Lets focus on basic data analysis and the cities locations.

In [ ]:
# import libraries 
import requests
import json
import time
from dotenv import load_dotenv
import os
import pandas as pd

# Configuration

pd.set_option('display.max_columns', None) # display each column's dataframe

# 1. Call api

## Call api nominatim

In [2]:
# import requests

nominatim_url = "https://nominatim.openstreetmap.org/search"
cities_info = f"{nominatim_url}/cities_location.json"

params = {
    "country": "France",
    "city": "Bayeux",
    "format": "geocodejson"
}

headers = {"User-Agent": "projet_etude_dataviz (lnmourez@gmail.com)"}

### Fetch cities information

In [3]:
# import json

nominatim_response = requests.get(nominatim_url, params=params, headers=headers) # call api

print(nominatim_response) # call api status code 
print(nominatim_response.content) # take a look at the data that was recieved along with this response
#print(json.dumps(response.json(), indent=2)) # add json indentation

<Response [200]>
b'{"type":"FeatureCollection","geocoding":{"version":"0.1.0","attribution":"Data \xc2\xa9 OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright","licence":"ODbL","query":"Bayeux, France"},"features":[{"type":"Feature","properties":{"geocoding":{"place_id":283731646,"osm_type":"relation","osm_id":145776,"osm_key":"boundary","osm_value":"administrative","type":"city","label":"Bayeux, Calvados, Normandie, France m\xc3\xa9tropolitaine, 14400, France","name":"Bayeux"}},"geometry":{"type": "Point","coordinates": [-0.7024738, 49.2764624]}},{"type":"Feature","properties":{"geocoding":{"place_id":281505575,"osm_type":"relation","osm_id":1656892,"osm_key":"boundary","osm_value":"administrative","type":"city","label":"Bayeux, Calvados, Normandie, France m\xc3\xa9tropolitaine, France","name":"Bayeux"}},"geometry":{"type": "Point","coordinates": [-0.791677, 49.2455634]}}]}'

In [4]:
type(nominatim_response.json())  # display type

dict

#### Fetch one city location

In [5]:
feature = nominatim_response.json()["features"][0] # declare the first result
city = feature["properties"]["geocoding"]["name"]
place_id = feature["properties"]["geocoding"]["place_id"]
lat = feature["geometry"]["coordinates"][1]
lon = feature["geometry"]["coordinates"][0]
print(f"{city}, {place_id},{lon}, {lat}")

Bayeux, 283731646,-0.7024738, 49.2764624

#### Fetch the cities list location

In the provided cities list, we observe that :
1) Ariège is a department. 
2) Gorges du Verdon and Chateau du haut Koenigsbourg are tourist sites

It could be interesting to search some nearby locations. 

Ariège :
- https://www.guide-toulouse-pyrenees.com/fr/experiences/culturelle/article-les-plus-beaux-villages-de-l-ariege-106.html
- https://www.sites-touristiques-ariege.fr/informations-pratiques/visiter-lariege/

Bédeilhac-et-Aynat
Camon
Carla-Bayle
Foix
Le Mas-d’Azil
Mirepoix
Montségur
Niaux
Saint-Lizier
Saint-Martin-d’Oydes
Tarascon-sur-Ariège

Gorges du Verdon : 
https://lesgorgesduverdon.fr/a-visiter/

Barjols
Castellane
Cotignac
Moustiers-Sainte-Marie
Sainte-Croix-du-Verdon
Sillans-la-Cascade
Valensole

Chateau du haut Koenigsbourg (ORSCHWILLER)
https://www.haut-koenigsbourg.fr/infos-pratiques/

In [ ]:
import time

cities_info = []
cities = ["Aigues Mortes",
"Aix en Provence",
"Amiens",
"Annecy",
"Avignon",
"Barjols",
"Bayeux",
"Bayonne",
"Besancon",
"Biarritz",
"Bormes les Mimosas",
"Bédeilhac-et-Aynat",
"Camon",
"Carcassonne",
"Carla-Bayle",
"Cassis",
"Castellane",
"Collioure",
"Colmar",
"Cotignac",
"Dijon",
"Eguisheim",
"Foix",
"Grenoble",
"La Rochelle",
"Le Havre",
"Le Mas-d’Azil",
"Lille",
"Lyon",
"Marseille",
"Mirepoix",
"Mont Saint Michel",
"Montauban",
"Montségur",
"Moustiers-Sainte-Marie",
"Niaux",
"Nimes",
"Orschwiller",
"Paris",
"Rouen",
"Saint-Lizier",
"Saint-Martin-d’Oydes",
"Sainte-Croix-du-Verdon",
"Saintes Maries de la mer",
"Sillans-la-Cascade",
"St Malo",
"Strasbourg",
"Tarascon-sur-Ariège",
"Toulouse",
"Uzes",
"Valensole"
]

for city in cities:
    try:
        nominatim_response = requests.get(
            nominatim_url, 
            params={"country": "France",
            "city": city,
            "format": "geocodejson"
            },
            headers=headers)
        # print(f"{city}: {response.status_code}")  # vérifiez le code HTTP


        feature = nominatim_response.json()["features"][0]
        cities_info.append({"city" : feature["properties"]["geocoding"]["name"],
        "place_id" : feature["properties"]["geocoding"]["place_id"],
        "lat" : feature["geometry"]["coordinates"][1],
        "lon" : feature["geometry"]["coordinates"][0]
        })
    except (IndexError, KeyError, requests.exceptions.RequestException):
        print(f"Execution with errors for {city} : {nominatim_response.status_code}")
      
    time.sleep(2)

In [7]:
# import json

print(len(cities_info))
print(cities_info)
#print(json.dumps(cities_location, indent=2))

51
[{'city': 'Aigues-Mortes', 'place_id': 83174366, 'lat': 43.5661521, 'lon': 4.19154}, {'city': 'Aix-en-Provence', 'place_id': 82709709, 'lat': 43.5298424, 'lon': 5.4474738}, {'city': 'Amiens', 'place_id': 99360340, 'lat': 49.8941708, 'lon': 2.2956951}, {'city': 'Annecy', 'place_id': 88514330, 'lat': 45.8992348, 'lon': 6.1288847}, {'city': 'Avignon', 'place_id': 82414561, 'lat': 43.9492493, 'lon': 4.8059012}, {'city': 'Barjols', 'place_id': 82795376, 'lat': 43.558133, 'lon': 6.0056803}, {'city': 'Bayeux', 'place_id': 283731646, 'lat': 49.2764624, 'lon': -0.7024738}, {'city': 'Bayonne', 'place_id': 291532516, 'lat': 43.4945144, 'lon': -1.4736657}, {'city': 'Besançon', 'place_id': 92553994, 'lat': 47.2380222, 'lon': 6.0243622}, {'city': 'Biarritz', 'place_id': 287222151, 'lat': 43.4832523, 'lon': -1.5592776}, {'city': 'Bormes-les-Mimosas', 'place_id': 81776233, 'lat': 43.1506968, 'lon': 6.3419285}, {'city': 'Bédeilhac-et-Aynat', 'place_id': 84249524, 'lat': 42.8816132, 'lon': 1.5674969}, {'city': 'Camon', 'place_id': 99997574, 'lat': 49.8874246, 'lon': 2.3446546}, {'city': 'Carcassonne', 'place_id': 84898345, 'lat': 43.2130358, 'lon': 2.3491069}, {'city': 'Le Carla-Bayle', 'place_id': 86409456, 'lat': 43.1500386, 'lon': 1.3936011}, {'city': 'Cassis', 'place_id': 83023230, 'lat': 43.2140359, 'lon': 5.5396318}, {'city': 'Castellane', 'place_id': 83230701, 'lat': 43.846459, 'lon': 6.5134463}, {'city': 'Collioure', 'place_id': 84280626, 'lat': 42.52505, 'lon': 3.0831554}, {'city': 'Colmar', 'place_id': 122171492, 'lat': 48.0777517, 'lon': 7.3579641}, {'city': 'Cotignac', 'place_id': 89393394, 'lat': 43.5280531, 'lon': 6.1502672}, {'city': 'Dijon', 'place_id': 93940430, 'lat': 47.3215806, 'lon': 5.0414701}, {'city': 'Eguisheim', 'place_id': 121333649, 'lat': 48.0447968, 'lon': 7.3079618}, {'city': 'Foix', 'place_id': 83990922, 'lat': 42.9638998, 'lon': 1.6053807}, {'city': 'Grenoble', 'place_id': 89646215, 'lat': 45.1875602, 'lon': 5.7357819}, {'city': 'La Rochelle', 'place_id': 289326024, 'lat': 46.159732, 'lon': -1.1515951}, {'city': 'Le Havre', 'place_id': 100021883, 'lat': 49.4938975, 'lon': 0.1079732}, {'city': "Le Mas-d'Azil", 'place_id': 85533908, 'lat': 43.0794579, 'lon': 1.3613197}, {'city': 'Lille', 'place_id': 101870667, 'lat': 50.6365654, 'lon': 3.0635282}, {'city': 'Lyon', 'place_id': 90160981, 'lat': 45.7578137, 'lon': 4.8320114}, {'city': 'Marseille', 'place_id': 83042786, 'lat': 43.2963986, 'lon': 5.3777888}, {'city': 'Mirepoix', 'place_id': 85916870, 'lat': 43.7458333, 'lon': 0.6719444}, {'city': 'Mont Saint-Michel', 'place_id': 119406788, 'lat': 48.6906803, 'lon': 5.8826485}, {'city': 'Montauban', 'place_id': 85485907, 'lat': 44.0175835, 'lon': 1.3549991}, {'city': 'Montségur', 'place_id': 84371924, 'lat': 42.8707548, 'lon': 1.8337452}, {'city': 'Moustiers-Sainte-Marie', 'place_id': 82649540, 'lat': 43.8460089, 'lon': 6.2217604}, {'city': 'Niaux', 'place_id': 84684813, 'lat': 42.8093089, 'lon': 1.5911122}, {'city': 'Nîmes', 'place_id': 82204290, 'lat': 43.8374249, 'lon': 4.3600687}, {'city': 'Orschwiller', 'place_id': 121122082, 'lat': 48.2422436, 'lon': 7.3799809}, {'city': 'Paris', 'place_id': 97554783, 'lat': 48.8588897, 'lon': 2.320041}, {'city': 'Rouen', 'place_id': 99438300, 'lat': 49.4404591, 'lon': 1.0939658}, {'city': 'Saint-Lizier', 'place_id': 84167605, 'lat': 43.0025191, 'lon': 1.1354926}, {'city': "Saint-Martin-d'Oydes", 'place_id': 85314031, 'lat': 43.169734, 'lon': 1.4955303}, {'city': 'Sainte-Croix-du-Verdon', 'place_id': 82903247, 'lat': 43.7589451, 'lon': 6.1518294}, {'city': 'Saintes-Maries-de-la-Mer', 'place_id': 82819543, 'lat': 43.4515922, 'lon': 4.4277202}, {'city': 'Sillans-la-Cascade', 'place_id': 81887886, 'lat': 43.5673969, 'lon': 6.1795387}, {'city': 'Saint-Malo', 'place_id': 284423924, 'lat': 48.649518, 'lon': -2.0260409}, {'city': 'Strasbourg', 'place_id': 120878363, 'lat': 48.584614, 'lon': 7.7507127}, {'city': 'Tarascon-sur-Ariège', 'place_id': 84404745, 'lat': 42.8492109, 'lon': 1.6043495}, {'city': 'Toulouse', 'place_id': 85889491, 'lat': 43.6044638, 'lon': 1.4442433}, {'city': 'Uzès', 'place_id': 87817750, 'lat': 44.0121279, 'lon': 4.4196718}, {'city': 'Valensole', 'place_id': 82836030, 'lat': 43.8379283, 'lon': 5.9839867}]

## 2. Call api openweathermap

In [8]:
# from dotenv import load_dotenv
# import os

# V2.5 https://api.openweathermap.org/data/2.5/weather
# V4.0 https://api.openweathermap.org/data/4.0/onecall/current

weather_url = "https://api.openweathermap.org/data/4.0/onecall/current"
params = {
    "lat":"48.635954",
    "lon":"-1.511460",
    "units":"metric",
    "appid": os.getenv("API_KEY")
}

### Fetch weather information

In [9]:
weather_response = requests.get(weather_url, params=params) # call api
weather_json = weather_response.json()

print(weather_response, weather_json)

<Response [200]> {'lat': 48.636, 'lon': -1.5115, 'timezone': 'Europe/Paris', 'timezone_offset': 7200, 'data': [{'dt': 1787605732, 'sunrise': 1787548306, 'sunset': 1787598335, 'temp': 19.25, 'feels_like': 18.98, 'pressure': 1009, 'humidity': 67, 'dew_point': 12.98, 'uvi': 0, 'clouds': 98, 'visibility': 10000, 'wind_speed': 2.45, 'wind_deg': 112, 'wind_gust': 4.85, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}]}]}

In [ ]:
weather_info = []
for city in cities_info:
    try:
        params = {
            "lat": city["lat"], 
            "lon": city["lon"], 
            "units": "metric", 
            "appid": os.getenv("API_KEY")
            }
        weather_response = requests.get(weather_url, params=params)
        weather = weather_response.json()
        weather['city'] = city['city'] #weather_info.append({"city": city["city"], "weather": weather_response.json()})
        weather_info.append(weather)
    except (IndexError, KeyError, requests.exceptions.RequestException):
        print(f"Execution with errors for {city} : {weather_response.status_code}")
    time.sleep(2)

In [11]:
print(cities_info[0].keys())  # display keys

dict_keys(['city', 'place_id', 'lat', 'lon'])

In [12]:
print(weather_info[0].keys())  # display keys

dict_keys(['lat', 'lon', 'timezone', 'timezone_offset', 'data', 'city'])

In [13]:
# print(json.dumps(weather_info, indent=2))

In [14]:
type(weather_info)

list

In [15]:
weather_info

[{'lat': 43.5662,
  'lon': 4.1915,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605733,
    'sunrise': 1787547477,
    'sunset': 1787596427,
    'temp': 17.98,
    'feels_like': 18.44,
    'pressure': 1011,
    'humidity': 100,
    'dew_point': 17.98,
    'uvi': 0,
    'clouds': 28,
    'visibility': 10000,
    'wind_speed': 2.57,
    'wind_deg': 20,
    'weather': [{'id': 802,
      'main': 'Clouds',
      'description': 'scattered clouds',
      'icon': '03n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824201529.676033:FR812:94f59fc1a21af4b942bfebe6251eac4d',
     '2.49.0.0.250.0.FR.20260824210057.274022:FR812:94f59fc1a21af4b942bfebe6251eac4d',
     '2.49.0.0.250.0.FR.20260824210105.987023:FR812:94f59fc1a21af4b942bfebe6251eac4d']}],
  'city': 'Aigues-Mortes'},
 {'lat': 43.5298,
  'lon': 5.4475,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605735,
    'sunrise': 1787547179,
    'sunset': 1787596122,
    'temp': 17.71,
    'feels_like': 17.94,
    'pressure': 1011,
    'humidity': 92,
    'dew_point': 16.39,
    'uvi': 0,
    'clouds': 65,
    'visibility': 10000,
    'wind_speed': 3.58,
    'wind_deg': 190,
    'wind_gust': 7.48,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260823160038.133023:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.0.FR.20260824060247.149023:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.0.FR.20260824210057.274022:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.0.FR.20260824210100.690033:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.1.FR.20260824210110.230024:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.1.FR.20260824210125.290024:FR824:3082e785eda196602d4373ec597f3e9c']}],
  'city': 'Aix-en-Provence'},
 {'lat': 49.8942,
  'lon': 2.2957,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605738,
    'sunrise': 1787547239,
    'sunset': 1787597574,
    'temp': 18.92,
    'feels_like': 18.43,
    'pressure': 1012,
    'humidity': 60,
    'dew_point': 10.99,
    'uvi': 0,
    'clouds': 62,
    'visibility': 10000,
    'wind_speed': 4.98,
    'wind_deg': 68,
    'wind_gust': 12.5,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824210121.328023:FR223:f8fd809be70dfdab07c919e4abde1fd6']}],
  'city': 'Amiens'},
 {'lat': 45.8992,
  'lon': 6.1289,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605741,
    'sunrise': 1787546776,
    'sunset': 1787596198,
    'temp': 20.08,
    'feels_like': 20.31,
    'pressure': 1012,
    'humidity': 83,
    'dew_point': 17.1,
    'uvi': 0,
    'clouds': 100,
    'visibility': 10000,
    'wind_speed': 2.06,
    'wind_deg': 260,
    'weather': [{'id': 501,
      'main': 'Rain',
      'description': 'moderate rain',
      'icon': '10n'}],
    'rain': {'1h': 1.57},
    'alerts': ['2.49.0.0.250.0.FR.20260824210105.987023:FR718:eb0fc523c9177c0d11476a87150f6ac0']}],
  'city': 'Annecy'},
 {'lat': 43.9492,
  'lon': 4.8059,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605743,
    'sunrise': 1787547292,
    'sunset': 1787596317,
    'temp': 19.05,
    'feels_like': 19.47,
    'pressure': 1012,
    'humidity': 94,
    'dew_point': 18.06,
    'uvi': 0,
    'clouds': 82,
    'visibility': 10000,
    'wind_speed': 2.57,
    'wind_deg': 340,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824210057.274022:FR826:340762cc63b0c80dd9d55361d29403aa',
     '2.49.0.0.250.0.FR.20260824210105.987023:FR826:340762cc63b0c80dd9d55361d29403aa',
     '2.49.0.0.250.1.FR.20260824210110.230024:FR826:340762cc63b0c80dd9d55361d29403aa',
     '2.49.0.0.250.1.FR.20260824210125.290024:FR826:340762cc63b0c80dd9d55361d29403aa']}],
  'city': 'Avignon'},
 {'lat': 43.5581,
  'lon': 6.0057,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605746,
    'sunrise': 1787547042,
    'sunset': 1787595991,
    'temp': 16.94,
    'feels_like': 17.12,
    'pressure': 1012,
    'humidity': 93,
    'dew_point': 15.8,
    'uvi': 0,
    'clouds': 78,
    'visibility': 6052,
    'wind_speed': 0.6,
    'wind_deg': 166,
    'wind_gust': 0.63,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260823160038.133023:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.0.FR.20260824060247.149023:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.0.FR.20260824210057.274022:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.0.FR.20260824210100.690033:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.1.FR.20260824210110.230024:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.1.FR.20260824210125.290024:FR825:50016682f57d00586bebeed8b77c6d42']}],
  'city': 'Barjols'},
 {'lat': 49.2765,
  'lon': -0.7025,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605749,
    'sunrise': 1787548035,
    'sunset': 1787598217,
    'temp': 21.14,
    'feels_like': 20.82,
    'pressure': 1010,
    'humidity': 58,
    'dew_point': 12.56,
    'uvi': 0,
    'clouds': 80,
    'visibility': 10000,
    'wind_speed': 7.16,
    'wind_deg': 67,
    'wind_gust': 14,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824210105.987023:FR251:9ac75691e728f773f711cc8fc73204db',
     '2.49.0.0.250.0.FR.20260824210121.328023:FR251:9ac75691e728f773f711cc8fc73204db']}],
  'city': 'Bayeux'},
 {'lat': 43.4945,
  'lon': -1.4737,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605751,
    'sunrise': 1787548844,
    'sunset': 1787597778,
    'temp': 23.42,
    'feels_like': 23.72,
    'pressure': 1010,
    'humidity': 73,
    'dew_point': 18.31,
    'uvi': 0,
    'clouds': 45,
    'visibility': 10000,
    'wind_speed': 2.06,
    'wind_deg': 160,
    'weather': [{'id': 802,
      'main': 'Clouds',
      'description': 'scattered clouds',
      'icon': '03n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824210105.987023:FR615:a512b287066f8f19b5b02accccec835d']}],
  'city': 'Bayonne'},
 {'lat': 47.238,
  'lon': 6.0244,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605754,
    'sunrise': 1787546656,
    'sunset': 1787596368,
    'temp': 18.02,
    'feels_like': 18.23,
    'pressure': 1011,
    'humidity': 90,
    'dew_point': 16.36,
    'uvi': 0,
    'clouds': 99,
    'visibility': 10000,
    'wind_speed': 1.22,
    'wind_deg': 129,
    'wind_gust': 1.01,
    'weather': [{'id': 502,
      'main': 'Rain',
      'description': 'heavy intensity rain',
      'icon': '10n'}],
    'rain': {'1h': 14.3},
    'alerts': ['2.49.0.0.250.0.FR.20260824210105.987023:FR431:985d7e72720aa41086d415fd5dbedb43']}],
  'city': 'Besançon'},
 {'lat': 43.4833,
  'lon': -1.5593,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605757,
    'sunrise': 1787548866,
    'sunset': 1787597798,
    'temp': 23.3,
    'feels_like': 23.59,
    'pressure': 1010,
    'humidity': 73,
    'dew_point': 18.19,
    'uvi': 0,
    'clouds': 43,
    'visibility': 10000,
    'wind_speed': 2.06,
    'wind_deg': 160,
    'weather': [{'id': 802,
      'main': 'Clouds',
      'description': 'scattered clouds',
      'icon': '03n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824210105.987023:FR615:a512b287066f8f19b5b02accccec835d']}],
  'city': 'Biarritz'},
 {'lat': 43.1507,
  'lon': 6.3419,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605759,
    'sunrise': 1787547000,
    'sunset': 1787595872,
    'temp': 19.42,
    'feels_like': 19.74,
    'pressure': 1011,
    'humidity': 89,
    'dew_point': 17.56,
    'uvi': 0,
    'clouds': 31,
    'visibility': 10000,
    'wind_speed': 4.12,
    'wind_deg': 350,
    'weather': [{'id': 501,
      'main': 'Rain',
      'description': 'moderate rain',
      'icon': '10n'}],
    'rain': {'1h': 1.54},
    'alerts': ['2.49.0.0.250.0.FR.20260823160038.133023:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.0.FR.20260824060247.149023:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.0.FR.20260824210057.274022:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.0.FR.20260824210100.690033:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.1.FR.20260824210110.230024:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.1.FR.20260824210125.290024:FR825:50016682f57d00586bebeed8b77c6d42']}],
  'city': 'Bormes-les-Mimosas'},
 {'lat': 42.8816,
  'lon': 1.5675,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605762,
    'sunrise': 1787548172,
    'sunset': 1787596991,
    'temp': 17.06,
    'feels_like': 16.94,
    'pressure': 1013,
    'humidity': 81,
    'dew_point': 13.78,
    'uvi': 0,
    'clouds': 22,
    'visibility': 10000,
    'wind_speed': 3.06,
    'wind_deg': 194,
    'wind_gust': 3.21,
    'weather': [{'id': 801,
      'main': 'Clouds',
      'description': 'few clouds',
      'icon': '02n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824201534.879023:FR621:04913bcb1f94cd1cab4451e22b84c7d3']}],
  'city': 'Bédeilhac-et-Aynat'},
 {'lat': 49.8874,
  'lon': 2.3447,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605764,
    'sunrise': 1787547228,
    'sunset': 1787597562,
    'temp': 18.51,
    'feels_like': 17.98,
    'pressure': 1012,
    'humidity': 60,
    'dew_point': 10.61,
    'uvi': 0,
    'clouds': 62,
    'visibility': 10000,
    'wind_speed': 5.01,
    'wind_deg': 67,
    'wind_gust': 12.5,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824210121.328023:FR223:f8fd809be70dfdab07c919e4abde1fd6']}],
  'city': 'Camon'},
 {'lat': 43.213,
  'lon': 2.3491,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605767,
    'sunrise': 1787547953,
    'sunset': 1787596835,
    'temp': 18.19,
    'feels_like': 18.44,
    'pressure': 1011,
    'humidity': 91,
    'dew_point': 16.7,
    'uvi': 0,
    'clouds': 24,
    'visibility': 10000,
    'wind_speed': 1.54,
    'wind_deg': 0,
    'weather': [{'id': 801,
      'main': 'Clouds',
      'description': 'few clouds',
      'icon': '02n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824180159.532033:FR811:bf4d986d580e6166331b65072cc6a799',
     '2.49.0.0.250.0.FR.20260824210105.987023:FR811:bf4d986d580e6166331b65072cc6a799']}],
  'city': 'Carcassonne'},
 {'lat': 43.15,
  'lon': 1.3936,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605770,
    'sunrise': 1787548189,
    'sunset': 1787597058,
    'temp': 20.23,
    'feels_like': 20.19,
    'pressure': 1011,
    'humidity': 72,
    'dew_point': 15.02,
    'uvi': 0,
    'clouds': 33,
    'visibility': 10000,
    'wind_speed': 1.36,
    'wind_deg': 28,
    'wind_gust': 2.37,
    'weather': [{'id': 802,
      'main': 'Clouds',
      'description': 'scattered clouds',
      'icon': '03n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824201534.879023:FR621:04913bcb1f94cd1cab4451e22b84c7d3']}],
  'city': 'Le Carla-Bayle'},
 {'lat': 43.214,
  'lon': 5.5396,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605772,
    'sunrise': 1787547187,
    'sunset': 1787596070,
    'temp': 27.45,
    'feels_like': 31.92,
    'pressure': 1009,
    'humidity': 89,
    'dew_point': 25.47,
    'uvi': 0,
    'clouds': 53,
    'visibility': 10000,
    'wind_speed': 5.23,
    'wind_deg': 142,
    'wind_gust': 6.67,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260823160038.133023:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.0.FR.20260824060247.149023:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.0.FR.20260824210057.274022:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.0.FR.20260824210100.690033:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.1.FR.20260824210110.230024:FR824:3082e785eda196602d4373ec597f3e9c',
     '2.49.0.0.250.1.FR.20260824210125.290024:FR824:3082e785eda196602d4373ec597f3e9c']}],
  'city': 'Cassis'},
 {'lat': 43.8465,
  'lon': 6.5134,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605775,
    'sunrise': 1787546892,
    'sunset': 1787595898,
    'temp': 16.5,
    'feels_like': 16.45,
    'pressure': 1014,
    'humidity': 86,
    'dew_point': 14.15,
    'uvi': 0,
    'clouds': 69,
    'visibility': 5949,
    'wind_speed': 1.15,
    'wind_deg': 18,
    'wind_gust': 0.94,
    'weather': [{'id': 502,
      'main': 'Rain',
      'description': 'heavy intensity rain',
      'icon': '10n'}],
    'rain': {'1h': 8.65},
    'alerts': ['2.49.0.0.250.0.FR.20260824210105.987023:FR821:d609c44147f27994a0a2ecb9eaa774f3']}],
  'city': 'Castellane'},
 {'lat': 42.5251,
  'lon': 3.0832,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605778,
    'sunrise': 1787547842,
    'sunset': 1787596594,
    'temp': 23.59,
    'feels_like': 24.04,
    'pressure': 1012,
    'humidity': 78,
    'dew_point': 19.53,
    'uvi': 0,
    'clouds': 48,
    'visibility': 10000,
    'wind_speed': 1.36,
    'wind_deg': 305,
    'wind_gust': 1.75,
    'weather': [{'id': 802,
      'main': 'Clouds',
      'description': 'scattered clouds',
      'icon': '03n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824180159.532033:FR815:b3a98ba6880b725b376f2e88f86ac4f6',
     '2.49.0.0.250.0.FR.20260824210105.987023:FR815:b3a98ba6880b725b376f2e88f86ac4f6']}],
  'city': 'Collioure'},
 {'lat': 48.0778,
  'lon': 7.358,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605780,
    'sunrise': 1787546241,
    'sunset': 1787596144,
    'temp': 17.81,
    'feels_like': 17.4,
    'pressure': 1012,
    'humidity': 67,
    'dew_point': 11.61,
    'uvi': 0,
    'clouds': 84,
    'visibility': 10000,
    'wind_speed': 5.8,
    'wind_deg': 13,
    'wind_gust': 6.9,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04n'}]}],
  'city': 'Colmar'},
 {'lat': 43.5281,
  'lon': 6.1503,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605783,
    'sunrise': 1787547010,
    'sunset': 1787595954,
    'temp': 17.06,
    'feels_like': 17.22,
    'pressure': 1012,
    'humidity': 92,
    'dew_point': 15.75,
    'uvi': 0,
    'clouds': 62,
    'visibility': 9542,
    'wind_speed': 0.16,
    'wind_deg': 285,
    'wind_gust': 0.8,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260823160038.133023:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.0.FR.20260824060247.149023:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.0.FR.20260824210057.274022:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.0.FR.20260824210100.690033:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.1.FR.20260824210110.230024:FR825:50016682f57d00586bebeed8b77c6d42',
     '2.49.0.0.250.1.FR.20260824210125.290024:FR825:50016682f57d00586bebeed8b77c6d42']}],
  'city': 'Cotignac'},
 {'lat': 47.3216,
  'lon': 5.0415,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605786,
    'sunrise': 1787546883,
    'sunset': 1787596613,
    'temp': 17.8,
    'feels_like': 18.09,
    'pressure': 1011,
    'humidity': 94,
    'dew_point': 16.82,
    'uvi': 0,
    'clouds': 100,
    'visibility': 10000,
    'wind_speed': 2.06,
    'wind_deg': 150,
    'weather': [{'id': 804,
      'main': 'Clouds',
      'description': 'overcast clouds',
      'icon': '04n'}],
    'rain': {'1h': 0.1},
    'alerts': ['2.49.0.0.250.0.FR.20260824210105.987023:FR261:f4eff213f202e5a08928183b7a0261f6',
     '2.49.0.0.250.0.FR.20260824210121.328023:FR261:f4eff213f202e5a08928183b7a0261f6']}],
  'city': 'Dijon'},
 {'lat': 48.0448,
  'lon': 7.308,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605788,
    'sunrise': 1787546256,
    'sunset': 1787596152,
    'temp': 17.72,
    'feels_like': 17.32,
    'pressure': 1012,
    'humidity': 68,
    'dew_point': 11.75,
    'uvi': 0,
    'clouds': 93,
    'visibility': 10000,
    'wind_speed': 5.8,
    'wind_deg': 13,
    'wind_gust': 6.9,
    'weather': [{'id': 804,
      'main': 'Clouds',
      'description': 'overcast clouds',
      'icon': '04n'}]}],
  'city': 'Eguisheim'},
 {'lat': 42.9639,
  'lon': 1.6054,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605791,
    'sunrise': 1787548156,
    'sunset': 1787596989,
    'temp': 20,
    'feels_like': 20.17,
    'pressure': 1012,
    'humidity': 81,
    'dew_point': 16.64,
    'uvi': 0,
    'clouds': 22,
    'visibility': 10000,
    'wind_speed': 1.9,
    'wind_deg': 184,
    'wind_gust': 1.82,
    'weather': [{'id': 801,
      'main': 'Clouds',
      'description': 'few clouds',
      'icon': '02n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824201534.879023:FR621:04913bcb1f94cd1cab4451e22b84c7d3']}],
  'city': 'Foix'},
 {'lat': 45.1876,
  'lon': 5.7358,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605793,
    'sunrise': 1787546944,
    'sunset': 1787596218,
    'temp': 19.87,
    'feels_like': 20.29,
    'pressure': 1012,
    'humidity': 91,
    'dew_point': 18.36,
    'uvi': 0,
    'clouds': 100,
    'visibility': 10000,
    'wind_speed': 2.16,
    'wind_deg': 267,
    'wind_gust': 3.72,
    'weather': [{'id': 503,
      'main': 'Rain',
      'description': 'very heavy rain',
      'icon': '10n'}],
    'rain': {'1h': 23.68},
    'alerts': ['2.49.0.0.250.0.FR.20260824210105.987023:FR714:cd05c2700aeb585b71de18aee6a44a20']}],
  'city': 'Grenoble'},
 {'lat': 46.1597,
  'lon': -1.1516,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605796,
    'sunrise': 1787548497,
    'sunset': 1787597971,
    'temp': 21.91,
    'feels_like': 22.22,
    'pressure': 1007,
    'humidity': 79,
    'dew_point': 18.1,
    'uvi': 0,
    'clouds': 100,
    'visibility': 10000,
    'wind_speed': 4.63,
    'wind_deg': 120,
    'weather': [{'id': 804,
      'main': 'Clouds',
      'description': 'overcast clouds',
      'icon': '04n'}],
    'alerts': ['2.49.0.0.250.0.FR.20260824190552.513023:FR532:8f9b039c22d0d4c8a90c1659e2850234']}],
  'city': 'La Rochelle'},
 {'lat': 49.4939,
  'lon': 0.108,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605799,
    'sunrise': 1787547814,
    'sunset': 1787598049,
    'temp': 19.46,
    'feels_like': 18.95,
    'pressure': 1010,
    'humidity': 57,
    'dew_point': 10.73,
    'uvi': 0,
    'clouds': 44,
    'visibility': 10000,
    'wind_speed': 5.66,
    'wind_deg': 80,
    'weather': [{'id': 500,
      'main': 'Rain',
      'description': 'light rain',
      'icon': '10n'}],
    'rain': {'1h': 0.37},
    'alerts': ['2.49.0.0.250.0.FR.20260824210105.987023:FR232:b9ca224072791e8245021648a9f883a4',
     '2.49.0.0.250.0.FR.20260824210121.328023:FR232:b9ca224072791e8245021648a9f883a4']}],
  'city': 'Le Havre'},
 {'lat': 43.0795,
  'lon': 1.3613,
  'timezone': 'Europe/Paris',
  'timezone_offset': 7200,
  'data': [{'dt': 1787605801,
    'sunrise': 1787548203,
    'sunset': 1787597059,
    'temp': 20.74,
    'feels_like': 20.75,
    'pressure': 1011,
    'humidity': 72,
    'dew_point': 15.51,
    'uvi': 0,
    'clouds': 26,
    'visibility': 10000,
    'wind_speed': 0.38,
    'wind_deg': 337,

# 2. Convert list to DataFrame

## cities dataframe convertion

In [ ]:
# import pandas as pd

cities_df = pd.DataFrame(cities_info)

## weather normalization

In [17]:
weather_df = pd.json_normalize(weather_info)

In [18]:
type(cities_df)

pandas.core.frame.DataFrame

In [19]:
type(weather_df)

pandas.core.frame.DataFrame

In [20]:
cities_df.head(1)

            city  place_id        lat      lon
0  Aigues-Mortes  83174366  43.566152  4.19154

In [21]:
weather_df.head(1)

,lat,lon,timezone,timezone_offset,data,city
0,43.5662,4.1915,Europe/Paris,7200,"[{'dt': 1787605733, 'sunrise': 1787547477, 'su...",Aigues-Mortes

In [22]:
weather = pd.json_normalize(weather_df['data'])
weather = weather.rename(columns={0:'data'})

In [23]:
weather.head(1)

                                                data
0  {'dt': 1787605733, 'sunrise': 1787547477, 'sun...

In [24]:
weather2 = pd.json_normalize(weather.to_dict(orient="records"))
# weather2 = weather2.add_prefix("weather.")

In [25]:
weather2.head(1)

,data.dt,data.sunrise,data.sunset,data.temp,data.feels_like,data.pressure,data.humidity,data.dew_point,data.uvi,data.clouds,data.visibility,data.wind_speed,data.wind_deg,data.weather,data.alerts,data.wind_gust,data.rain.1h
0,1787605733,1787547477,1787596427,17.98,18.44,1011,100,17.98,0,28,10000,2.57,20,"[{'id': 802, 'main': 'Clouds', 'description': ...",[2.49.0.0.250.0.FR.20260824201529.676033:FR812...,NaN,NaN

In [26]:
weather3 = pd.json_normalize(weather2['data.weather'])
weather3 = weather3.rename(columns={0:'data.'})

In [27]:
weather3.head(1)

                                               data.
0  {'id': 802, 'main': 'Clouds', 'description': '...

In [28]:
weather4 = pd.json_normalize(weather3['data.'])

In [29]:
weather4.head(1)

    id    main       description icon
0  802  Clouds  scattered clouds  03n

In [30]:
weather_df = pd.concat(
    [weather_df.drop(columns="data"),
    weather2.drop(columns="data.weather"),
    weather4],
    axis=1)

In [ ]:
# pd.set_option('display.max_columns', None) # display each column's dataframe

weather_df.head(1)

,lat,lon,timezone,timezone_offset,city,data.dt,data.sunrise,data.sunset,data.temp,data.feels_like,data.pressure,data.humidity,data.dew_point,data.uvi,data.clouds,data.visibility,data.wind_speed,data.wind_deg,data.alerts,data.wind_gust,data.rain.1h,id,main,description,icon
0,43.5662,4.1915,Europe/Paris,7200,Aigues-Mortes,1787605733,1787547477,1787596427,17.98,18.44,1011,100,17.98,0,28,10000,2.57,20,[2.49.0.0.250.0.FR.20260824201529.676033:FR812...,NaN,NaN,802,Clouds,scattered clouds,03n

In [32]:
weather_df.columns

Index(['lat', 'lon', 'timezone', 'timezone_offset', 'city', 'data.dt',
       'data.sunrise', 'data.sunset', 'data.temp', 'data.feels_like',
       'data.pressure', 'data.humidity', 'data.dew_point', 'data.uvi',
       'data.clouds', 'data.visibility', 'data.wind_speed', 'data.wind_deg',
       'data.alerts', 'data.wind_gust', 'data.rain.1h', 'id', 'main',
       'description', 'icon'],
      dtype='object')

# 3. Merge DataFrames on 'city'

In [33]:
current_weather = pd.merge(cities_df, weather_df, on='city')

# Display key columns
print("\nCurrent weather:")
current_weather.head()

Current weather:

,city,place_id,lat_x,lon_x,lat_y,lon_y,timezone,timezone_offset,data.dt,data.sunrise,data.sunset,data.temp,data.feels_like,data.pressure,data.humidity,data.dew_point,data.uvi,data.clouds,data.visibility,data.wind_speed,data.wind_deg,data.alerts,data.wind_gust,data.rain.1h,id,main,description,icon
0,Aigues-Mortes,83174366,43.566152,4.191540,43.5662,4.1915,Europe/Paris,7200,1787605733,1787547477,1787596427,17.98,18.44,1011,100,17.98,0,28,10000,2.57,20,[2.49.0.0.250.0.FR.20260824201529.676033:FR812...,NaN,NaN,802,Clouds,scattered clouds,03n
1,Aix-en-Provence,82709709,43.529842,5.447474,43.5298,5.4475,Europe/Paris,7200,1787605735,1787547179,1787596122,17.71,17.94,1011,92,16.39,0,65,10000,3.58,190,[2.49.0.0.250.0.FR.20260823160038.133023:FR824...,7.48,NaN,803,Clouds,broken clouds,04n
2,Amiens,99360340,49.894171,2.295695,49.8942,2.2957,Europe/Paris,7200,1787605738,1787547239,1787597574,18.92,18.43,1012,60,10.99,0,62,10000,4.98,68,[2.49.0.0.250.0.FR.20260824210121.328023:FR223...,12.50,NaN,803,Clouds,broken clouds,04n
3,Annecy,88514330,45.899235,6.128885,45.8992,6.1289,Europe/Paris,7200,1787605741,1787546776,1787596198,20.08,20.31,1012,83,17.10,0,100,10000,2.06,260,[2.49.0.0.250.0.FR.20260824210105.987023:FR718...,NaN,1.57,501,Rain,moderate rain,10n
4,Avignon,82414561,43.949249,4.805901,43.9492,4.8059,Europe/Paris,7200,1787605743,1787547292,1787596317,19.05,19.47,1012,94,18.06,0,82,10000,2.57,340,[2.49.0.0.250.0.FR.20260824210057.274022:FR826...,NaN,NaN,803,Clouds,broken clouds,04n

In [37]:
current_weather.sample(2)

,city,place_id,lat_x,lon_x,lat_y,lon_y,timezone,timezone_offset,data.dt,data.sunrise,data.sunset,data.temp,data.feels_like,data.pressure,data.humidity,data.dew_point,data.uvi,data.clouds,data.visibility,data.wind_speed,data.wind_deg,data.alerts,data.wind_gust,data.rain.1h,id,main,description,icon
23,Grenoble,89646215,45.18756,5.735782,45.1876,5.7358,Europe/Paris,7200,1787605793,1787546944,1787596218,19.87,20.29,1012,91,18.36,0,100,10000,2.16,267,[2.49.0.0.250.0.FR.20260824210105.987023:FR714...,3.72,23.68,503,Rain,very heavy rain,10n
31,Mont Saint-Michel,119406788,48.69068,5.882649,48.6907,5.8826,Europe/Paris,7200,1787605815,1787546524,1787596569,16.39,16.54,1012,94,15.42,0,99,10000,2.57,160,NaN,NaN,NaN,804,Clouds,overcast clouds,04n

In [35]:
type(current_weather)

pandas.core.frame.DataFrame

In [36]:
print(current_weather.head())

              city  place_id      lat_x     lon_x    lat_y   lon_y  \
0    Aigues-Mortes  83174366  43.566152  4.191540  43.5662  4.1915
1  Aix-en-Provence  82709709  43.529842  5.447474  43.5298  5.4475
2           Amiens  99360340  49.894171  2.295695  49.8942  2.2957
3           Annecy  88514330  45.899235  6.128885  45.8992  6.1289
4          Avignon  82414561  43.949249  4.805901  43.9492  4.8059

       timezone  timezone_offset     data.dt  data.sunrise  data.sunset  \
0  Europe/Paris             7200  1787605733    1787547477   1787596427
1  Europe/Paris             7200  1787605735    1787547179   1787596122
2  Europe/Paris             7200  1787605738    1787547239   1787597574
3  Europe/Paris             7200  1787605741    1787546776   1787596198
4  Europe/Paris             7200  1787605743    1787547292   1787596317

   data.temp  data.feels_like  data.pressure  data.humidity  data.dew_point  \
0      17.98            18.44           1011            100           17.98
1      17.71            17.94           1011             92           16.39
2      18.92            18.43           1012             60           10.99
3      20.08            20.31           1012             83           17.10
4      19.05            19.47           1012             94           18.06

   data.uvi  data.clouds  data.visibility  data.wind_speed  data.wind_deg  \
0         0           28            10000             2.57             20
1         0           65            10000             3.58            190
2         0           62            10000             4.98             68
3         0          100            10000             2.06            260
4         0           82            10000             2.57            340

                                         data.alerts  data.wind_gust  \
0  [2.49.0.0.250.0.FR.20260824201529.676033:FR812...             NaN
1  [2.49.0.0.250.0.FR.20260823160038.133023:FR824...            7.48
2  [2.49.0.0.250.0.FR.20260824210121.328023:FR223...           12.50
3  [2.49.0.0.250.0.FR.20260824210105.987023:FR718...             NaN
4  [2.49.0.0.250.0.FR.20260824210057.274022:FR826...             NaN

   data.rain.1h   id    main       description icon
0           NaN  802  Clouds  scattered clouds  03n
1           NaN  803  Clouds     broken clouds  04n
2           NaN  803  Clouds     broken clouds  04n
3          1.57  501    Rain     moderate rain  10n
4           NaN  803  Clouds     broken clouds  04n