In [19]:
import pandas as pd
import numpy as np
import json

In [2]:
final_df = pd.read_csv("/Users/nicolasbour/Desktop/Projets_IA /Projets_certif/02_kayak/data/final_data_test.csv")

In [3]:
final_df = final_df.drop(columns=['sys.type', 'sys.id', "sys.country", "coord.lon", "coord.lat", "cod", "base", "name", "id", "timezone", "place_id"])

In [6]:
pd.set_option('display.max_columns', None)
final_df.head(2)

,city,lat,lon,visibility,dt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,wind.gust,clouds.all,sys.sunrise,sys.sunset,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,hotels
0,mont saint michel,48.635954,-1.511460,10000,1787833888,24.25,24.01,24.25,24.25,1009,49,1009,1003,3.31,261,5.58,99,1787807759,1787857183,NaN,804,Clouds,couvert,04d,"[{'name': 'Hotel Rose', 'price': '€ 313', 'sco..."
1,saint malo,48.649518,-2.026041,10000,1787833889,23.29,23.24,23.21,23.29,1009,60,1009,1007,3.09,0,NaN,100,1787807882,1787857308,NaN,804,Clouds,couvert,04d,"[{'name': 'Kyriad Prestige Saint-Malo', 'price..."

In [69]:
hotels_df = final_df["hotels"]

In [74]:
type(hotels_df)

pandas.core.series.Series

In [104]:
import pandas as pd


def unwrap_hotels(value):
    # Tant qu'on a une liste qui contient UNE seule liste,
    # on enlève un niveau
    while (
        isinstance(value, list)
        and len(value) == 1
        and isinstance(value[0], list)
    ):
        value = value[0]

    return value


# 1. Nettoyer les listes imbriquées
hotel_lists = final_df["hotels"].apply(unwrap_hotels)


# 2. Vérification rapide
print(type(hotel_lists.iloc[0]))
print(len(hotel_lists.iloc[0]))
print(type(hotel_lists.iloc[0][0]))

<class 'str'>
3183
<class 'str'>

In [106]:
import pandas as pd
import ast


# 1. Transformer le texte en vraie liste Python
final_df["hotels"] = final_df["hotels"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)


# 2. Retirer les éventuels niveaux de listes inutiles
def unwrap_hotels(value):
    while (
        isinstance(value, list)
        and len(value) == 1
        and isinstance(value[0], list)
    ):
        value = value[0]

    return value


final_df["hotels"] = final_df["hotels"].apply(unwrap_hotels)


# 3. Vérifier la structure
print(type(final_df["hotels"].iloc[0]))
print(len(final_df["hotels"].iloc[0]))
print(type(final_df["hotels"].iloc[0][0]))

<class 'list'>
25
<class 'dict'>

In [108]:
# 4. Transformer les 25 hôtels en lignes
df_hotels = pd.DataFrame(
    final_df["hotels"].tolist(),
    index=final_df["city"]
).T


# 5. Renommer les lignes
df_hotels.index = [
    f"hotel_{i+1}"
    for i in range(len(df_hotels))
]


# 6. Nommer les axes
df_hotels.index.name = "hotel"
df_hotels.columns.name = "city"


# 7. Affichage
df_hotels.head(25)

city,mont saint michel,saint malo,bayeux,le havre,rouen,paris,amiens,lille,strasbourg,chateau du haut koenigsbourg,colmar,eguisheim,besancon,dijon,annecy,grenoble,lyon,gorges du verdon,bormes les mimosas,cassis,marseille,aix en provence,avignon,uzes,nimes,aigues mortes,saintes maries de la mer,collioure,carcassonne,ariege,toulouse,montauban,biarritz,bayonne,la rochelle
hotel,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
hotel_1,"{'name': 'Hotel Rose', 'price': '€ 313', 'scor...","{'name': 'Kyriad Prestige Saint-Malo', 'price'...","{'name': 'B&B HOTEL Bayeux', 'price': '€ 241',...",{'name': 'Les Beaux Volumes - Grand T2 rénové ...,"{'name': 'Grand Hôtel De La Seine', 'price': '...","{'name': 'Ibis Styles Paris Batignolles', 'pri...","{'name': 'Ibis Budget Amiens Centre Gare', 'pr...","{'name': 'Babel Lille Centre', 'price': '€ 254...","{'name': 'Hôtel Restaurant Athena Spa', 'price...","{'name': 'Domaine du Haut-Koenigsbourg', 'pric...","{'name': 'Hôtel Maison Turenne', 'price': '€ 4...",{'name': 'Hotel SPA Restaurant Husseren Collec...,{'name': 'Premiere Classe Besancon Ecole Valen...,"{'name': 'Hotel Le Jacquemart', 'price': '€ 19...","{'name': 'appartement moderne et spacieux, par...","{'name': 'B&B HOTEL Grenoble Centre Verlaine',...","{'name': 'Mama Shelter Lyon', 'price': '€ 276'...","{'name': 'Le 10 18 hôtel restaurant', 'price':...","{'name': 'Hotel La Voile', 'price': '€ 287', '...","{'name': 'Hotel Le Golfe', 'price': '€ 306', '...",{'name': 'MEININGER Marseille Centre la Joliet...,{'name': 'Aparthotel Adagio Access Aix-en-Prov...,"{'name': 'ibis budget Avignon Centre', 'price'...","{'name': 'Boutique Hôtel Entraigues', 'price':...","{'name': 'hotelF1 Nîmes Ouest', 'price': '€ 84...",{'name': 'Hôtel les jardins du canal - piscine...,{'name': 'Oh! Campings - La Brise de Camargue'...,"{'name': 'Les Chênes-lièges d'Ambeille', 'pric...","{'name': 'Tribe Carcassonne', 'price': '€ 286'...","{'name': 'Mercure Ax Les Thermes', 'price': '€...",{'name': 'Eklo Hotels Toulouse Cartoucherie Zé...,"{'name': 'Unisotel Montauban EX F1', 'price': ...",{'name': 'Nemea Appart Hotel Les Hauts de Mila...,"{'name': 'ibis budget Bayonne', 'price': '€ 18...",{'name': 'ibis budget La Rochelle Centre les M...
hotel_2,"{'name': 'Gîtes Les Rives du Mont', 'price': '...","{'name': 'ibis Saint Malo Plage', 'price': '€ ...","{'name': 'Ibis Budget Bayeux', 'price': '€ 177...",{'name': 'All Suites Appart Hôtel - Le Havre C...,"{'name': 'Eaux Spa Rive Droite', 'price': '€ 2...","{'name': 'Mercure Tour Eiffel Grenelle', 'pric...","{'name': 'ibis Styles Amiens Sud', 'price': '€...","{'name': 'Lille City Hotel', 'price': '€ 175',...","{'name': 'Ibis Budget Strasbourg Centre Gare',...","{'name': 'Au pied du Château', 'price': '€ 252...","{'name': 'Novotel Suites Colmar Centre', 'pric...",{'name': 'Résidence Pierre & Vacances Le Clos ...,"{'name': 'B&B HOTEL Besançon Valentin', 'price...","{'name': 'Neoresid - Résidence Clos Morlot', '...","{'name': 'B&B HOTEL Annecy Cran-Gevrier', 'pri...","{'name': 'B&B HOTEL Grenoble Centre Alpexpo', ...",{'name': 'Campanile PRIME Lyon Centre Gare Par...,{'name': 'Camping RCN Les Collines de Castella...,"{'name': 'Camping Clau Mar Jo', 'price': '€ 14...",{'name': 'Les Jardins de Cassis - Parking Grat...,"{'name': 'ibis budget Marseille Vieux Port', '...",{'name': 'B&B HOTEL Aix-en-Provence Pont de l'...,{'name': 'Premiere Classe Avignon Courtine Gar...,"{'name': 'Hôtel Le SAINT-GENIÈS', 'price': '€ ...","{'name': 'ibis budget Nimes Centre Gare', 'pri...","{'name': 'Hotel L'Escale', 'price': '€ 178', '...","{'name': 'Hotel Les Palmiers En Camargue', 'pr...","{'name': 'Chambres Rue de la République', 'pri...","{'name': 'Premiere Classe Carcassonne', 'price...","{'name': 'Hôtel Le Bellevue', 'price': '€ 198'...","{'name': 'Hôtel Riquet', 'price': '€ 155', 'sc...","{'name': 'Premiere Classe Montauban', 'price':...","{'name': 'ibis Styles Biarritz Plage', 'price'...","{'name': 'Hotel Cote Basque', 'price': '€ 267'...",{'name': 'B&B HOTEL La Rochelle Centre 3 étoil...
hotel_3,"{'name': 'Les mouettes', 'price': '€ 273', 'sc...",{'name': 'Studio meublé dans moulin à Saint Ma...,"{'name': 'B&B Nathalie', 'price': '€ 271', 'sc...",{'name': 'Appart'hôtel Odalys City - Le Havre ...,"{'name': 'Hôtel 1er Consul Rouen', 'price': '€...","{'name': 'Résidence du Louvre', 'price': '€ 12...","{'name': 'Holiday Inn Express Amiens by IHG', ...","{'name': 'Hotel De La Treille', 'price': '€ 26...","{'name': 'The People - Strasbourg', 'price': '...",{'name': 'Appartement plain-pied au coeur de l...,"{'name': 'ibis Budget Colmar Centre Gare', 'pr...","{'name': 'L'Ecrin du Rempart', 'price': '€ 233...",{'name': 'ibis budget Besançon Ecole Valentin'...,{'name': 'Aparthotel Adagio Access Dijon Répub...,{'name': 'Premiere Classe Annecy Cran-Gevrier ...,{'name': 'greet Grenoble Centre Gare Accor Hot...,{'name': 'MEININGER Hotel Lyon Centre Berthelo...,"{'name': 'Hôtel Spa L'Ermitage', 'price': '€ 2...","{'name': 'Hostellerie du Cigalou', 'price': '€...","{'name': 'The Originals Boutique, Hôtel Cassit...",{'name': 'ibis Styles Marseille Palais des Con...,"{'name': 'ibis Aix en Provence', 'price': '€ 2...",{'name': 'hotelF1 Avignon Centre Courtine gare...,{'name': 'Logis Hotel Restaurant Uzès Pont du ...,{'name': 'Appart'hôtel Odalys City - Nîmes Arè...,"{'name': 'La Villa Mazarin', 'price': '€ 429',...","{'name': 'Hotel Le Bleu Marine', 'price': '€ 1...","{'name': 'La Frégate', 'price': '€ 287', 'scor...","{'name': 'ibis budget Carcassonne La Cité', 'p...","{'name': 'La Bastide', 'price': '€ 105', 'scor...",{'name': 'Mercure Toulouse Centre Saint-George...,"{'name': 'ibis Montauban', 'price': '€ 140', '...","{'name': 'Premiere Classe Biarritz', 'price': ...","{'name': 'Hôtel Les Genêts Bayonne', 'price': ...",{'name': 'ibis Budget La Rochelle Centre gare'...
hotel_4,"{'name': 'Maison neuve à deux pas du Mont', 'p...","{'name': 'Le Confortable proche Intra-muros, G...","{'name': 'Hotel Reine Mathilde', 'price': '€ 2...","{'name': 'Ibis Budget Le Havre Les Docks', 'pr...","{'name': 'Hotel Morand', 'price': '€ 187', 'sc...",{'name': 'Belleville 1 Bedroom Apartment Near ...,"{'name': 'Première Classe Amiens', 'price': '€...","{'name': 'Montempô Appart'hôtel Lille Gares', ...","{'name': 'City Residence Access Strasbourg', '...","{'name': 'Hotel Elisabeth', 'price': '€ 148', ...","{'name': 'Cit'Hotel Primo Colmar Centre', 'pri...","{'name': 'Résidence Vénus', 'price': '€ 245', ...",{'name': 'Campanile NATURE - Besançon Ouest Ch...,"{'name': 'Hôtel Montchapet Dijon Centre', 'pri...","{'name': 'Auberge de Jeunesse HI Annecy', 'pri...","{'name': 'Campanile Grenoble Centre Gare', 'pr...",{'name': 'Residence Montempo Appart'Hôtel Lyon...,"{'name': 'Auberge des Salles', 'price': '€ 267...","{'name': 'Hotel Restaurant Bellevue', 'price':...","{'name': 'Best Western Plus Hôtel la Rade', 'p...","{'name': 'HOTEL SYLVABELLE', 'price': '€ 235',...",{'name': 'Appart'hôtel Odalys City - Aix en Pr...,"{'name': 'Novotel Avignon Centre', 'price': '€...","{'name': 'RAVISSANT STUDIO', 'price': '€ 184',...","{'name': 'ibis Nîmes Ouest - A9', 'price': '€ ...","{'name': 'Appartement intra-muros', 'price': '...","{'name': 'Le Castelet', 'price': '€ 148', 'sco...","{'name': 'Collioure sur Mer', 'price': '€ 916'...",{'name': 'Hotel du Roi & Spa by SOWELL COLLECT...,"{'name': 'Résidence des 3 Césars', 'price': '€...",{'name': 'Alfred Hotels Toulouse Centre Wilson...,"{'name': 'ibis budget Montauban Les Chaumes', ...","{'name': 'Campanile NATURE - Biarritz', 'price...","{'name': 'Premiere Classe Bayonne', 'price': '...","{'name': 'Auberge de Jeunesse', 'price': '€ 22..."
hotel_5,"{'name': 'Le Petit Gîte du Mont', 'price': '€ ...","{'name': 'Hôtel Cartier', 'price': '€ 452', 's...","{'name': 'Le Bayeusain', 'price': '€ 178', 'sc...","{'name': 'Hilton Garden Inn Le Havre Centre', ...",{'name': 'Ibis Styles Rouen Centre Cathédrale'...,"{'name': 'Le Littré', 'price': '€ 1 156', 'sco...","{'name': 'ibis Styles Amiens Centre', 'price':...",{'name': 'Appart'City Confort Lille - Euralill...,{'name': 'Hotel Strasbourg Montagne Verte & Re...,"{'name': 'Duplex au cœur de l’Alsace', 'price'...","{'name': 'B&B HOTEL Colmar Lumière', 'price': ...","{'name': 'James Vignoble Hôtel, Eguisheim', 'p...","{'name': 'Hôtel Restaurant Spa Le Sauvage', 'p...","{'name': 'Hôtel République', 'price': '€ 158',...","{'name': 'Le Pélican', 'price': '€ 1 055', 'sc...",{'name': 'The Babel Community Hôtel - Grenoble...,{'name': 'Novotel Lyon Centre-Confluence Bord ...,"{'name': 'Hôtel La Bonne Auberge', 'price': '€...","{'name': 'Hôtel Paradis', 'price': '€ 308', 's...","{'name': 'HOTEL DES CALANQUES Port de Cassis',...","{'name': 'Hotel Gambetta', 'price': '€ 123', '...","{'name': 'thecamp hôtel - Aix en Provence', 'p...","{'name': 'Golden Tulip Avignon Le Paradou', 'p...","{'name': 'Appartement des amoureux', 'price': ...","{'name': 'Campanile PRIME - Nîmes Centre', 'pr...",{'name': 'Hotel Saint Louis - Au Coeur des Rem...,"{'name': 'Thalacap Camargue', 'price': '€ 361'...","{'name': 'Le Relais Des Trois Mas', 'price': '...","{'name': 'Le Bastide Cosy', 'price': '€ 126', ...",{'name': 'Vacancéole - Le Domaine de la Vallée...,{'name': 'belle chambre 5 calme élégant proche...,"{'name': 'Hôtel du Commerce', 'price': '€ 180'...",{'name': 'Résidence Pierre & Vacances Premium ...,"{'name': 'Adonis Hotel Bayonne', 'price': '€ 1...","{'name': 'Novotel La Rochelle Centre', 'price'..."
hotel_6,"{'name': 'Escale du Mont', 'price': '€ 364', '...","{'name': 'Résidence Pierre & Vacances Ty Mat',...","{'name': 'Hôtel De Brunville & Spa', 'price': ...","{'name': 'Hotel Spa Le Pasino', 'price': '€ 27...","{'name': 'Hôtel De La Cathédrale', 'price': '€...","{'name': 'Hôtel Botaniste', 'price': '€ 682', ...","{'name': 'Mercure Amiens Cathédrale', 'price':...",{'name': 'Alliance Lille - Couvent Des Minimes...,"{'name': 'ibis Strasbourg Centre Historique', ...",{'name': 'La Cour de Mamama Appartement 4 Clim...,{'name': 'Appart'hôtel Odalys City - Colmar Ce...,{'name': 'Gite Traditionnel au Centre Historiq...,"{'name': 'Temis hôtel Besançon', 'price': '€ 1...","{'name': 'Brit Hotel Dijon Centre Gare', 'pric...","{'name': 'Centre Jean XXIII', 'price': '€ 282'...","{'name': 'Kyriad Grenoble Centre', 'price': '€...","{'name': 'HO36 Hostel Lyon', 'price': '€ 202',...",{'name': 'Camping Rives du Lac de Sainte Croix...,"{'name': 'La Licorne YourHostHelper', 'price':...","{'name': 'T3 vue mer exceptionnelle', 'price':...",{'name': 'Novotel Marseille Centre Prado Vélod...,"{'name': 'L'intimiste', 'price': '€ 179', 'sco...","{'name': 'Hotel Cristol', 'price': '€ 145', 's...",{'name': 'Appartement climatisé avec piscine e...,"{'name': 'Comfort Aparthotel Nimes Centre', 'p...","{'name': 'Cœur de Cité AC clim parking', 'pric...","{'name': 'Hotel Le Méditérranée', 'price': '€ ...","{'name': 'Paul CEZANNE', 'price': '€ 336', 'sc...",{'name': 'Campanile Carcassonne Est - La Cité'...,{'name': 'Résidence Vacancéole Les Chalets d'A...,"{'name': 'Citiz Hotel', 'price': '€ 274', 'sco...","{'name': 'Abbaye des Capucins Spa & Resort', '...","{'name': 'Mercure Président Biarritz Plage', '...","{'name': 'Hôtel Le Bayonne', 'price': '€ 249',...",{'name': 'B&B HOTEL La Rochelle Centre Les Min...
hotel_7,"{'name': 'Horizon du Mont 15 personnes', 'pric...","{'name': 'Le Sunset Malouin', 'price': '€ 245'...","{'name': 'Campanile Bayeux', 'price': '€ 288',...","{'name': 'The Originals Boutique, Hôtel Le Mar...","{'name': 'Eaux Spa', 'price': '€ 202', 'score'...",{'name': 'Wonderful Apartments in the Center o...,"{'name': 'Comfort Hotel Amiens Nord', 'price':...","{'name': 'Eklo Hotels Lille', 'price': '€ 113'...","{'name': 'ibis Strasbourg Centre Les Halles', ...","{'name': 'Hôtel De La Couronne', 'price': '€ 2...","{'name': 'Hotel L'Europe Colmar, BW Signature ...","{'name': 'Le gîte de Ninon et Léon 2 épis', 'p...","{'name': 'hotelF1 Besancon Ouest Micropolis', ...","{'name': 'Hôtel Le Chambellan', 'price': '€ 15...","{'name': 'Ace Hotel Annecy', 'price': '€ 178',...",{'name': 'Residhome Grenoble Caserne De Bonne'...,"{'name': 'Hôtel des Facultés', 'price': '€ 101...","{'name': 'Studi-Hôtel Résidence Plein Voile', ...","{'name': 'Hôtel de la Plage - HDLP', 'price': ...","{'name': 'Le petit cassis', 'price': '€ 277', ...","{'name': 'The People - Marseille', 'price': '€...","{'name': 'ibis budget Aix en Provence', 'price...","{'name': 'Camping du Pont d'Avignon', 'price':...","{'name': 'Appart One Uzès', 'price': '€ 158', ...","{'name': 'B&B HOTEL Nîmes Centre Arènes', 'pri...","{'name': 'Au Cœur des Remparts', 'price': '€ 1...",{'name': 'L'Oustau des Palunettes Concept Adul...,"{'name': 'La roussette', 'price': '€ 243', 'sc...","{'name': 'SOWELL HOTELS Les Chevaliers', 'pric...","{'name': 'Jardin Bleu - Chambres d'hôtes', 'pr...","{'name': 'Residhome Toulouse Occitania', 'pric...","{'name': 'Kyriad Montauban Sud - Albasud', 'pr...","{'name': 'Le Gamaritz', 'price': '€ 438', 'sco...","{'name': 'Hostel20 Bayonne', 'price': '€ 305',...","{'name': 'Mercure La Rochelle Vieux Port', 'pr..."
hotel_8,{'name': 'Ibis Budget Pontorson Baie Du Mont S...,{'name': 'Hotel Kyriad Saint Malo Centre Plage...,{'name': 'Apt duplex ou plain pied tout confor...,{'name': 'Aparthotel Adagio Access Le Havre Le...,"{'name': 'Radisson Blu Hotel, Rouen Centre', '...",{'name': 'Hilton Garden Inn Paris La Villette'...,"{'name': 'Appart'City Confort Amiens Gare', 'p...","{'name': 'Campanile Lille Euralille', 'price':...","{'name': 'Hôtel Arc-en-Ciel', 'price': '€ 102'...","{'name': 'Spacieux duplex 1 à 6 personnes', 'p...",{'name': 'L'Attique de la Taillanderie - Mon G...,"{'name': 'Le Zen', 'price': '€ 354', 'score': ...","{'name': 'Hôtel AKENA Besançon', 'price': '€ 2...","{'name': 'Hôtel de Paris - Dijon Centre Gare',...","{'name': 'Novotel Annecy Centre', 'price': '€ ...","{'name': 'Novotel Grenoble Centre', 'price': '...","{'name': 'Hôtel du Helder', 'price': '€ 163', ...","{'name': 'Les Canyons du Verdon', 'price': '€ ...","{'name': 'Bohème 375', 'price': '€ 408', 'scor...","{'name': 'BOUTIQUE HOSTEL BY Cassis', 'price':...","{'name': 'Ibis Marseille Centre Prefecture', '...",{'name': 'Le Aix Rotonde Mirabeau - Centre Vil...,{'name': 'ibis Avignon Centre Pont De L'Europe...,"{'name': 'Uzès, au cœur du centre médiéval La ...","{'name': 'Novotel Atria Nimes Centre', 'price'...",{'name': 'La Suite du Mas Lauseta - Charme et ...,"{'name': 'Abrivado', 'price': '€ 234', 'score'...",{'name': 'Maison de pêcheurs 50 m de la Plage ...,{'name': 'ibis budget Carcassonne Aéroport - A...,{'name': 'Chambre Bohème - parenthèse cosy à l...,{'name': 'Résidence le Pastel François Verdier...,"{'name': 'La Terrasse Bohème I T3 climatisé, C...","{'name': 'Hôtel Le Windsor Biarritz', 'price':...","{'name': 'OKKO Hotels Bayonne Centre', 'price'...",{'name': 'ibis Styles La Rochelle Centre Vieux...
hotel_9,"{'name': 'Gîtes des Archanges', 'price': '€ 30...","{'name': 'Oceania Saint Malo', 'price': '€ 682...","{'name': 'Les palmiers', 'price': '€ 174', 'sc...","{'name': 'UNISOTEL Le Havre', 'price': '€ 73',...","{'name': 'Holiday Inn Express Rouen by IHG', '...",{'name': 'HotelF1 Paris Saint Ouen Marché Aux ...,"{'name': 'Moxy Amiens', 'price': '€ 183', 'sco...",{'name': 'Vieux Lille - Large modern and funct...,{'name': 'ibis Styles Strasbourg Avenue du Rhi...,{'name': 'Le duplex du Ried à Muttersholtz en ...,"{'name': 'Cosy Home Colmar - Petite Venise', '...","{'name': 'Les trois pierres', 'price': '€ 629'...","{'name': 'B&B HOTEL Besançon Chateaufarine', '...","{'name': 'Le Relax SPA', 'price': '€ 302', 'sc...","{'name': 'Perle Alpine', 'price': '€ 333', 'sc...","{'name': 'RockyPop Grenoble Hotel', 'price': '...",{'name': 'Première Classe Lyon Centre Gare Par...,"{'name': 'Nouvel Hôtel du Commerce', 'price': ...",{'name': 'Villa LEOVI Superbe logement 3 piece...,{'name': 'LES VOLETS ROUGES - Hôtel Cassis - S...,"{'name': 'ibis Marseille Centre Euromed', 'pri...","{'name': 'Radisson Hotel Aix En Provence', 'pr...","{'name': 'ApartHotel Sainte-Marthe', 'price': ...","{'name': 'Patio De Violette', 'price': '€ 269'...",{'name': 'Hôtel Concorde - Centre ville de Nim...,"{'name': 'Chambre cozy spacieuse, intra-muros,...","{'name': 'L Abri-côtier Appartements', 'price'...",{'name': 'Hôtel & Spa Le Madeloc - Collioure C...,"{'name': 'L'Écrin Jacques Ourtal', 'price': '€...","{'name': 'Hôtel Premiere Classe Pamiers', 'pri...",{'name': 'Hotel Mercure Toulouse Centre Compan...,"{'name': 'Brit Hotel Confort Montauban', 'pric...","{'name': 'Hôtel de La Plage', 'price': '€ 524'...","{'name': 'Hotel Loreak', 'price': '€ 258', 'sc...",{'name': 'Appart'City Classic La Rochelle Cent...
hotel_10,{'name': 'ibis Pontorson Baie Du Mont Saint Mi...,"{'name': 'hotelF1 Saint Malo', 'price': '€ 116...","{'name': 'Chambre d´hote En Famille', 'price':...",{'name': 'Premiere Classe Le Havre Centre-LES ...,"{'name': 'Brit Hotel Confort Rouen Centre', 'p...",{'name': 'Courtyard by Marriott Paris Gare de ...,{'name': 'Maison cosy avec 3 chambres et 3 sal...,{'name': 'Holiday Inn Express Lille Centre by ...,{'name': 'ibis Styles Strasbourg Stade de la M...,"{'name': 'A labri du vent', 'price': '€ 146', ...","{'name': 'Logis Hotel Saint-Martin', 'price': ...","{'name': 'Gite du Vignoble', 'price': '€ 221',...",{'name': 'Cosy T2 - Centre historique Besançon...,{'name': 'Holiday Inn Dijon Toison D'or by IHG...,{'name': 'Appartement 3 Pièces PROCHE DU LAC a...,"{'name': 'Le Grand Hôtel Grenoble, BW Premier ...","{'name': 'Hotel de Normandie', 'price': '€ 195...",{'name': 'Provençal Studio with Private Entran...,{'name': 'Eden Rose Grand Hotel BW Premier Col...,{'name': 'Hôtel by Reboul - Boutique Hôtel - P...,{'name': 'Campanile NATURE - Marseille Saint-A...,{'name': 'Élégant T2 - Centre - Clim - Rue d'I...,"{'name': 'ibis Styles Avignon Sud', 'price': '...",{'name': 'La Casita - Studio Confort avec Park...,{'name': 'B&B HOTEL Nîmes Ville Active 3 étoil...,"{'name': 'Hotel Des 4 Vents ""Esprit Camargue"" ...","{'name': 'Les Rizières', 'price': '€ 245', 'sc...","{'name': 'Camping Les Amandiers', 'price': '€ ...","{'name': 'ibis Carcassonne Est la Cité', 'pric...",{'name': 'Résidence Pierre & Vacances Les Troi...,"{'name': 'ibis Toulouse Centre', 'price': '€ 2...","{'name': 'B&B HOTEL Montauban', 'price': '€ 13...","{'name': 'Résidence Biarritz Ocean', 'price': ...","{'name': 'Temporesidence Chateauneuf', 'price'...",{'name': 'Hôtel Kyriad La Rochelle Centre Vill...