In [1]:
import pandas as pd
import numpy as np
import json
import ast
from IPython.display import display, Markdown

In [2]:
# Nettoyage du dataframe et Normalisation de la colonne Hotels pour préparer le dataset final pour l'EDA.

In [3]:
final_df = pd.read_csv("/Users/nicolasbour/Desktop/Projets_IA /Projets_certif/02_kayak/data/tests/final_data.csv")

In [4]:
final_df.head(2)

,city,place_id,lat,lon,base,visibility,dt,timezone,id,name,...,sys.sunrise,sys.sunset,sys.type,sys.id,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,hotels
0,mont saint michel,281361808,48.635954,-1.511460,stations,10000,1788426584,7200,6435453,Huisnes-sur-Mer,...,1788413148,1788461136,NaN,NaN,0,804,Clouds,couvert,04d,"[{'hotel_city': 'Beauvoir', 'name': 'La Villa ..."
1,saint malo,285565834,48.649518,-2.026041,stations,10000,1788426585,7200,2978640,Saint-Malo,...,1788413270,1788461260,1.0,6557.0,0,804,Clouds,couvert,04d,"[{'hotel_city': 'Saint-Malo', 'name': 'Kyriad ..."

In [5]:
# Reconvertir la string en vraie liste de dictionnaires (convertion des strings en objets Python)
final_df["hotels"] = final_df["hotels"].apply(ast.literal_eval)

In [6]:
final_df.head(2)

,city,place_id,lat,lon,base,visibility,dt,timezone,id,name,...,sys.sunrise,sys.sunset,sys.type,sys.id,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,hotels
0,mont saint michel,281361808,48.635954,-1.511460,stations,10000,1788426584,7200,6435453,Huisnes-sur-Mer,...,1788413148,1788461136,NaN,NaN,0,804,Clouds,couvert,04d,"[{'hotel_city': 'Beauvoir', 'name': 'La Villa ..."
1,saint malo,285565834,48.649518,-2.026041,stations,10000,1788426585,7200,2978640,Saint-Malo,...,1788413270,1788461260,1.0,6557.0,0,804,Clouds,couvert,04d,"[{'hotel_city': 'Saint-Malo', 'name': 'Kyriad ..."

In [7]:
# Une ligne par hôtel
final_df = final_df.explode("hotels", ignore_index=True)

In [8]:
final_df.head(2)

,city,place_id,lat,lon,base,visibility,dt,timezone,id,name,...,sys.sunrise,sys.sunset,sys.type,sys.id,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,hotels
0,mont saint michel,281361808,48.635954,-1.51146,stations,10000,1788426584,7200,6435453,Huisnes-sur-Mer,...,1788413148,1788461136,NaN,NaN,0,804,Clouds,couvert,04d,"{'hotel_city': 'Beauvoir', 'name': 'La Villa d..."
1,mont saint michel,281361808,48.635954,-1.51146,stations,10000,1788426584,7200,6435453,Huisnes-sur-Mer,...,1788413148,1788461136,NaN,NaN,0,804,Clouds,couvert,04d,"{'hotel_city': 'Huisnes-sur-Mer', 'name': 'Esc..."

In [9]:
# Transformer chaque dictionnaire hôtel en colonnes
hotel_details = pd.json_normalize(final_df["hotels"])

In [10]:
hotel_details.head(2)

,hotel_city,name,price,score,latitude,longitude
0,Beauvoir,La Villa du Manoir,€ 521,"Avec une note de 9,8 9,8 Exceptionnel 6 expéri...",48.596052,-1.500324
1,Huisnes-sur-Mer,Escale du Mont,€ 364,"Avec une note de 7,5 7,5 Bien 2 expériences vé...",48.621474,-1.447158

In [11]:
hotel_details['name'] = hotel_details['name'].str.split(' - ').str[0] # register hotel label
hotel_details['rate'] = hotel_details['score'].str.extract(r'(?:de\s+)?(\d+(?:,\d+)?)') # extract hotel score  
hotel_details['rate_label'] = hotel_details['score'].str.extract(r'(?:\d+(?:,\d+)?)\s+(?:\d+(?:,\d+)?)\s+([^\d]+?)\s+\d+')[0].str.strip() # extract rate label
hotel_details['experience'] = hotel_details['score'].str.extract(r'(\d+(?:\s+\d+)*)\s+expériences?')[0] # extract number of experiences
hotel_details['hotel_city'] = hotel_details['hotel_city'].str.split(',').str[-1].str.strip() # extract hotel city

In [12]:
hotel_details.head(2)

,hotel_city,name,price,score,latitude,longitude,rate,rate_label,experience
0,Beauvoir,La Villa du Manoir,€ 521,"Avec une note de 9,8 9,8 Exceptionnel 6 expéri...",48.596052,-1.500324,"9,8",Exceptionnel,6
1,Huisnes-sur-Mer,Escale du Mont,€ 364,"Avec une note de 7,5 7,5 Bien 2 expériences vé...",48.621474,-1.447158,"7,5",Bien,2

In [13]:
hotel_details = pd.concat([final_df.drop(columns=["hotels"]), hotel_details], axis=1)

In [14]:
hotel_details.head(2)

,city,place_id,lat,lon,base,visibility,dt,timezone,id,name,...,weather.0.icon,hotel_city,name,price,score,latitude,longitude,rate,rate_label,experience
0,mont saint michel,281361808,48.635954,-1.51146,stations,10000,1788426584,7200,6435453,Huisnes-sur-Mer,...,04d,Beauvoir,La Villa du Manoir,€ 521,"Avec une note de 9,8 9,8 Exceptionnel 6 expéri...",48.596052,-1.500324,"9,8",Exceptionnel,6
1,mont saint michel,281361808,48.635954,-1.51146,stations,10000,1788426584,7200,6435453,Huisnes-sur-Mer,...,04d,Huisnes-sur-Mer,Escale du Mont,€ 364,"Avec une note de 7,5 7,5 Bien 2 expériences vé...",48.621474,-1.447158,"7,5",Bien,2

!!! Attention !!! il y a un doublon avec le label name : 
    - openweathermap : name => nom de la ville de la station
        "name" =>> "station_name"
    - booking : name => nom de l'hôtel
        "name" =>> "hotel_name"

sys.type = 4 # => info interne à openweathermap obsolète, on peut la supprimer
sys.id = 4 # => info interne à openweathermap obsolète, on peut la supprimer

In [15]:
# Openweathermap name : 
columns = list(hotel_details.columns)
columns[9] = "station_name"
hotel_details.columns = columns

In [16]:
# Hotel name : 
hotel_details.rename(columns={"name": "hotel_name"}, inplace=True)

In [17]:
hotel_details.head(2)

,city,place_id,lat,lon,base,visibility,dt,timezone,id,station_name,...,weather.0.icon,hotel_city,hotel_name,price,score,latitude,longitude,rate,rate_label,experience
0,mont saint michel,281361808,48.635954,-1.51146,stations,10000,1788426584,7200,6435453,Huisnes-sur-Mer,...,04d,Beauvoir,La Villa du Manoir,€ 521,"Avec une note de 9,8 9,8 Exceptionnel 6 expéri...",48.596052,-1.500324,"9,8",Exceptionnel,6
1,mont saint michel,281361808,48.635954,-1.51146,stations,10000,1788426584,7200,6435453,Huisnes-sur-Mer,...,04d,Huisnes-sur-Mer,Escale du Mont,€ 364,"Avec une note de 7,5 7,5 Bien 2 expériences vé...",48.621474,-1.447158,"7,5",Bien,2

In [18]:
hotel_details = hotel_details.drop(columns=["score", "sys.type", "sys.id", "sys.country", "coord.lon", "coord.lat", "cod", "base", "station_name", "id", "timezone", "place_id"])

In [19]:
pd.set_option('display.max_columns', None)  # Afficher toutes les colonnes
hotel_details.head()

,city,lat,lon,visibility,dt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,wind.gust,clouds.all,sys.sunrise,sys.sunset,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,hotel_city,hotel_name,price,latitude,longitude,rate,rate_label,experience
0,mont saint michel,48.635954,-1.51146,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.6,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Beauvoir,La Villa du Manoir,€ 521,48.596052,-1.500324,"9,8",Exceptionnel,6
1,mont saint michel,48.635954,-1.51146,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.6,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Huisnes-sur-Mer,Escale du Mont,€ 364,48.621474,-1.447158,"7,5",Bien,2
2,mont saint michel,48.635954,-1.51146,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.6,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Huisnes-sur-Mer,Horizon du Mont 15 personnes,€ 1 140,48.619514,-1.459112,"9,7",Exceptionnel,10
3,mont saint michel,48.635954,-1.51146,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.6,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Beauvoir,Ermitage,€ 1 954,48.594490,-1.511429,"8,7",Superbe,152
4,mont saint michel,48.635954,-1.51146,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.6,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Beauvoir,Le Petit Gîte du Mont,€ 440,48.597734,-1.511773,"8,9",Superbe,55

In [20]:
hotel_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 875 entries, 0 to 874
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   city                   875 non-null    object
 1   lat                    875 non-null    float64
 2   lon                    875 non-null    float64
 3   visibility             875 non-null    int64
 4   dt                     875 non-null    int64
 5   main.temp              875 non-null    float64
 6   main.feels_like        875 non-null    float64
 7   main.temp_min          875 non-null    float64
 8   main.temp_max          875 non-null    float64
 9   main.pressure          875 non-null    int64
 10  main.humidity          875 non-null    int64
 11  main.sea_level         875 non-null    int64
 12  main.grnd_level        875 non-null    int64
 13  wind.speed             875 non-null    float64
 14  wind.deg               875 non-null    int64
 15  wind.gust              400 non-null    float64
 16  clouds.all             875 non-null    int64
 17  sys.sunrise            875 non-null    int64
 18  sys.sunset             875 non-null    int64
 19  rain.1h                875 non-null    int64
 20  weather.0.id           875 non-null    int64
 21  weather.0.main         875 non-null    object
 22  weather.0.description  875 non-null    object
 23  weather.0.icon         875 non-null    object
 24  hotel_city             875 non-null    object
 25  hotel_name             875 non-null    object
 26  price                  875 non-null    object
 27  latitude               875 non-null    float64
 28  longitude              875 non-null    float64
 29  rate                   865 non-null    object
 30  rate_label             865 non-null    object
 31  experience             865 non-null    object
dtypes: float64(10), int64(12), object(10)
memory usage: 218.9+ KB

In [21]:
hotel_details.isna().sum()

city                       0
lat                        0
lon                        0
visibility                 0
dt                         0
main.temp                  0
main.feels_like            0
main.temp_min              0
main.temp_max              0
main.pressure              0
main.humidity              0
main.sea_level             0
main.grnd_level            0
wind.speed                 0
wind.deg                   0
wind.gust                475
clouds.all                 0
sys.sunrise                0
sys.sunset                 0
rain.1h                    0
weather.0.id               0
weather.0.main             0
weather.0.description      0
weather.0.icon             0
hotel_city                 0
hotel_name                 0
price                      0
latitude                   0
longitude                  0
rate                      10
rate_label                10
experience                10
dtype: int64

In [22]:
print(hotel_details[hotel_details["rate"].isna()])

                city        lat       lon  visibility          dt  main.temp  \
81          le havre  49.493898  0.107973       10000  1788426587      19.61
159           amiens  49.894171  2.295695       10000  1788426591      20.67
294        eguisheim  48.044797  7.307962       10000  1788426596      23.92
326            dijon  47.321581  5.041470       10000  1788426302      23.80
526  aix en provence  43.529842  5.447474       10000  1788426607      25.52
619            nimes  43.837425  4.360069       10000  1788426303      28.22
700      carcassonne  43.213036  2.349107       10000  1788426615      25.15
702      carcassonne  43.213036  2.349107       10000  1788426615      25.15
755         toulouse  43.604464  1.444243       10000  1788426576      23.97
822         biarritz  43.471144 -1.552728       10000  1788426619      22.00

     main.feels_like  main.temp_min  main.temp_max  main.pressure  \
81             20.03          19.51          21.68           1021
159            20.88          20.67          20.67           1020
294            23.70          23.32          23.94           1023
326            22.81          23.80          23.80           1024
526            25.43          25.07          25.78           1019
619            27.47          28.22          28.22           1021
700            25.10          23.49          25.94           1024
702            25.10          23.49          25.94           1024
755            23.73          23.97          23.97           1024
822            22.03          20.55          22.00           1024

     main.humidity  main.sea_level  main.grnd_level  wind.speed  wind.deg  \
81              92            1021             1019        5.66       230
159             80            1020             1010        5.88       242
294             51            1023              979        4.30       166
326             22            1024              986        2.06       150
526             50            1019              987        1.55         9
619             34            1021             1012        6.69       350
700             53            1024              994        5.66       270
702             53            1024              994        5.66       270
755             50            1024             1003        1.03         0
822             68            1024             1018        2.57        80

     wind.gust  clouds.all  sys.sunrise  sys.sunset  rain.1h  weather.0.id  \
81         NaN         100   1788412688  1788460818        0           804
159      10.47         100   1788412129  1788460327        0           804
294       5.80          22   1788411076  1788458975        0           801
326        NaN          12   1788411676  1788459462        0           801
526       2.19          16   1788411848  1788459096        0           801
619        NaN          10   1788412088  1788459377        0           800
700        NaN           6   1788412613  1788459818        0           800
702        NaN           6   1788412613  1788459818        0           800
755        NaN          37   1788412804  1788460061        0           802
822        NaN           8   1788413533  1788460770        0           800

    weather.0.main  weather.0.description weather.0.icon  \
81          Clouds                couvert            04d
159         Clouds                couvert            04d
294         Clouds            peu nuageux            02d
326         Clouds            peu nuageux            02d
526         Clouds            peu nuageux            02d
619          Clear            ciel dégagé            01d
700          Clear            ciel dégagé            01d
702          Clear            ciel dégagé            01d
755         Clouds  partiellement nuageux            03d
822          Clear            ciel dégagé            01d

                  hotel_city  \
81                  Le Havre
159                   Amiens
294  Herrlisheim-près-Colmar
326                    Dijon
526          Aix-en-Provence
619                    Nîmes
700              Carcassonne
702              Carcassonne
755                 Toulouse
822                 Biarritz

                                            hotel_name  price   latitude  \
81                                            Dalikyda  € 293  49.490236
159                            Appartement cosy Amiens  € 158  49.896188
294                       Appartement cosy avec jardin  € 219  48.016137
326                                     Les Toits d'Or  € 149  47.321982
526                       Charming design ꕥ Aix Center  € 208  43.527809
619                        Studio Pop Art Nîmes Centre  € 140  43.839642
700                                    L'oasis urbaine  € 129  43.214892
702  3-Bedroom House with Garden Near the Cité de C...  € 204  43.209839
755                                 La Fabrik Matabiau  € 212  43.610823
822                                    Studio Victoria  € 422  43.481128

     longitude rate rate_label experience
81    0.099071  NaN        NaN        NaN
159   2.292838  NaN        NaN        NaN
294   7.321405  NaN        NaN        NaN
326   5.036638  NaN        NaN        NaN
526   5.453575  NaN        NaN        NaN
619   4.356902  NaN        NaN        NaN
700   2.349706  NaN        NaN        NaN
702   2.374277  NaN        NaN        NaN
755   1.447504  NaN        NaN        NaN
822  -1.556587  NaN        NaN        NaN

In [23]:
percentage_null = (hotel_details["rate"].isna().sum() / len(hotel_details))*100

In [24]:
display(Markdown(f"""
**Hypothèse à valider :** Les valeurs nulles semblent correspondre à des hôtels 
qui n'ont pas de note ou d'avis laissés sur le site Booking. 
Cela représente {percentage_null:.2f}% des hôtels de la base de données. 
Il est donc possible de supprimer ces lignes sans perte d'information significative."""))

**Hypothèse à valider :** Les valeurs nulles semblent correspondre à des hôtels
qui n'ont pas de note ou d'avis laissés sur le site Booking.
Cela représente 1.14% des hôtels de la base de données.
Il est donc possible de supprimer ces lignes sans perte d'information significative.

In [25]:
hotel_details.to_csv("/Users/nicolasbour/Desktop/Projets_IA /Projets_certif/02_kayak/data/final_data_cleaned.csv", index=False)