Lets focus on basic data analysis and the cities locations.

# 1. Call api

## Call api nominatim

In [1]:
import requests

nominatim_url = "https://nominatim.openstreetmap.org/search"
cities_info = f"{nominatim_url}/cities_location.json"

params = {
    "country": "France",
    "city": "Bayeux",
    "format": "geocodejson"
}

headers = {"User-Agent": "projet_etude_dataviz (lnmourez@gmail.com)"}

### Fetch cities information

In [2]:
import json

nominatim_response = requests.get(nominatim_url, params=params, headers=headers) # call api

print(nominatim_response) # call api status code 
print(nominatim_response.content) # take a look at the data that was recieved along with this response
#print(json.dumps(response.json(), indent=2)) # add json indentation

<Response [200]>
b'{"type":"FeatureCollection","geocoding":{"version":"0.1.0","attribution":"Data \xc2\xa9 OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright","licence":"ODbL","query":"Bayeux, France"},"features":[{"type":"Feature","properties":{"geocoding":{"place_id":280655053,"osm_type":"relation","osm_id":145776,"osm_key":"boundary","osm_value":"administrative","type":"city","label":"Bayeux, Calvados, Normandie, France m\xc3\xa9tropolitaine, 14400, France","name":"Bayeux"}},"geometry":{"type": "Point","coordinates": [-0.7024738, 49.2764624]}},{"type":"Feature","properties":{"geocoding":{"place_id":283440891,"osm_type":"relation","osm_id":1656892,"osm_key":"boundary","osm_value":"administrative","type":"city","label":"Bayeux, Calvados, Normandie, France m\xc3\xa9tropolitaine, France","name":"Bayeux"}},"geometry":{"type": "Point","coordinates": [-0.791677, 49.2455634]}}]}'

In [3]:
type(nominatim_response.json())  # display type

dict

#### Fetch one city location

In [4]:
feature = nominatim_response.json()["features"][0] # declare the first result
city = feature["properties"]["geocoding"]["name"]
place_id = feature["properties"]["geocoding"]["place_id"]
lat = feature["geometry"]["coordinates"][1]
lon = feature["geometry"]["coordinates"][0]
print(f"{city}, {place_id},{lon}, {lat}")

Bayeux, 280655053,-0.7024738, 49.2764624

#### Fetch the cities list location

In the provided cities list, we observe that :
1) Ariège is a department. 
2) Gorges du Verdon and Chateau du haut Koenigsbourg are tourist sites

It could be interesting to search some nearby locations. 

Ariège :
- https://www.guide-toulouse-pyrenees.com/fr/experiences/culturelle/article-les-plus-beaux-villages-de-l-ariege-106.html
- https://www.sites-touristiques-ariege.fr/informations-pratiques/visiter-lariege/

Bédeilhac-et-Aynat
Camon
Carla-Bayle
Foix
Le Mas-d’Azil
Mirepoix
Montségur
Niaux
Saint-Lizier
Saint-Martin-d’Oydes
Tarascon-sur-Ariège

Gorges du Verdon : 
https://lesgorgesduverdon.fr/a-visiter/

Barjols
Castellane
Cotignac
Moustiers-Sainte-Marie
Sainte-Croix-du-Verdon
Sillans-la-Cascade
Valensole

Chateau du haut Koenigsbourg (ORSCHWILLER)
https://www.haut-koenigsbourg.fr/infos-pratiques/

In [34]:
import time

cities_info = []
cities = ["Aigues Mortes",
"Aix en Provence",
"Amiens",
"Annecy",
"Avignon",
"Barjols",
"Bayeux",
"Bayonne",
"Besancon",
"Biarritz",
"Bormes les Mimosas",
"Bédeilhac-et-Aynat",
"Camon",
"Carcassonne",
"Carla-Bayle",
"Cassis",
"Castellane",
"Collioure",
"Colmar",
"Cotignac",
"Dijon",
"Eguisheim",
"Foix",
"Grenoble",
"La Rochelle",
"Le Havre",
"Le Mas-d’Azil",
"Lille",
"Lyon",
"Marseille",
"Mirepoix",
"Mont Saint Michel",
"Montauban",
"Montségur",
"Moustiers-Sainte-Marie",
"Niaux",
"Nimes",
"Orschwiller",
"Paris",
"Rouen",
"Saint-Lizier",
"Saint-Martin-d’Oydes",
"Sainte-Croix-du-Verdon",
"Saintes Maries de la mer",
"Sillans-la-Cascade",
"St Malo",
"Strasbourg",
"Tarascon-sur-Ariège",
"Toulouse",
"Uzes",
"Valensole"
]

for city in cities:
    try:
        nominatim_response = requests.get(
            nominatim_url, 
            params={"country": "France",
            "city": city,
            "format": "geocodejson"
            },
            headers=headers)
        # print(f"{city}: {response.status_code}")  # vérifiez le code HTTP


        feature = nominatim_response.json()["features"][0]
        cities_info.append({"city" : feature["properties"]["geocoding"]["name"],
        "place_id" : feature["properties"]["geocoding"]["place_id"],
        "lat" : feature["geometry"]["coordinates"][1],
        "lon" : feature["geometry"]["coordinates"][0]
        })
    except (IndexError, KeyError, requests.exceptions.RequestException):
        print(f"Execution with errors for {city} : {nominatim_response.status_code}")
      
    time.sleep(2)

In [35]:
import json
print(len(cities_info))
print(cities_info)
#print(json.dumps(cities_location, indent=2))

51
[{'city': 'Aigues-Mortes', 'place_id': 83174366, 'lat': 43.5661521, 'lon': 4.19154}, {'city': 'Aix-en-Provence', 'place_id': 82709709, 'lat': 43.5298424, 'lon': 5.4474738}, {'city': 'Amiens', 'place_id': 99360340, 'lat': 49.8941708, 'lon': 2.2956951}, {'city': 'Annecy', 'place_id': 88514330, 'lat': 45.8992348, 'lon': 6.1288847}, {'city': 'Avignon', 'place_id': 82414561, 'lat': 43.9492493, 'lon': 4.8059012}, {'city': 'Barjols', 'place_id': 82795376, 'lat': 43.558133, 'lon': 6.0056803}, {'city': 'Bayeux', 'place_id': 283731646, 'lat': 49.2764624, 'lon': -0.7024738}, {'city': 'Bayonne', 'place_id': 291532516, 'lat': 43.4945144, 'lon': -1.4736657}, {'city': 'Besançon', 'place_id': 92553994, 'lat': 47.2380222, 'lon': 6.0243622}, {'city': 'Biarritz', 'place_id': 287222151, 'lat': 43.4832523, 'lon': -1.5592776}, {'city': 'Bormes-les-Mimosas', 'place_id': 81776233, 'lat': 43.1506968, 'lon': 6.3419285}, {'city': 'Bédeilhac-et-Aynat', 'place_id': 84249524, 'lat': 42.8816132, 'lon': 1.5674969}, {'city': 'Camon', 'place_id': 99997574, 'lat': 49.8874246, 'lon': 2.3446546}, {'city': 'Carcassonne', 'place_id': 84898345, 'lat': 43.2130358, 'lon': 2.3491069}, {'city': 'Le Carla-Bayle', 'place_id': 86409456, 'lat': 43.1500386, 'lon': 1.3936011}, {'city': 'Cassis', 'place_id': 83023230, 'lat': 43.2140359, 'lon': 5.5396318}, {'city': 'Castellane', 'place_id': 83230701, 'lat': 43.846459, 'lon': 6.5134463}, {'city': 'Collioure', 'place_id': 84280626, 'lat': 42.52505, 'lon': 3.0831554}, {'city': 'Colmar', 'place_id': 122171492, 'lat': 48.0777517, 'lon': 7.3579641}, {'city': 'Cotignac', 'place_id': 89393394, 'lat': 43.5280531, 'lon': 6.1502672}, {'city': 'Dijon', 'place_id': 93940430, 'lat': 47.3215806, 'lon': 5.0414701}, {'city': 'Eguisheim', 'place_id': 121333649, 'lat': 48.0447968, 'lon': 7.3079618}, {'city': 'Foix', 'place_id': 83990922, 'lat': 42.9638998, 'lon': 1.6053807}, {'city': 'Grenoble', 'place_id': 89646215, 'lat': 45.1875602, 'lon': 5.7357819}, {'city': 'La Rochelle', 'place_id': 289326024, 'lat': 46.159732, 'lon': -1.1515951}, {'city': 'Le Havre', 'place_id': 100021883, 'lat': 49.4938975, 'lon': 0.1079732}, {'city': "Le Mas-d'Azil", 'place_id': 85533908, 'lat': 43.0794579, 'lon': 1.3613197}, {'city': 'Lille', 'place_id': 101870667, 'lat': 50.6365654, 'lon': 3.0635282}, {'city': 'Lyon', 'place_id': 90160981, 'lat': 45.7578137, 'lon': 4.8320114}, {'city': 'Marseille', 'place_id': 83042786, 'lat': 43.2963986, 'lon': 5.3777888}, {'city': 'Mirepoix', 'place_id': 85916870, 'lat': 43.7458333, 'lon': 0.6719444}, {'city': 'Mont Saint-Michel', 'place_id': 119406788, 'lat': 48.6906803, 'lon': 5.8826485}, {'city': 'Montauban', 'place_id': 85485907, 'lat': 44.0175835, 'lon': 1.3549991}, {'city': 'Montségur', 'place_id': 84371924, 'lat': 42.8707548, 'lon': 1.8337452}, {'city': 'Moustiers-Sainte-Marie', 'place_id': 82649540, 'lat': 43.8460089, 'lon': 6.2217604}, {'city': 'Niaux', 'place_id': 84684813, 'lat': 42.8093089, 'lon': 1.5911122}, {'city': 'Nîmes', 'place_id': 82204290, 'lat': 43.8374249, 'lon': 4.3600687}, {'city': 'Orschwiller', 'place_id': 121122082, 'lat': 48.2422436, 'lon': 7.3799809}, {'city': 'Paris', 'place_id': 97620444, 'lat': 48.8534951, 'lon': 2.3483915}, {'city': 'Rouen', 'place_id': 99438300, 'lat': 49.4404591, 'lon': 1.0939658}, {'city': 'Saint-Lizier', 'place_id': 84167605, 'lat': 43.0025191, 'lon': 1.1354926}, {'city': "Saint-Martin-d'Oydes", 'place_id': 85314031, 'lat': 43.169734, 'lon': 1.4955303}, {'city': 'Sainte-Croix-du-Verdon', 'place_id': 82903247, 'lat': 43.7589451, 'lon': 6.1518294}, {'city': 'Saintes-Maries-de-la-Mer', 'place_id': 82819543, 'lat': 43.4515922, 'lon': 4.4277202}, {'city': 'Sillans-la-Cascade', 'place_id': 81887886, 'lat': 43.5673969, 'lon': 6.1795387}, {'city': 'Saint-Malo', 'place_id': 284423924, 'lat': 48.649518, 'lon': -2.0260409}, {'city': 'Strasbourg', 'place_id': 120878363, 'lat': 48.584614, 'lon': 7.7507127}, {'city': 'Tarascon-sur-Ariège', 'place_id': 84404745, 'lat': 42.8492109, 'lon': 1.6043495}, {'city': 'Toulouse', 'place_id': 85889491, 'lat': 43.6044638, 'lon': 1.4442433}, {'city': 'Uzès', 'place_id': 87817750, 'lat': 44.0121279, 'lon': 4.4196718}, {'city': 'Valensole', 'place_id': 82836030, 'lat': 43.8379283, 'lon': 5.9839867}]

## 2. Call api openweathermap

In [7]:
from dotenv import load_dotenv
import os
# V2.5 https://api.openweathermap.org/data/2.5/weather
# V4.0 https://api.openweathermap.org/data/4.0/onecall/current

weather_url = "https://api.openweathermap.org/data/2.5/weather"
params = {
    "lat":"48.635954",
    "lon":"-1.511460",
    "units":"metric",
    "appid": os.getenv("API_KEY")
}

### Fetch weather information

In [8]:
weather_response = requests.get(weather_url, params=params) # call api
weather_json = weather_response.json()

print(weather_response, weather_json)

<Response [200]> {'coord': {'lon': -1.5115, 'lat': 48.636}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'base': 'stations', 'main': {'temp': 19.46, 'feels_like': 19.13, 'temp_min': 19.46, 'temp_max': 19.46, 'pressure': 1008, 'humidity': 64, 'sea_level': 1008, 'grnd_level': 1003}, 'visibility': 10000, 'wind': {'speed': 1.57, 'deg': 111, 'gust': 4.07}, 'clouds': {'all': 98}, 'dt': 1787602833, 'sys': {'country': 'FR', 'sunrise': 1787548306, 'sunset': 1787598335}, 'timezone': 7200, 'id': 6435453, 'name': 'Huisnes-sur-Mer', 'cod': 200}

In [37]:
weather_info = []
for city in cities_info:
    try:
        params = {
            "lat": city["lat"], 
            "lon": city["lon"], 
            "units": "metric", 
            "appid": "65a6acbff3eb4de13c8e4cf52a30ccf2"
            }
        weather_response = requests.get(weather_url, params=params)
        weather = weather_response.json()
        weather['city'] = city['city'] #weather_info.append({"city": city["city"], "weather": weather_response.json()})
        weather_info.append(weather)
    except (IndexError, KeyError, requests.exceptions.RequestException):
        print(f"Execution with errors for {city} : {weather_response.status_code}")
    time.sleep(2)

In [10]:
print(cities_info[0].keys())  # display keys

dict_keys(['city', 'place_id', 'lat', 'lon'])

In [11]:
print(weather_info[0].keys())  # display keys

dict_keys(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'clouds', 'dt', 'sys', 'timezone', 'id', 'name', 'cod', 'city'])

In [12]:
# print(json.dumps(weather_info, indent=2))

In [13]:
type(weather_info)

list

In [14]:
weather_info

[{'coord': {'lon': 4.1915, 'lat': 43.5662},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'base': 'stations',
  'main': {'temp': 18.98,
   'feels_like': 19.39,
   'temp_min': 18.56,
   'temp_max': 18.98,
   'pressure': 1012,
   'humidity': 94,
   'sea_level': 1012,
   'grnd_level': 1012},
  'visibility': 10000,
  'wind': {'speed': 1.54, 'deg': 20},
  'clouds': {'all': 37},
  'dt': 1787602834,
  'sys': {'type': 1,
   'id': 6518,
   'country': 'FR',
   'sunrise': 1787547477,
   'sunset': 1787596427},
  'timezone': 7200,
  'id': 3038493,
  'name': 'Aigues-Mortes',
  'cod': 200,
  'city': 'Aigues-Mortes'},
 {'coord': {'lon': 5.4541, 'lat': 43.5264},
  'weather': [{'id': 501,
    'main': 'Rain',
    'description': 'moderate rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 17.74,
   'feels_like': 17.92,
   'temp_min': 16.1,
   'temp_max': 17.74,
   'pressure': 1012,
   'humidity': 90,
   'sea_level': 1012,
   'grnd_level': 981},
  'visibility': 10000,
  'wind': {'speed': 4.71, 'deg': 189, 'gust': 10.5},
  'rain': {'1h': 3.65},
  'clouds': {'all': 57},
  'dt': 1787602810,
  'sys': {'type': 1,
   'id': 6512,
   'country': 'FR',
   'sunrise': 1787547177,
   'sunset': 1787596121},
  'timezone': 7200,
  'id': 3038354,
  'name': 'Aix-en-Provence',
  'cod': 200,
  'city': 'Aix-en-Provence'},
 {'coord': {'lon': 2.2957, 'lat': 49.8942},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'base': 'stations',
  'main': {'temp': 19.78,
   'feels_like': 19.3,
   'temp_min': 19.78,
   'temp_max': 19.78,
   'pressure': 1012,
   'humidity': 57,
   'sea_level': 1012,
   'grnd_level': 1001},
  'visibility': 10000,
  'wind': {'speed': 5.15, 'deg': 60, 'gust': 12.27},
  'clouds': {'all': 44},
  'dt': 1787602308,
  'sys': {'country': 'FR', 'sunrise': 1787547239, 'sunset': 1787597574},
  'timezone': 7200,
  'id': 3037854,
  'name': 'Amiens',
  'cod': 200,
  'city': 'Amiens'},
 {'coord': {'lon': 6.1289, 'lat': 45.8992},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'base': 'stations',
  'main': {'temp': 20.08,
   'feels_like': 20.15,
   'temp_min': 20.08,
   'temp_max': 20.08,
   'pressure': 1012,
   'humidity': 77,
   'sea_level': 1012,
   'grnd_level': 927},
  'visibility': 10000,
  'wind': {'speed': 5.66, 'deg': 300},
  'clouds': {'all': 100},
  'dt': 1787602842,
  'sys': {'type': 1,
   'id': 6500,
   'country': 'FR',
   'sunrise': 1787546776,
   'sunset': 1787596198},
  'timezone': 7200,
  'id': 3037543,
  'name': 'Annecy',
  'cod': 200,
  'city': 'Annecy'},
 {'coord': {'lon': 4.8059, 'lat': 43.9492},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 19.05,
   'feels_like': 19.47,
   'temp_min': 18.21,
   'temp_max': 19.05,
   'pressure': 1012,
   'humidity': 94,
   'sea_level': 1012,
   'grnd_level': 1006},
  'visibility': 1127,
  'wind': {'speed': 3.09, 'deg': 330},
  'rain': {'1h': 0.71},
  'clouds': {'all': 72},
  'dt': 1787602844,
  'sys': {'type': 1,
   'id': 6520,
   'country': 'FR',
   'sunrise': 1787547292,
   'sunset': 1787596317},
  'timezone': 7200,
  'id': 3035681,
  'name': 'Avignon',
  'cod': 200,
  'city': 'Avignon'},
 {'coord': {'lon': 6.0075, 'lat': 43.5581},
  'weather': [{'id': 502,
    'main': 'Rain',
    'description': 'heavy intensity rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 18.05,
   'feels_like': 18.23,
   'temp_min': 18.05,
   'temp_max': 18.05,
   'pressure': 1015,
   'humidity': 89,
   'sea_level': 1015,
   'grnd_level': 970},
  'visibility': 10000,
  'wind': {'speed': 1.86, 'deg': 161, 'gust': 1.83},
  'rain': {'1h': 8.42},
  'clouds': {'all': 73},
  'dt': 1787602421,
  'sys': {'type': 2,
   'id': 2006427,
   'country': 'FR',
   'sunrise': 1787547041,
   'sunset': 1787595991},
  'timezone': 7200,
  'id': 3034918,
  'name': 'Barjols',
  'cod': 200,
  'city': 'Barjols'},
 {'coord': {'lon': -0.7025, 'lat': 49.2765},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'base': 'stations',
  'main': {'temp': 21.14,
   'feels_like': 20.75,
   'temp_min': 21.14,
   'temp_max': 21.14,
   'pressure': 1010,
   'humidity': 55,
   'sea_level': 1010,
   'grnd_level': 1004},
  'visibility': 10000,
  'wind': {'speed': 8.34, 'deg': 63, 'gust': 14.52},
  'clouds': {'all': 71},
  'dt': 1787602850,
  'sys': {'type': 1,
   'id': 6569,
   'country': 'FR',
   'sunrise': 1787548035,
   'sunset': 1787598217},
  'timezone': 7200,
  'id': 3034483,
  'name': 'Bayeux',
  'cod': 200,
  'city': 'Bayeux'},
 {'coord': {'lon': -1.4737, 'lat': 43.4945},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'base': 'stations',
  'main': {'temp': 24.42,
   'feels_like': 24.82,
   'temp_min': 23.97,
   'temp_max': 24.42,
   'pressure': 1009,
   'humidity': 73,
   'sea_level': 1009,
   'grnd_level': 1005},
  'visibility': 10000,
  'wind': {'speed': 1.54, 'deg': 0},
  'clouds': {'all': 18},
  'dt': 1787602853,
  'sys': {'type': 1,
   'id': 6478,
   'country': 'FR',
   'sunrise': 1787548844,
   'sunset': 1787597778},
  'timezone': 7200,
  'id': 3034475,
  'name': 'Bayonne',
  'cod': 200,
  'city': 'Bayonne'},
 {'coord': {'lon': 6.0241, 'lat': 47.2378},
  'weather': [{'id': 502,
    'main': 'Rain',
    'description': 'heavy intensity rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 19.68,
   'feels_like': 19.79,
   'temp_min': 18.33,
   'temp_max': 19.68,
   'pressure': 1011,
   'humidity': 80,
   'sea_level': 1011,
   'grnd_level': 971},
  'visibility': 10000,
  'wind': {'speed': 2.63, 'deg': 116, 'gust': 7.05},
  'rain': {'1h': 14.14},
  'clouds': {'all': 99},
  'dt': 1787602376,
  'sys': {'type': 2,
   'id': 2003958,
   'country': 'FR',
   'sunrise': 1787546656,
   'sunset': 1787596368},
  'timezone': 7200,
  'id': 3033123,
  'name': 'Besançon',
  'cod': 200,
  'city': 'Besançon'},
 {'coord': {'lon': -1.5586, 'lat': 43.4832},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'base': 'stations',
  'main': {'temp': 24.3,
   'feels_like': 24.69,
   'temp_min': 24.3,
   'temp_max': 24.85,
   'pressure': 1009,
   'humidity': 73,
   'sea_level': 1009,
   'grnd_level': 1006},
  'visibility': 10000,
  'wind': {'speed': 1.54, 'deg': 0},
  'clouds': {'all': 15},
  'dt': 1787602310,
  'sys': {'type': 1,
   'id': 6478,
   'country': 'FR',
   'sunrise': 1787548866,
   'sunset': 1787597798},
  'timezone': 7200,
  'id': 3032797,
  'name': 'Biarritz',
  'cod': 200,
  'city': 'Biarritz'},
 {'coord': {'lon': 6.3419, 'lat': 43.1507},
  'weather': [{'id': 504,
    'main': 'Rain',
    'description': 'extreme rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 19.42,
   'feels_like': 19.69,
   'temp_min': 18.26,
   'temp_max': 19.97,
   'pressure': 1014,
   'humidity': 87,
   'sea_level': 1014,
   'grnd_level': 997},
  'visibility': 10000,
  'wind': {'speed': 9.77, 'deg': 310, 'gust': 16.98},
  'rain': {'1h': 162.02},
  'clouds': {'all': 10},
  'dt': 1787602861,
  'sys': {'type': 2,
   'id': 2016551,
   'country': 'FR',
   'sunrise': 1787547000,
   'sunset': 1787595872},
  'timezone': 7200,
  'id': 3031532,
  'name': 'Bormes-les-Mimosas',
  'cod': 200,
  'city': 'Bormes-les-Mimosas'},
 {'coord': {'lon': 1.5675, 'lat': 42.8816},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 18.18,
   'feels_like': 18.17,
   'temp_min': 18.18,
   'temp_max': 18.18,
   'pressure': 1013,
   'humidity': 81,
   'sea_level': 1013,
   'grnd_level': 884},
  'visibility': 10000,
  'wind': {'speed': 3.68, 'deg': 190, 'gust': 4},
  'clouds': {'all': 4},
  'dt': 1787602863,
  'sys': {'type': 2,
   'id': 20300,
   'country': 'FR',
   'sunrise': 1787548172,
   'sunset': 1787596991},
  'timezone': 7200,
  'id': 6426331,
  'name': 'Tarascon-sur-Ariège',
  'cod': 200,
  'city': 'Bédeilhac-et-Aynat'},
 {'coord': {'lon': 2.3447, 'lat': 49.8874},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'base': 'stations',
  'main': {'temp': 18.51,
   'feels_like': 17.93,
   'temp_min': 18.51,
   'temp_max': 18.51,
   'pressure': 1012,
   'humidity': 58,
   'sea_level': 1012,
   'grnd_level': 1001},
  'visibility': 10000,
  'wind': {'speed': 5.19, 'deg': 59, 'gust': 12.27},
  'clouds': {'all': 44},
  'dt': 1787602866,
  'sys': {'type': 1,
   'id': 6446,
   'country': 'FR',
   'sunrise': 1787547228,
   'sunset': 1787597562},
  'timezone': 7200,
  'id': 3029003,
  'name': 'Camon',
  'cod': 200,
  'city': 'Camon'},
 {'coord': {'lon': 2.3491, 'lat': 43.213},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'base': 'stations',
  'main': {'temp': 18.19,
   'feels_like': 18.47,
   'temp_min': 18.06,
   'temp_max': 19.27,
   'pressure': 1011,
   'humidity': 92,
   'sea_level': 1011,
   'grnd_level': 981},
  'visibility': 10000,
  'wind': {'speed': 2.57, 'deg': 180},
  'clouds': {'all': 35},
  'dt': 1787602869,
  'sys': {'type': 1,
   'id': 6513,
   'country': 'FR',
   'sunrise': 1787547953,
   'sunset': 1787596835},
  'timezone': 7200,
  'id': 3028641,
  'name': 'Carcassonne',
  'cod': 200,
  'city': 'Carcassonne'},
 {'coord': {'lon': 1.3936, 'lat': 43.15},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'base': 'stations',
  'main': {'temp': 21.35,
   'feels_like': 21.34,
   'temp_min': 19.59,
   'temp_max': 21.35,
   'pressure': 1011,
   'humidity': 69,
   'sea_level': 1011,
   'grnd_level': 972},
  'visibility': 10000,
  'wind': {'speed': 1.85, 'deg': 46, 'gust': 3.78},
  'clouds': {'all': 30},
  'dt': 1787602872,
  'sys': {'type': 2,
   'id': 20300,
   'country': 'FR',
   'sunrise': 1787548189,
   'sunset': 1787597058},
  'timezone': 7200,
  'id': 6446851,
  'name': 'Artigat',
  'cod': 200,
  'city': 'Le Carla-Bayle'},
 {'coord': {'lon': 5.5396, 'lat': 43.214},
  'weather': [{'id': 504,
    'main': 'Rain',
    'description': 'extreme rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 27.45,
   'feels_like': 31.78,
   'temp_min': 27.45,
   'temp_max': 27.45,
   'pressure': 1012,
   'humidity': 88,
   'sea_level': 1012,
   'grnd_level': 1002},
  'visibility': 10000,
  'wind': {'speed': 5.01, 'deg': 155, 'gust': 6.1},
  'rain': {'1h': 60.87},
  'clouds': {'all': 59},
  'dt': 1787602874,
  'sys': {'type': 2,
   'id': 2110835,
   'country': 'FR',
   'sunrise': 1787547187,
   'sunset': 1787596070},
  'timezone': 7200,
  'id': 3028431,
  'name': 'Cassis',
  'cod': 200,
  'city': 'Cassis'},
 {'coord': {'lon': 6.5134, 'lat': 43.8465},
  'weather': [{'id': 503,
    'main': 'Rain',
    'description': 'very heavy rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 17.19,
   'feels_like': 17.16,
   'temp_min': 17.19,
   'temp_max': 17.19,
   'pressure': 1013,
   'humidity': 84,
   'sea_level': 1013,
   'grnd_level': 889},
  'visibility': 6926,
  'wind': {'speed': 0.31, 'deg': 351, 'gust': 0.49},
  'rain': {'1h': 48.47},
  'clouds': {'all': 84},
  'dt': 1787602877,
  'sys': {'country': 'FR', 'sunrise': 1787546892, 'sunset': 1787595898},
  'timezone': 7200,
  'id': 3028382,
  'name': 'Castellane',
  'cod': 200,
  'city': 'Castellane'},
 {'coord': {'lon': 3.0832, 'lat': 42.5251},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'base': 'stations',
  'main': {'temp': 22.4,
   'feels_like': 22.89,
   'temp_min': 21.18,
   'temp_max': 24.47,
   'pressure': 1012,
   'humidity': 84,
   'sea_level': 1012,
   'grnd_level': 991},
  'visibility': 10000,
  'wind': {'speed': 2.06, 'deg': 285, 'gust': 2.85},
  'clouds': {'all': 20},
  'dt': 1787602880,
  'sys': {'type': 2,
   'id': 2041509,
   'country': 'FR',
   'sunrise': 1787547842,
   'sunset': 1787596594},
  'timezone': 7200,
  'id': 3024314,
  'name': 'Collioure',
  'cod': 200,
  'city': 'Collioure'},
 {'coord': {'lon': 7.358, 'lat': 48.0778},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'base': 'stations',
  'main': {'temp': 17.96,
   'feels_like': 17.59,
   'temp_min': 17.85,
   'temp_max': 18.36,
   'pressure': 1012,
   'humidity': 68,
   'sea_level': 1012,
   'grnd_level': 971},
  'visibility': 10000,
  'wind': {'speed': 4.9, 'deg': 357, 'gust': 9.2},
  'clouds': {'all': 76},
  'dt': 1787602883,
  'sys': {'type': 5,
   'id': 50014460,
   'country': 'FR',
   'sunrise': 1787546241,
   'sunset': 1787596144},
  'timezone': 7200,
  'id': 3024297,
  'name': 'Colmar',
  'cod': 200,
  'city': 'Colmar'},
 {'coord': {'lon': 6.1503, 'lat': 43.5281},
  'weather': [{'id': 503,
    'main': 'Rain',
    'description': 'very heavy rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 17.62,
   'feels_like': 17.76,
   'temp_min': 17.62,
   'temp_max': 17.83,
   'pressure': 1015,
   'humidity': 89,
   'sea_level': 1015,
   'grnd_level': 974},
  'visibility': 10000,
  'wind': {'speed': 0.21, 'deg': 208, 'gust': 1.11},
  'rain': {'1h': 16.4},
  'clouds': {'all': 41},
  'dt': 1787602886,
  'sys': {'type': 2,
   'id': 2006427,
   'country': 'FR',
   'sunrise': 1787547010,
   'sunset': 1787595954},
  'timezone': 7200,
  'id': 3023410,
  'name': 'Cotignac',
  'cod': 200,
  'city': 'Cotignac'},
 {'coord': {'lon': 5.0415, 'lat': 47.322},
  'weather': [{'id': 502,
    'main': 'Rain',
    'description': 'heavy intensity rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 17.8,
   'feels_like': 18.09,
   'temp_min': 17.8,
   'temp_max': 17.8,
   'pressure': 1012,
   'humidity': 94,
   'sea_level': 1012,
   'grnd_level': 972},
  'visibility': 10000,
  'wind': {'speed': 0.51, 'deg': 0},
  'rain': {'1h': 4.01},
  'clouds': {'all': 100},
  'dt': 1787602308,
  'sys': {'type': 1,
   'id': 6586,
   'country': 'FR',
   'sunrise': 1787546883,
   'sunset': 1787596613},
  'timezone': 7200,
  'id': 3006622,
  'name': 'Larrey',
  'cod': 200,
  'city': 'Dijon'},
 {'coord': {'lon': 7.308, 'lat': 48.0448},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'base': 'stations',
  'main': {'temp': 17.91,
   'feels_like': 17.53,
   'temp_min': 17.82,
   'temp_max': 18.32,
   'pressure': 1012,
   'humidity': 68,
   'sea_level': 1012,
   'grnd_level': 969},
  'visibility': 10000,
  'wind': {'speed': 4.9, 'deg': 357, 'gust': 9.2},
  'clouds': {'all': 89},
  'dt': 1787602892,
  'sys': {'type': 5,
   'id': 50014460,
   'country': 'FR',
   'sunrise': 1787546256,
   'sunset': 1787596152},
  'timezone': 7200,
  'id': 3020324,
  'name': 'Eguisheim',
  'cod': 200,
  'city': 'Eguisheim'},
 {'coord': {'lon': 1.6054, 'lat': 42.9639},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 21.12,
   'feels_like': 21.4,
   'temp_min': 19.3,
   'temp_max': 21.12,
   'pressure': 1012,
   'humidity': 81,
   'sea_level': 1012,
   'grnd_level': 922},
  'visibility': 10000,
  'wind': {'speed': 2.87, 'deg': 181, 'gust': 2.8},
  'clouds': {'all': 5},
  'dt': 1787602895,
  'sys': {'type': 2,
   'id': 20300,
   'country': 'FR',
   'sunrise': 1787548156,
   'sunset': 1787596989},
  'timezone': 7200,
  'id': 3018174,
  'name': 'Foix',
  'cod': 200,
  'city': 'Foix'},
 {'coord': {'lon': 5.7358, 'lat': 45.1876},
  'weather': [{'id': 501,
    'main': 'Rain',
    'description': 'moderate rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 21.54,
   'feels_like': 21.81,
   'temp_min': 21.54,
   'temp_max': 22.95,
   'pressure': 1012,
   'humidity': 79,
   'sea_level': 1012,
   'grnd_level': 918},
  'visibility': 10000,
  'wind': {'speed': 1.34, 'deg': 191, 'gust': 8.49},
  'rain': {'1h': 3.16},
  'clouds': {'all': 100},
  'dt': 1787602898,
  'sys': {'type': 2,
   'id': 2004515,
   'country': 'FR',
   'sunrise': 1787546944,
   'sunset': 1787596218},
  'timezone': 7200,
  'id': 6454071,
  'name': 'Grenoble',
  'cod': 200,
  'city': 'Grenoble'},
 {'coord': {'lon': -1.1511, 'lat': 46.1603},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'base': 'stations',
  'main': {'temp': 22.03,
   'feels_like': 22.22,
   'temp_min': 21.85,
   'temp_max': 22.74,
   'pressure': 1008,
   'humidity': 74,
   'sea_level': 1008,
   'grnd_level': 1008},
  'visibility': 10000,
  'wind': {'speed': 4.63, 'deg': 90},
  'clouds': {'all': 99},
  'dt': 1787602508,
  'sys': {'type': 1,
   'id': 6458,
   'country': 'FR',
   'sunrise': 1787548497,
   'sunset': 1787597971},
  'timezone': 7200,
  'id': 3006787,
  'name': 'La Rochelle',
  'cod': 200,
  'city': 'La Rochelle'},
 {'coord': {'lon': 0.108, 'lat': 49.4939},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'base': 'stations',
  'main': {'temp': 19.56,
   'feels_like': 19.11,
   'temp_min': 19.51,
   'temp_max': 20.86,
   'pressure': 1010,
   'humidity': 59,
   'sea_level': 1010,
   'grnd_level': 1008},
  'visibility': 10000,
  'wind': {'speed': 6.17, 'deg': 70},
  'clouds': {'all': 16},
  'dt': 1787602904,
  'sys': {'type': 1,
   'id': 6533,
   'country': 'FR',
   'sunrise': 1787547814,
   'sunset': 1787598049},
  'timezone': 7200,
  'id': 3003796,
  'name': 'Le Havre',
  'cod': 200,
  'city': 'Le Havre'},
 {'coord': {'lon': 1.3613, 'lat': 43.0795},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'base': 'stations',
  'main': {'temp': 21.86,
   'feels_like': 21.9,
   'temp_min': 21.86,
   'temp_max': 21.86,
   'pressure': 1011,
   'humidity': 69,
   'sea_level': 1011,
   'grnd_level': 957},
  'visibility': 10000,
  'wind': {'speed': 1.13, 'deg': 113, 'gust': 2.96},
  'clouds': {'all': 25},
  'dt': 1787602906,
  'sys': {'type': 2,
   'id': 20300,
   'country': 'FR',
   'sunrise': 1787548203,
   'sunset': 1787597059},
  'timezone': 7200,
  'id': 6446851,
  'name': 'Artigat',
  'cod': 200,
  'city': "Le Mas-d'Azil"},
 {'coord': {'lon': 3.0636, 'lat': 50.6363},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'base': 'stations',
  'main': {'temp': 19.01,
   'feels_like': 18.45,
   'temp_min': 18.71,
   'temp_max': 19.4,
   'pressure': 1013,
   'humidity': 57,
   'sea_level': 1013,
   'grnd_level': 1010},
  'visibility': 10000,
  'wind': {'speed': 4.63, 'deg': 50},
  'clouds': {'all': 13},
  'dt': 1787602765,
  'sys': {'type': 1,
   'id': 6559,
   'country': 'FR',
   'sunrise': 1787546961,
   'sunset': 1787597484},
  'timezone': 7200,
  'id': 6454414,
  'name': 'Lille',
  'cod': 200,
  'city': 'Lille'},
 {'coord': {'lon': 4.832, 'lat': 45.7578},
  'weather': [{'id': 502,
    'main': 'Rain',
    'description': 'heavy intensity rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 18.84,
   'feels_like': 19.1,
   'temp_min': 17.93,
   'temp_max': 19.13,
   'pressure': 1011,
   'humidity': 89,
   'sea_level': 1011,
   'grnd_level': 980},
  'visibility': 10000,
  'wind': {'speed': 1.54, 'deg': 10},
  'rain': {'1h': 5.46},
  'clouds': {'all': 100},
  'dt': 1787602466,
  'sys': {'type': 1,
   'id': 6505,
   'country': 'FR',
   'sunrise': 1787547102,
   'sunset': 1787596494},
  'timezone': 7200,
  'id': 8015556,
  'name': 'Vieux Lyon',
  'cod': 200,
  'city': 'Lyon'},
 {'coord': {'lon': 5.382, 'lat': 43.3034},
  'weather': [{'id': 501,
    'main': 'Rain',
    'description': 'moderate rain',
    'icon': '10n'}],
  'base': 'stations',
  'main': {'temp': 27.31,
   'feels_like': 27.15,
   'temp_min': 18.7,
   'temp_max': 27.31,
   'pressure': 1011,
   'humidity': 41,
   'sea_level': 1011,

# 2. Convert list to DataFrame

## cities dataframe convertion

In [15]:
import pandas as pd

cities_df = pd.DataFrame(cities_info)

## weather normalization

In [16]:
weather_df = pd.json_normalize(weather_info)

In [17]:
type(cities_df)

pandas.core.frame.DataFrame

In [18]:
type(weather_df)

pandas.core.frame.DataFrame

In [19]:
cities_df.head(1)

            city  place_id        lat      lon
0  Aigues-Mortes  83174366  43.566152  4.19154

In [20]:
weather_df.head(1)

,weather,base,visibility,dt,timezone,id,name,cod,city,coord.lon,...,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,wind.gust,rain.1h
0,"[{'id': 802, 'main': 'Clouds', 'description': ...",stations,10000,1787602834,7200,3038493,Aigues-Mortes,200,Aigues-Mortes,4.1915,...,1.54,20,37,1.0,6518.0,FR,1787547477,1787596427,NaN,NaN

In [21]:
weather = pd.json_normalize(weather_df['weather'])

In [22]:
weather.head(1)

                                                   0
0  {'id': 802, 'main': 'Clouds', 'description': '...

In [23]:
weather2 = pd.json_normalize(weather.to_dict(orient="records"))
weather2 = weather2.add_prefix("data.")

In [24]:
weather2.head(1)

   data.0.id data.0.main data.0.description data.0.icon
0        802      Clouds   scattered clouds         03n

In [25]:
weather_df = pd.concat(
    [weather_df.drop(columns="weather"),
     weather2],
     axis=1)

In [26]:
pd.set_option('display.max_columns', None) # display each column's dataframe
weather_df.head(1)

,base,visibility,dt,timezone,id,name,cod,city,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,wind.gust,rain.1h,data.0.id,data.0.main,data.0.description,data.0.icon
0,stations,10000,1787602834,7200,3038493,Aigues-Mortes,200,Aigues-Mortes,4.1915,43.5662,18.98,19.39,18.56,18.98,1012,94,1012,1012,1.54,20,37,1.0,6518.0,FR,1787547477,1787596427,NaN,NaN,802,Clouds,scattered clouds,03n

In [27]:
weather_df.columns

Index(['base', 'visibility', 'dt', 'timezone', 'id', 'name', 'cod', 'city',
       'coord.lon', 'coord.lat', 'main.temp', 'main.feels_like',
       'main.temp_min', 'main.temp_max', 'main.pressure', 'main.humidity',
       'main.sea_level', 'main.grnd_level', 'wind.speed', 'wind.deg',
       'clouds.all', 'sys.type', 'sys.id', 'sys.country', 'sys.sunrise',
       'sys.sunset', 'wind.gust', 'rain.1h', 'data.0.id', 'data.0.main',
       'data.0.description', 'data.0.icon'],
      dtype='object')

# 3. Merge DataFrames on 'city'

In [28]:
current_weather = pd.merge(cities_df, weather_df, on='city')

# Display key columns
print("\nCurrent weather:")
current_weather.head()

Current weather:

,city,place_id,lat,lon,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,wind.gust,rain.1h,data.0.id,data.0.main,data.0.description,data.0.icon
0,Aigues-Mortes,83174366,43.566152,4.191540,stations,10000,1787602834,7200,3038493,Aigues-Mortes,200,4.1915,43.5662,18.98,19.39,18.56,18.98,1012,94,1012,1012,1.54,20,37,1.0,6518.0,FR,1787547477,1787596427,NaN,NaN,802,Clouds,scattered clouds,03n
1,Aix-en-Provence,82779545,43.529842,5.447474,stations,10000,1787602810,7200,3038354,Aix-en-Provence,200,5.4541,43.5264,17.74,17.92,16.10,17.74,1012,90,1012,981,4.71,189,57,1.0,6512.0,FR,1787547177,1787596121,10.50,3.65,501,Rain,moderate rain,10n
2,Amiens,99515658,49.894171,2.295695,stations,10000,1787602308,7200,3037854,Amiens,200,2.2957,49.8942,19.78,19.30,19.78,19.78,1012,57,1012,1001,5.15,60,44,NaN,NaN,FR,1787547239,1787597574,12.27,NaN,802,Clouds,scattered clouds,03n
3,Annecy,88514330,45.899235,6.128885,stations,10000,1787602842,7200,3037543,Annecy,200,6.1289,45.8992,20.08,20.15,20.08,20.08,1012,77,1012,927,5.66,300,100,1.0,6500.0,FR,1787546776,1787596198,NaN,NaN,804,Clouds,overcast clouds,04n
4,Avignon,82758863,43.949249,4.805901,stations,1127,1787602844,7200,3035681,Avignon,200,4.8059,43.9492,19.05,19.47,18.21,19.05,1012,94,1012,1006,3.09,330,72,1.0,6520.0,FR,1787547292,1787596317,NaN,0.71,500,Rain,light rain,10n

In [32]:
current_weather.head(2)

,city,place_id,lat,lon,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,wind.gust,rain.1h,data.0.id,data.0.main,data.0.description,data.0.icon
0,Aigues-Mortes,83174366,43.566152,4.191540,stations,10000,1787602834,7200,3038493,Aigues-Mortes,200,4.1915,43.5662,18.98,19.39,18.56,18.98,1012,94,1012,1012,1.54,20,37,1.0,6518.0,FR,1787547477,1787596427,NaN,NaN,802,Clouds,scattered clouds,03n
1,Aix-en-Provence,82779545,43.529842,5.447474,stations,10000,1787602810,7200,3038354,Aix-en-Provence,200,5.4541,43.5264,17.74,17.92,16.10,17.74,1012,90,1012,981,4.71,189,57,1.0,6512.0,FR,1787547177,1787596121,10.5,3.65,501,Rain,moderate rain,10n

In [30]:
type(current_weather)

pandas.core.frame.DataFrame

In [31]:
print(current_weather.head())

              city  place_id        lat       lon      base  visibility  \
0    Aigues-Mortes  83174366  43.566152  4.191540  stations       10000
1  Aix-en-Provence  82779545  43.529842  5.447474  stations       10000
2           Amiens  99515658  49.894171  2.295695  stations       10000
3           Annecy  88514330  45.899235  6.128885  stations       10000
4          Avignon  82758863  43.949249  4.805901  stations        1127

           dt  timezone       id             name  cod  coord.lon  coord.lat  \
0  1787602834      7200  3038493    Aigues-Mortes  200     4.1915    43.5662
1  1787602810      7200  3038354  Aix-en-Provence  200     5.4541    43.5264
2  1787602308      7200  3037854           Amiens  200     2.2957    49.8942
3  1787602842      7200  3037543           Annecy  200     6.1289    45.8992
4  1787602844      7200  3035681          Avignon  200     4.8059    43.9492

   main.temp  main.feels_like  main.temp_min  main.temp_max  main.pressure  \
0      18.98            19.39          18.56          18.98           1012
1      17.74            17.92          16.10          17.74           1012
2      19.78            19.30          19.78          19.78           1012
3      20.08            20.15          20.08          20.08           1012
4      19.05            19.47          18.21          19.05           1012

   main.humidity  main.sea_level  main.grnd_level  wind.speed  wind.deg  \
0             94            1012             1012        1.54        20
1             90            1012              981        4.71       189
2             57            1012             1001        5.15        60
3             77            1012              927        5.66       300
4             94            1012             1006        3.09       330

   clouds.all  sys.type  sys.id sys.country  sys.sunrise  sys.sunset  \
0          37       1.0  6518.0          FR   1787547477  1787596427
1          57       1.0  6512.0          FR   1787547177  1787596121
2          44       NaN     NaN          FR   1787547239  1787597574
3         100       1.0  6500.0          FR   1787546776  1787596198
4          72       1.0  6520.0          FR   1787547292  1787596317

   wind.gust  rain.1h  data.0.id data.0.main data.0.description data.0.icon
0        NaN      NaN        802      Clouds   scattered clouds         03n
1      10.50     3.65        501        Rain      moderate rain         10n
2      12.27      NaN        802      Clouds   scattered clouds         03n
3        NaN      NaN        804      Clouds    overcast clouds         04n
4        NaN     0.71        500        Rain         light rain         10n