Lets focus on basic data analysis and the cities locations.

In [1]:
# Libraries import

import requests
import json
import time
from dotenv import load_dotenv
import os
import pandas as pd

# Configuration

pd.set_option('display.max_columns', None) # display each column's dataframe

# 1. Call api

## Call api nominatim

In [2]:
# import requests

nominatim_url = "https://nominatim.openstreetmap.org/search"
cities_info = f"{nominatim_url}/cities_location.json"

params = {
    "country": "France",
    "city": "Bayeux",
    "format": "geocodejson"
}

headers = {"User-Agent": "projet_etude_dataviz (lnmourez@gmail.com)"}

### Fetch cities information

In [3]:
# import json

nominatim_response = requests.get(nominatim_url, params=params, headers=headers) # call api

print(nominatim_response) # call api status code 
print(nominatim_response.content) # take a look at the data that was recieved along with this response
#print(json.dumps(response.json(), indent=2)) # add json indentation

<Response [200]>
b'{"type":"FeatureCollection","geocoding":{"version":"0.1.0","attribution":"Data \xc2\xa9 OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright","licence":"ODbL","query":"Bayeux, France"},"features":[{"type":"Feature","properties":{"geocoding":{"place_id":284771403,"osm_type":"relation","osm_id":145776,"osm_key":"boundary","osm_value":"administrative","type":"city","label":"Bayeux, Calvados, Normandie, France m\xc3\xa9tropolitaine, 14400, France","name":"Bayeux"}},"geometry":{"type": "Point","coordinates": [-0.7024738, 49.2764624]}},{"type":"Feature","properties":{"geocoding":{"place_id":284516418,"osm_type":"relation","osm_id":1656892,"osm_key":"boundary","osm_value":"administrative","type":"city","label":"Bayeux, Calvados, Normandie, France m\xc3\xa9tropolitaine, France","name":"Bayeux"}},"geometry":{"type": "Point","coordinates": [-0.791677, 49.2455634]}}]}'

In [4]:
type(nominatim_response.json())  # display type

dict

#### Fetch one city location

In [5]:
feature = nominatim_response.json()["features"][0] # declare the first result
city = feature["properties"]["geocoding"]["name"]
place_id = feature["properties"]["geocoding"]["place_id"]
lat = feature["geometry"]["coordinates"][1]
lon = feature["geometry"]["coordinates"][0]
response = requests.get(nominatim_url, params=params, headers=headers)
print()
print(f"{city}, {place_id},{lon}, {lat}")

Bayeux, 284771403,-0.7024738, 49.2764624

#### Fetch the cities list location

In the provided cities list, we observe that :
1) Ariège is a department. 
2) Gorges du Verdon and Chateau du haut Koenigsbourg are tourist sites

It could be interesting to search some nearby locations. 

Ariège :
- https://www.guide-toulouse-pyrenees.com/fr/experiences/culturelle/article-les-plus-beaux-villages-de-l-ariege-106.html
- https://www.sites-touristiques-ariege.fr/informations-pratiques/visiter-lariege/

Bédeilhac-et-Aynat
Camon
Carla-Bayle
Foix
Le Mas-d’Azil
Mirepoix
Montségur
Niaux
Saint-Lizier
Saint-Martin-d’Oydes
Tarascon-sur-Ariège

Gorges du Verdon : 
https://lesgorgesduverdon.fr/a-visiter/

Barjols
Castellane
Cotignac
Moustiers-Sainte-Marie
Sainte-Croix-du-Verdon
Sillans-la-Cascade
Valensole

Chateau du haut Koenigsbourg (ORSCHWILLER)
https://www.haut-koenigsbourg.fr/infos-pratiques/

In [6]:
# import time

cities_info = []
cities = ["Aigues Mortes",
"Aix en Provence",
"Amiens",
"Annecy",
"Avignon",
"Barjols",
"Bayeux",
"Bayonne",
"Besancon",
"Biarritz",
"Bormes les Mimosas",
"Bédeilhac-et-Aynat",
"Camon",
"Carcassonne",
"Carla-Bayle",
"Cassis",
"Castellane",
"Collioure",
"Colmar",
"Cotignac",
"Dijon",
"Eguisheim",
"Foix",
"Grenoble",
"La Rochelle",
"Le Havre",
"Le Mas-d’Azil",
"Lille",
"Lyon",
"Marseille",
"Mirepoix",
"Mont Saint Michel",
"Montauban",
"Montségur",
"Moustiers-Sainte-Marie",
"Niaux",
"Nimes",
"Orschwiller",
"Paris",
"Rouen",
"Saint-Lizier",
"Saint-Martin-d’Oydes",
"Sainte-Croix-du-Verdon",
"Saintes Maries de la mer",
"Sillans-la-Cascade",
"St Malo",
"Strasbourg",
"Tarascon-sur-Ariège",
"Toulouse",
"Uzes",
"Valensole"
]

for city in cities:
    try:
        nominatim_response = requests.get(
            nominatim_url, 
            params={"country": "France",
            "city": city,
            "format": "geocodejson"
            },
            headers=headers)
        # print(f"{city}: {response.status_code}")  # vérifiez le code HTTP


        feature = nominatim_response.json()["features"][0]
        cities_info.append({"city" : feature["properties"]["geocoding"]["name"],
        "place_id" : feature["properties"]["geocoding"]["place_id"],
        "lat" : feature["geometry"]["coordinates"][1],
        "lon" : feature["geometry"]["coordinates"][0]
        })
    except (IndexError, KeyError, requests.exceptions.RequestException):
        print(f"Execution with errors for {city} : {nominatim_response.status_code}")
      
    time.sleep(2)

In [7]:
# import json
print(len(cities_info))
print(cities_info)
#print(json.dumps(cities_location, indent=2))

51
[{'city': 'Aigues-Mortes', 'place_id': 83121595, 'lat': 43.5661521, 'lon': 4.19154}, {'city': 'Aix-en-Provence', 'place_id': 82709709, 'lat': 43.5298424, 'lon': 5.4474738}, {'city': 'Amiens', 'place_id': 99515658, 'lat': 49.8941708, 'lon': 2.2956951}, {'city': 'Annecy', 'place_id': 88762115, 'lat': 45.8992348, 'lon': 6.1288847}, {'city': 'Avignon', 'place_id': 82703601, 'lat': 43.9492493, 'lon': 4.8059012}, {'city': 'Barjols', 'place_id': 82290101, 'lat': 43.558133, 'lon': 6.0056803}, {'city': 'Bayeux', 'place_id': 284771403, 'lat': 49.2764624, 'lon': -0.7024738}, {'city': 'Bayonne', 'place_id': 291698146, 'lat': 43.4945144, 'lon': -1.4736657}, {'city': 'Besançon', 'place_id': 92553994, 'lat': 47.2380222, 'lon': 6.0243622}, {'city': 'Biarritz', 'place_id': 287222151, 'lat': 43.4832523, 'lon': -1.5592776}, {'city': 'Bormes-les-Mimosas', 'place_id': 82541806, 'lat': 43.1506968, 'lon': 6.3419285}, {'city': 'Bédeilhac-et-Aynat', 'place_id': 84249524, 'lat': 42.8816132, 'lon': 1.5674969}, {'city': 'Camon', 'place_id': 99400021, 'lat': 49.8874246, 'lon': 2.3446546}, {'city': 'Carcassonne', 'place_id': 85203402, 'lat': 43.2130358, 'lon': 2.3491069}, {'city': 'Le Carla-Bayle', 'place_id': 85080454, 'lat': 43.1500386, 'lon': 1.3936011}, {'city': 'Cassis', 'place_id': 83165753, 'lat': 43.2140359, 'lon': 5.5396318}, {'city': 'Castellane', 'place_id': 82659450, 'lat': 43.846459, 'lon': 6.5134463}, {'city': 'Collioure', 'place_id': 84564617, 'lat': 42.52505, 'lon': 3.0831554}, {'city': 'Colmar', 'place_id': 119771663, 'lat': 48.0777517, 'lon': 7.3579641}, {'city': 'Cotignac', 'place_id': 82761453, 'lat': 43.5280531, 'lon': 6.1502672}, {'city': 'Dijon', 'place_id': 93940430, 'lat': 47.3215806, 'lon': 5.0414701}, {'city': 'Eguisheim', 'place_id': 121333649, 'lat': 48.0447968, 'lon': 7.3079618}, {'city': 'Foix', 'place_id': 84674104, 'lat': 42.9638998, 'lon': 1.6053807}, {'city': 'Grenoble', 'place_id': 89789042, 'lat': 45.1875602, 'lon': 5.7357819}, {'city': 'La Rochelle', 'place_id': 290369823, 'lat': 46.159732, 'lon': -1.1515951}, {'city': 'Le Havre', 'place_id': 99622516, 'lat': 49.4938975, 'lon': 0.1079732}, {'city': "Le Mas-d'Azil", 'place_id': 85690532, 'lat': 43.0794579, 'lon': 1.3613197}, {'city': 'Lille', 'place_id': 102005298, 'lat': 50.6365654, 'lon': 3.0635282}, {'city': 'Lyon', 'place_id': 90002899, 'lat': 45.7578137, 'lon': 4.8320114}, {'city': 'Marseille', 'place_id': 83042786, 'lat': 43.2963986, 'lon': 5.3777888}, {'city': 'Mirepoix', 'place_id': 86315261, 'lat': 43.7458333, 'lon': 0.6719444}, {'city': 'Mont Saint-Michel', 'place_id': 120400975, 'lat': 48.6906803, 'lon': 5.8826485}, {'city': 'Montauban', 'place_id': 85485907, 'lat': 44.0175835, 'lon': 1.3549991}, {'city': 'Montségur', 'place_id': 84371924, 'lat': 42.8707548, 'lon': 1.8337452}, {'city': 'Moustiers-Sainte-Marie', 'place_id': 81639300, 'lat': 43.8460089, 'lon': 6.2217604}, {'city': 'Niaux', 'place_id': 84333342, 'lat': 42.8093089, 'lon': 1.5911122}, {'city': 'Nîmes', 'place_id': 83331461, 'lat': 43.8374249, 'lon': 4.3600687}, {'city': 'Orschwiller', 'place_id': 121122082, 'lat': 48.2422436, 'lon': 7.3799809}, {'city': 'Paris', 'place_id': 97683695, 'lat': 48.8534951, 'lon': 2.3483915}, {'city': 'Rouen', 'place_id': 99298218, 'lat': 49.4404591, 'lon': 1.0939658}, {'city': 'Saint-Lizier', 'place_id': 83976086, 'lat': 43.0025191, 'lon': 1.1354926}, {'city': "Saint-Martin-d'Oydes", 'place_id': 85322018, 'lat': 43.169734, 'lon': 1.4955303}, {'city': 'Sainte-Croix-du-Verdon', 'place_id': 82484741, 'lat': 43.7589451, 'lon': 6.1518294}, {'city': 'Saintes-Maries-de-la-Mer', 'place_id': 83337373, 'lat': 43.4515922, 'lon': 4.4277202}, {'city': 'Sillans-la-Cascade', 'place_id': 82528656, 'lat': 43.5673969, 'lon': 6.1795387}, {'city': 'Saint-Malo', 'place_id': 284423924, 'lat': 48.649518, 'lon': -2.0260409}, {'city': 'Strasbourg', 'place_id': 120975157, 'lat': 48.584614, 'lon': 7.7507127}, {'city': 'Tarascon-sur-Ariège', 'place_id': 84742066, 'lat': 42.8492109, 'lon': 1.6043495}, {'city': 'Toulouse', 'place_id': 85268269, 'lat': 43.6044638, 'lon': 1.4442433}, {'city': 'Uzès', 'place_id': 87602259, 'lat': 44.0121279, 'lon': 4.4196718}, {'city': 'Valensole', 'place_id': 87359820, 'lat': 43.8379283, 'lon': 5.9839867}]

In [33]:
type(cities_info)

list

## 2. Call api openweathermap

In [8]:
# from dotenv import load_dotenv
# import os
# V2.5 https://api.openweathermap.org/data/2.5/weather
# V4.0 https://api.openweathermap.org/data/4.0/onecall/current

weather_url = "https://api.openweathermap.org/data/2.5/weather"
params = {
    "lat":"48.635954",
    "lon":"-1.511460",
    "units":"metric",
    "appid": os.getenv("API_KEY")
}

### Fetch weather information

In [9]:
weather_response = requests.get(weather_url, params=params) # call api
weather_json = weather_response.json()

print(weather_response, weather_json)

<Response [200]> {'coord': {'lon': -1.5115, 'lat': 48.636}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 25.4, 'feels_like': 25.01, 'temp_min': 25.4, 'temp_max': 25.4, 'pressure': 1008, 'humidity': 39, 'sea_level': 1008, 'grnd_level': 1003}, 'visibility': 10000, 'wind': {'speed': 3.9, 'deg': 238, 'gust': 5.37}, 'clouds': {'all': 85}, 'dt': 1787668895, 'sys': {'country': 'FR', 'sunrise': 1787634791, 'sunset': 1787684618}, 'timezone': 7200, 'id': 6435453, 'name': 'Huisnes-sur-Mer', 'cod': 200}

In [10]:
weather_info = []
for city in cities_info:
    try:
        params = {
            "lat": city["lat"], 
            "lon": city["lon"], 
            "units": "metric", 
            "appid": "65a6acbff3eb4de13c8e4cf52a30ccf2"
            }
        weather_response = requests.get(weather_url, params=params)
        weather = weather_response.json()
        weather['city'] = city['city'] #weather_info.append({"city": city["city"], "weather": weather_response.json()})
        weather_info.append(weather)
    except (IndexError, KeyError, requests.exceptions.RequestException):
        print(f"Execution with errors for {city} : {weather_response.status_code}")
    time.sleep(2)

In [11]:
print(cities_info[0].keys())  # display keys

dict_keys(['city', 'place_id', 'lat', 'lon'])

In [12]:
print(weather_info[0].keys())  # display keys

dict_keys(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'clouds', 'dt', 'sys', 'timezone', 'id', 'name', 'cod', 'city'])

In [13]:
# print(json.dumps(weather_info, indent=2))

In [14]:
type(weather_info)

list

In [15]:
weather_info

[{'coord': {'lon': 4.1915, 'lat': 43.5662},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 27.29,
   'feels_like': 28.21,
   'temp_min': 26.98,
   'temp_max': 31.56,
   'pressure': 1011,
   'humidity': 57,
   'sea_level': 1011,
   'grnd_level': 1011},
  'visibility': 10000,
  'wind': {'speed': 4.12, 'deg': 200},
  'clouds': {'all': 72},
  'dt': 1787668896,
  'sys': {'type': 1,
   'id': 6518,
   'country': 'FR',
   'sunrise': 1787633944,
   'sunset': 1787682728},
  'timezone': 7200,
  'id': 3038493,
  'name': 'Aigues-Mortes',
  'cod': 200,
  'city': 'Aigues-Mortes'},
 {'coord': {'lon': 5.4475, 'lat': 43.5298},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'base': 'stations',
  'main': {'temp': 30.51,
   'feels_like': 33.83,
   'temp_min': 28.71,
   'temp_max': 30.78,
   'pressure': 1011,
   'humidity': 60,
   'sea_level': 1011,
   'grnd_level': 979},
  'visibility': 10000,
  'wind': {'speed': 1.79, 'deg': 281, 'gust': 3.58},
  'clouds': {'all': 42},
  'dt': 1787668899,
  'sys': {'type': 2,
   'id': 2006832,
   'country': 'FR',
   'sunrise': 1787633646,
   'sunset': 1787682423},
  'timezone': 7200,
  'id': 3038354,
  'name': 'Aix-en-Provence',
  'cod': 200,
  'city': 'Aix-en-Provence'},
 {'coord': {'lon': 2.303, 'lat': 49.8917},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 25.46,
   'feels_like': 25.21,
   'temp_min': 25.46,
   'temp_max': 25.46,
   'pressure': 1010,
   'humidity': 44,
   'sea_level': 1010,
   'grnd_level': 1000},
  'visibility': 10000,
  'wind': {'speed': 4.09, 'deg': 93, 'gust': 4},
  'clouds': {'all': 70},
  'dt': 1787668521,
  'sys': {'type': 1,
   'id': 6446,
   'country': 'FR',
   'sunrise': 1787633727,
   'sunset': 1787683851},
  'timezone': 7200,
  'id': 3037854,
  'name': 'Amiens',
  'cod': 200,
  'city': 'Amiens'},
 {'coord': {'lon': 6.1289, 'lat': 45.8992},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 29.08,
   'feels_like': 28.43,
   'temp_min': 27.79,
   'temp_max': 29.08,
   'pressure': 1012,
   'humidity': 37,
   'sea_level': 1012,
   'grnd_level': 928},
  'visibility': 10000,
  'wind': {'speed': 1.03, 'deg': 0},
  'clouds': {'all': 62},
  'dt': 1787668906,
  'sys': {'type': 1,
   'id': 6500,
   'country': 'FR',
   'sunrise': 1787633251,
   'sunset': 1787682492},
  'timezone': 7200,
  'id': 3037543,
  'name': 'Annecy',
  'cod': 200,
  'city': 'Annecy'},
 {'coord': {'lon': 4.81, 'lat': 43.95},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 32.22,
   'feels_like': 32.41,
   'temp_min': 31.16,
   'temp_max': 32.44,
   'pressure': 1011,
   'humidity': 39,
   'sea_level': 1011,
   'grnd_level': 1004},
  'visibility': 10000,
  'wind': {'speed': 1.54, 'deg': 0},
  'clouds': {'all': 51},
  'dt': 1787668768,
  'sys': {'type': 1,
   'id': 6520,
   'country': 'FR',
   'sunrise': 1787633759,
   'sunset': 1787682616},
  'timezone': 7200,
  'id': 3035681,
  'name': 'Avignon',
  'cod': 200,
  'city': 'Avignon'},
 {'coord': {'lon': 6.0057, 'lat': 43.5581},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'base': 'stations',
  'main': {'temp': 33.05,
   'feels_like': 35.29,
   'temp_min': 32.6,
   'temp_max': 33.05,
   'pressure': 1011,
   'humidity': 46,
   'sea_level': 1011,
   'grnd_level': 967},
  'visibility': 10000,
  'wind': {'speed': 3.95, 'deg': 251, 'gust': 3},
  'clouds': {'all': 44},
  'dt': 1787668913,
  'sys': {'type': 2,
   'id': 2006427,
   'country': 'FR',
   'sunrise': 1787633509,
   'sunset': 1787682292},
  'timezone': 7200,
  'id': 3034918,
  'name': 'Barjols',
  'cod': 200,
  'city': 'Barjols'},
 {'coord': {'lon': -0.7, 'lat': 49.28},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'base': 'stations',
  'main': {'temp': 26.19,
   'feels_like': 26.19,
   'temp_min': 26.19,
   'temp_max': 26.19,
   'pressure': 1009,
   'humidity': 67,
   'sea_level': 1009,
   'grnd_level': 1003},
  'visibility': 10000,
  'wind': {'speed': 4.64, 'deg': 46, 'gust': 7.42},
  'clouds': {'all': 41},
  'dt': 1787668699,
  'sys': {'type': 1,
   'id': 6569,
   'country': 'FR',
   'sunrise': 1787634521,
   'sunset': 1787684498},
  'timezone': 7200,
  'id': 6447202,
  'name': 'Bayeux',
  'cod': 200,
  'city': 'Bayeux'},
 {'coord': {'lon': -1.4737, 'lat': 43.4945},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 24.42,
   'feels_like': 24.82,
   'temp_min': 24.42,
   'temp_max': 26.21,
   'pressure': 1013,
   'humidity': 73,
   'sea_level': 1013,
   'grnd_level': 1008},
  'visibility': 10000,
  'wind': {'speed': 4.63, 'deg': 330},
  'clouds': {'all': 100},
  'dt': 1787668920,
  'sys': {'type': 1,
   'id': 6478,
   'country': 'FR',
   'sunrise': 1787635312,
   'sunset': 1787684079},
  'timezone': 7200,
  'id': 3034475,
  'name': 'Bayonne',
  'cod': 200,
  'city': 'Bayonne'},
 {'coord': {'lon': 6.0244, 'lat': 47.238},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 24.68,
   'feels_like': 24.9,
   'temp_min': 24.68,
   'temp_max': 25,
   'pressure': 1012,
   'humidity': 65,
   'sea_level': 1012,
   'grnd_level': 973},
  'visibility': 10000,
  'wind': {'speed': 0.63, 'deg': 209, 'gust': 0.89},
  'clouds': {'all': 84},
  'dt': 1787668923,
  'sys': {'type': 2,
   'id': 2003958,
   'country': 'FR',
   'sunrise': 1787633135,
   'sunset': 1787682657},
  'timezone': 7200,
  'id': 3033123,
  'name': 'Besançon',
  'cod': 200,
  'city': 'Besançon'},
 {'coord': {'lon': -1.5593, 'lat': 43.4833},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 24.3,
   'feels_like': 24.69,
   'temp_min': 24.3,
   'temp_max': 25.85,
   'pressure': 1013,
   'humidity': 73,
   'sea_level': 1013,
   'grnd_level': 1010},
  'visibility': 10000,
  'wind': {'speed': 4.63, 'deg': 330},
  'clouds': {'all': 100},
  'dt': 1787668926,
  'sys': {'type': 1,
   'id': 6478,
   'country': 'FR',
   'sunrise': 1787635333,
   'sunset': 1787684099},
  'timezone': 7200,
  'id': 3032797,
  'name': 'Biarritz',
  'cod': 200,
  'city': 'Biarritz'},
 {'coord': {'lon': 6.3419, 'lat': 43.1507},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 28.77,
   'feels_like': 32.23,
   'temp_min': 27.23,
   'temp_max': 32.76,
   'pressure': 1011,
   'humidity': 70,
   'sea_level': 1011,
   'grnd_level': 995},
  'visibility': 10000,
  'wind': {'speed': 7.2, 'deg': 230},
  'clouds': {'all': 79},
  'dt': 1787668929,
  'sys': {'type': 2,
   'id': 2006377,
   'country': 'FR',
   'sunrise': 1787633466,
   'sunset': 1787682174},
  'timezone': 7200,
  'id': 3031532,
  'name': 'Bormes-les-Mimosas',
  'cod': 200,
  'city': 'Bormes-les-Mimosas'},
 {'coord': {'lon': 1.5675, 'lat': 42.8816},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 23.06,
   'feels_like': 22.73,
   'temp_min': 23.06,
   'temp_max': 24.29,
   'pressure': 1014,
   'humidity': 50,
   'sea_level': 1014,
   'grnd_level': 885},
  'visibility': 10000,
  'wind': {'speed': 2.7, 'deg': 18, 'gust': 1.7},
  'clouds': {'all': 85},
  'dt': 1787668932,
  'sys': {'type': 2,
   'id': 2106908,
   'country': 'FR',
   'sunrise': 1787634638,
   'sunset': 1787683293},
  'timezone': 7200,
  'id': 6426331,
  'name': 'Tarascon-sur-Ariège',
  'cod': 200,
  'city': 'Bédeilhac-et-Aynat'},
 {'coord': {'lon': 2.3447, 'lat': 49.8874},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 25.51,
   'feels_like': 25.27,
   'temp_min': 25.51,
   'temp_max': 25.51,
   'pressure': 1010,
   'humidity': 44,
   'sea_level': 1010,
   'grnd_level': 1000},
  'visibility': 10000,
  'wind': {'speed': 4.12, 'deg': 92, 'gust': 4.01},
  'clouds': {'all': 72},
  'dt': 1787668936,
  'sys': {'type': 1,
   'id': 6446,
   'country': 'FR',
   'sunrise': 1787633718,
   'sunset': 1787683841},
  'timezone': 7200,
  'id': 3029003,
  'name': 'Camon',
  'cod': 200,
  'city': 'Camon'},
 {'coord': {'lon': 2.3491, 'lat': 43.213},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 30.89,
   'feels_like': 31.71,
   'temp_min': 28.49,
   'temp_max': 31.06,
   'pressure': 1012,
   'humidity': 46,
   'sea_level': 1012,
   'grnd_level': 982},
  'visibility': 10000,
  'wind': {'speed': 4.63, 'deg': 320},
  'clouds': {'all': 53},
  'dt': 1787668940,
  'sys': {'type': 1,
   'id': 6513,
   'country': 'FR',
   'sunrise': 1787634420,
   'sunset': 1787683137},
  'timezone': 7200,
  'id': 3028641,
  'name': 'Carcassonne',
  'cod': 200,
  'city': 'Carcassonne'},
 {'coord': {'lon': 1.3936, 'lat': 43.15},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 27.45,
   'feels_like': 27.79,
   'temp_min': 26.22,
   'temp_max': 27.46,
   'pressure': 1012,
   'humidity': 49,
   'sea_level': 1012,
   'grnd_level': 974},
  'visibility': 10000,
  'wind': {'speed': 3.16, 'deg': 4, 'gust': 2.8},
  'clouds': {'all': 74},
  'dt': 1787668944,
  'sys': {'type': 2,
   'id': 20300,
   'country': 'FR',
   'sunrise': 1787634655,
   'sunset': 1787683360},
  'timezone': 7200,
  'id': 6446851,
  'name': 'Artigat',
  'cod': 200,
  'city': 'Le Carla-Bayle'},
 {'coord': {'lon': 5.5396, 'lat': 43.214},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'base': 'stations',
  'main': {'temp': 27.93,
   'feels_like': 30.4,
   'temp_min': 27.74,
   'temp_max': 28.54,
   'pressure': 1011,
   'humidity': 69,
   'sea_level': 1011,
   'grnd_level': 1000},
  'visibility': 10000,
  'wind': {'speed': 3.34, 'deg': 198, 'gust': 3.11},
  'clouds': {'all': 39},
  'dt': 1787668947,
  'sys': {'type': 2,
   'id': 80238,
   'country': 'FR',
   'sunrise': 1787633653,
   'sunset': 1787682372},
  'timezone': 7200,
  'id': 3028431,
  'name': 'Cassis',
  'cod': 200,
  'city': 'Cassis'},
 {'coord': {'lon': 6.5134, 'lat': 43.8465},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 25.1,
   'feels_like': 24.89,
   'temp_min': 25.1,
   'temp_max': 25.1,
   'pressure': 1013,
   'humidity': 47,
   'sea_level': 1013,
   'grnd_level': 888},
  'visibility': 10000,
  'wind': {'speed': 3, 'deg': 282, 'gust': 3.88},
  'clouds': {'all': 87},
  'dt': 1787668951,
  'sys': {'country': 'FR', 'sunrise': 1787633360, 'sunset': 1787682198},
  'timezone': 7200,
  'id': 3028382,
  'name': 'Castellane',
  'cod': 200,
  'city': 'Castellane'},
 {'coord': {'lon': 3.0832, 'lat': 42.5251},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 27.03,
   'feels_like': 27.38,
   'temp_min': 26.14,
   'temp_max': 30.68,
   'pressure': 1011,
   'humidity': 49,
   'sea_level': 1011,
   'grnd_level': 991},
  'visibility': 10000,
  'wind': {'speed': 3.12, 'deg': 123, 'gust': 2.23},
  'clouds': {'all': 99},
  'dt': 1787668954,
  'sys': {'type': 2,
   'id': 2036964,
   'country': 'FR',
   'sunrise': 1787634306,
   'sunset': 1787682898},
  'timezone': 7200,
  'id': 3024314,
  'name': 'Collioure',
  'cod': 200,
  'city': 'Collioure'},
 {'coord': {'lon': 7.358, 'lat': 48.0778},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 23.95,
   'feels_like': 23.55,
   'temp_min': 23.94,
   'temp_max': 25.07,
   'pressure': 1014,
   'humidity': 44,
   'sea_level': 1014,
   'grnd_level': 973},
  'visibility': 10000,
  'wind': {'speed': 2.06, 'deg': 360},
  'clouds': {'all': 87},
  'dt': 1787668957,
  'sys': {'type': 1,
   'id': 6482,
   'country': 'FR',
   'sunrise': 1787632723,
   'sunset': 1787682429},
  'timezone': 7200,
  'id': 3024297,
  'name': 'Colmar',
  'cod': 200,
  'city': 'Colmar'},
 {'coord': {'lon': 6.1503, 'lat': 43.5281},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'base': 'stations',
  'main': {'temp': 33.08,
   'feels_like': 36.45,
   'temp_min': 31.83,
   'temp_max': 33.17,
   'pressure': 1011,
   'humidity': 50,
   'sea_level': 1011,
   'grnd_level': 972},
  'visibility': 10000,
  'wind': {'speed': 3.96, 'deg': 246, 'gust': 3.48},
  'clouds': {'all': 50},
  'dt': 1787668960,
  'sys': {'type': 2,
   'id': 2006427,
   'country': 'FR',
   'sunrise': 1787633477,
   'sunset': 1787682255},
  'timezone': 7200,
  'id': 3023410,
  'name': 'Cotignac',
  'cod': 200,
  'city': 'Cotignac'},
 {'coord': {'lon': 5.0415, 'lat': 47.3216},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 24.8,
   'feels_like': 24.93,
   'temp_min': 24.8,
   'temp_max': 24.8,
   'pressure': 1013,
   'humidity': 61,
   'sea_level': 1013,
   'grnd_level': 975},
  'visibility': 10000,
  'wind': {'speed': 2.57, 'deg': 220},
  'clouds': {'all': 100},
  'dt': 1787668963,
  'sys': {'type': 1,
   'id': 6586,
   'country': 'FR',
   'sunrise': 1787633362,
   'sunset': 1787682902},
  'timezone': 7200,
  'id': 3006622,
  'name': 'Larrey',
  'cod': 200,
  'city': 'Dijon'},
 {'coord': {'lon': 7.308, 'lat': 48.0448},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 24.04,
   'feels_like': 24.25,
   'temp_min': 22.54,
   'temp_max': 25.04,
   'pressure': 1013,
   'humidity': 67,
   'sea_level': 1013,
   'grnd_level': 970},
  'visibility': 10000,
  'wind': {'speed': 2.06, 'deg': 360},
  'clouds': {'all': 86},
  'dt': 1787668966,
  'sys': {'type': 5,
   'id': 50014460,
   'country': 'FR',
   'sunrise': 1787632739,
   'sunset': 1787682438},
  'timezone': 7200,
  'id': 3020324,
  'name': 'Eguisheim',
  'cod': 200,
  'city': 'Eguisheim'},
 {'coord': {'lon': 1.6054, 'lat': 42.9639},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 26,
   'feels_like': 26,
   'temp_min': 25.99,
   'temp_max': 27.23,
   'pressure': 1013,
   'humidity': 49,
   'sea_level': 1013,
   'grnd_level': 924},
  'visibility': 10000,
  'wind': {'speed': 2.69, 'deg': 17, 'gust': 1.9},
  'clouds': {'all': 74},
  'dt': 1787668969,
  'sys': {'type': 2,
   'id': 2106908,
   'country': 'FR',
   'sunrise': 1787634621,
   'sunset': 1787683292},
  'timezone': 7200,
  'id': 3018174,
  'name': 'Foix',
  'cod': 200,
  'city': 'Foix'},
 {'coord': {'lon': 5.7358, 'lat': 45.1876},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 28.2,
   'feels_like': 29.87,
   'temp_min': 27.39,
   'temp_max': 28.2,
   'pressure': 1012,
   'humidity': 61,
   'sea_level': 1012,
   'grnd_level': 918},
  'visibility': 10000,
  'wind': {'speed': 1.01, 'deg': 305, 'gust': 2.42},
  'clouds': {'all': 70},
  'dt': 1787668973,
  'sys': {'type': 2,
   'id': 2004515,
   'country': 'FR',
   'sunrise': 1787633417,
   'sunset': 1787682514},
  'timezone': 7200,
  'id': 6454071,
  'name': 'Grenoble',
  'cod': 200,
  'city': 'Grenoble'},
 {'coord': {'lon': -1.1516, 'lat': 46.1597},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 25.32,
   'feels_like': 25.63,
   'temp_min': 24.4,
   'temp_max': 26.29,
   'pressure': 1012,
   'humidity': 66,
   'sea_level': 1012,
   'grnd_level': 1012},
  'visibility': 10000,
  'wind': {'speed': 5.14, 'deg': 220},
  'clouds': {'all': 100},
  'dt': 1787668976,
  'sys': {'type': 1,
   'id': 6458,
   'country': 'FR',
   'sunrise': 1787634973,
   'sunset': 1787684263},
  'timezone': 7200,
  'id': 3006787,
  'name': 'La Rochelle',
  'cod': 200,
  'city': 'La Rochelle'},
 {'coord': {'lon': 0.108, 'lat': 49.4939},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'base': 'stations',
  'main': {'temp': 24.71,
   'feels_like': 24.7,
   'temp_min': 24.51,
   'temp_max': 28.9,
   'pressure': 1008,
   'humidity': 56,
   'sea_level': 1008,
   'grnd_level': 1006},
  'visibility': 8330,
  'wind': {'speed': 3.6, 'deg': 340},
  'clouds': {'all': 16},
  'dt': 1787668979,
  'sys': {'type': 1,
   'id': 6533,
   'country': 'FR',
   'sunrise': 1787634302,
   'sunset': 1787684330},
  'timezone': 7200,
  'id': 3003796,
  'name': 'Le Havre',
  'cod': 200,
  'city': 'Le Havre'},
 {'coord': {'lon': 1.3613, 'lat': 43.0795},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 27.97,
   'feels_like': 28.33,
   'temp_min': 26.74,
   'temp_max': 27.97,
   'pressure': 1013,
   'humidity': 49,
   'sea_level': 1013,
   'grnd_level': 959},
  'visibility': 10000,
  'wind': {'speed': 2.79, 'deg': 11, 'gust': 2.33},
  'clouds': {'all': 67},
  'dt': 1787668983,
  'sys': {'type': 2,
   'id': 20300,
   'country': 'FR',
   'sunrise': 1787634669,
   'sunset': 1787683361},
  'timezone': 7200,
  'id': 6446851,
  'name': 'Artigat',
  'cod': 200,
  'city': "Le Mas-d'Azil"},
 {'coord': {'lon': 3.0635, 'lat': 50.6366},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 24.12,
   'feels_like': 23.89,
   'temp_min': 22.77,
   'temp_max': 27.72,
   'pressure': 1011,
   'humidity': 50,
   'sea_level': 1011,
   'grnd_level': 1008},
  'visibility': 10000,
  'wind': {'speed': 5.14, 'deg': 70},
  'clouds': {'all': 87},
  'dt': 1787668855,
  'sys': {'type': 2,
   'id': 2011132,
   'country': 'FR',
   'sunrise': 1787633453,
   'sunset': 1787683760},
  'timezone': 7200,
  'id': 6454414,
  'name': 'Lille',
  'cod': 200,
  'city': 'Lille'},
 {'coord': {'lon': 4.832, 'lat': 45.7578},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'base': 'stations',
  'main': {'temp': 29.63,
   'feels_like': 29.72,
   'temp_min': 28.49,
   'temp_max': 30.28,
   'pressure': 1011,
   'humidity': 44,
   'sea_level': 1011,
   'grnd_level': 980},
  'visibility': 10000,
  'wind': {'speed': 2.06, 'deg': 170},
  'clouds': {'all': 74},
  'dt': 1787668743,
  'sys': {'type': 2,
   'id': 2108477,
   'country': 'FR',
   'sunrise': 1787633577,
   'sunset': 1787682788},
  'timezone': 7200,
  'id': 8015556,
  'name': 'Vieux Lyon',
  'cod': 200,
  'city': 'Lyon'},
 {'coord': {'lon': 5.382, 'lat': 43.3034},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'base': 'stations',
  'main': {'temp': 27.26,
   'feels_like': 29.21,
   'temp_min': 27.24,
   'temp_max': 31.77,
   'pressure': 1011,
   'humidity': 69,
   'sea_level': 1011,
   'grnd_level': 1004},
  'visibility': 10000,
  'wind': {'speed': 4.12, 'deg': 250},
  'clouds': {'all': 27},
  'dt': 1787668401,
  'sys': {'type': 2,
   'id': 80238,
   'country': 'FR',
   'sunrise': 1787633683,
   'sunset': 1787682418},
  'timezone': 7200,

# 2. Convert list to DataFrame

## cities dataframe convertion

In [16]:
# import pandas as pd

cities_df = pd.DataFrame(cities_info)

## weather normalization

In [17]:
weather_df = pd.json_normalize(weather_info)

In [18]:
type(cities_df)

pandas.core.frame.DataFrame

In [19]:
type(weather_df)

pandas.core.frame.DataFrame

In [20]:
cities_df.head(1)

            city  place_id        lat      lon
0  Aigues-Mortes  83121595  43.566152  4.19154

In [21]:
weather_df.head(1)

,weather,base,visibility,dt,timezone,id,name,cod,city,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,wind.gust
0,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1787668896,7200,3038493,Aigues-Mortes,200,Aigues-Mortes,4.1915,43.5662,27.29,28.21,26.98,31.56,1011,57,1011,1011,4.12,200,72,1.0,6518.0,FR,1787633944,1787682728,NaN

In [22]:
weather = pd.json_normalize(weather_df['weather'])

In [23]:
weather.head(1)

                                                   0
0  {'id': 803, 'main': 'Clouds', 'description': '...

In [24]:
weather2 = pd.json_normalize(weather.to_dict(orient="records"))
weather2 = weather2.add_prefix("data.")

In [25]:
weather2.head(1)

   data.0.id data.0.main data.0.description data.0.icon
0        803      Clouds      broken clouds         04d

In [26]:
weather_df = pd.concat(
    [weather_df.drop(columns="weather"),
     weather2],
     axis=1)

In [27]:
# pd.set_option('display.max_columns', None) # display each column's dataframe
weather_df.head(1)

,base,visibility,dt,timezone,id,name,cod,city,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,wind.gust,data.0.id,data.0.main,data.0.description,data.0.icon
0,stations,10000,1787668896,7200,3038493,Aigues-Mortes,200,Aigues-Mortes,4.1915,43.5662,27.29,28.21,26.98,31.56,1011,57,1011,1011,4.12,200,72,1.0,6518.0,FR,1787633944,1787682728,NaN,803,Clouds,broken clouds,04d

In [28]:
weather_df.columns

Index(['base', 'visibility', 'dt', 'timezone', 'id', 'name', 'cod', 'city',
       'coord.lon', 'coord.lat', 'main.temp', 'main.feels_like',
       'main.temp_min', 'main.temp_max', 'main.pressure', 'main.humidity',
       'main.sea_level', 'main.grnd_level', 'wind.speed', 'wind.deg',
       'clouds.all', 'sys.type', 'sys.id', 'sys.country', 'sys.sunrise',
       'sys.sunset', 'wind.gust', 'data.0.id', 'data.0.main',
       'data.0.description', 'data.0.icon'],
      dtype='object')

# 3. Merge DataFrames on 'city'

In [29]:
current_weather = pd.merge(cities_df, weather_df, on='city')

# Display key columns
print("\nCurrent weather:")
current_weather.head()

Current weather:

,city,place_id,lat,lon,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,wind.gust,data.0.id,data.0.main,data.0.description,data.0.icon
0,Aigues-Mortes,83121595,43.566152,4.191540,stations,10000,1787668896,7200,3038493,Aigues-Mortes,200,4.1915,43.5662,27.29,28.21,26.98,31.56,1011,57,1011,1011,4.12,200,72,1.0,6518.0,FR,1787633944,1787682728,NaN,803,Clouds,broken clouds,04d
1,Aix-en-Provence,82709709,43.529842,5.447474,stations,10000,1787668899,7200,3038354,Aix-en-Provence,200,5.4475,43.5298,30.51,33.83,28.71,30.78,1011,60,1011,979,1.79,281,42,2.0,2006832.0,FR,1787633646,1787682423,3.58,802,Clouds,scattered clouds,03d
2,Amiens,99515658,49.894171,2.295695,stations,10000,1787668521,7200,3037854,Amiens,200,2.3030,49.8917,25.46,25.21,25.46,25.46,1010,44,1010,1000,4.09,93,70,1.0,6446.0,FR,1787633727,1787683851,4.00,803,Clouds,broken clouds,04d
3,Annecy,88762115,45.899235,6.128885,stations,10000,1787668906,7200,3037543,Annecy,200,6.1289,45.8992,29.08,28.43,27.79,29.08,1012,37,1012,928,1.03,0,62,1.0,6500.0,FR,1787633251,1787682492,NaN,803,Clouds,broken clouds,04d
4,Avignon,82703601,43.949249,4.805901,stations,10000,1787668768,7200,3035681,Avignon,200,4.8100,43.9500,32.22,32.41,31.16,32.44,1011,39,1011,1004,1.54,0,51,1.0,6520.0,FR,1787633759,1787682616,NaN,803,Clouds,broken clouds,04d

In [30]:
current_weather.head(2)

,city,place_id,lat,lon,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,wind.gust,data.0.id,data.0.main,data.0.description,data.0.icon
0,Aigues-Mortes,83121595,43.566152,4.191540,stations,10000,1787668896,7200,3038493,Aigues-Mortes,200,4.1915,43.5662,27.29,28.21,26.98,31.56,1011,57,1011,1011,4.12,200,72,1.0,6518.0,FR,1787633944,1787682728,NaN,803,Clouds,broken clouds,04d
1,Aix-en-Provence,82709709,43.529842,5.447474,stations,10000,1787668899,7200,3038354,Aix-en-Provence,200,5.4475,43.5298,30.51,33.83,28.71,30.78,1011,60,1011,979,1.79,281,42,2.0,2006832.0,FR,1787633646,1787682423,3.58,802,Clouds,scattered clouds,03d

In [31]:
type(current_weather)

pandas.core.frame.DataFrame

In [32]:
print(current_weather.head())

              city  place_id        lat       lon      base  visibility  \
0    Aigues-Mortes  83121595  43.566152  4.191540  stations       10000
1  Aix-en-Provence  82709709  43.529842  5.447474  stations       10000
2           Amiens  99515658  49.894171  2.295695  stations       10000
3           Annecy  88762115  45.899235  6.128885  stations       10000
4          Avignon  82703601  43.949249  4.805901  stations       10000

           dt  timezone       id             name  cod  coord.lon  coord.lat  \
0  1787668896      7200  3038493    Aigues-Mortes  200     4.1915    43.5662
1  1787668899      7200  3038354  Aix-en-Provence  200     5.4475    43.5298
2  1787668521      7200  3037854           Amiens  200     2.3030    49.8917
3  1787668906      7200  3037543           Annecy  200     6.1289    45.8992
4  1787668768      7200  3035681          Avignon  200     4.8100    43.9500

   main.temp  main.feels_like  main.temp_min  main.temp_max  main.pressure  \
0      27.29            28.21          26.98          31.56           1011
1      30.51            33.83          28.71          30.78           1011
2      25.46            25.21          25.46          25.46           1010
3      29.08            28.43          27.79          29.08           1012
4      32.22            32.41          31.16          32.44           1011

   main.humidity  main.sea_level  main.grnd_level  wind.speed  wind.deg  \
0             57            1011             1011        4.12       200
1             60            1011              979        1.79       281
2             44            1010             1000        4.09        93
3             37            1012              928        1.03         0
4             39            1011             1004        1.54         0

   clouds.all  sys.type     sys.id sys.country  sys.sunrise  sys.sunset  \
0          72       1.0     6518.0          FR   1787633944  1787682728
1          42       2.0  2006832.0          FR   1787633646  1787682423
2          70       1.0     6446.0          FR   1787633727  1787683851
3          62       1.0     6500.0          FR   1787633251  1787682492
4          51       1.0     6520.0          FR   1787633759  1787682616

   wind.gust  data.0.id data.0.main data.0.description data.0.icon
0        NaN        803      Clouds      broken clouds         04d
1       3.58        802      Clouds   scattered clouds         03d
2       4.00        803      Clouds      broken clouds         04d
3        NaN        803      Clouds      broken clouds         04d
4        NaN        803      Clouds      broken clouds         04d