In [1]:
import requests
import pandas as pd
from unidecode import unidecode
import time
from get_cities import get_city_info

In [24]:
#df = get_city_info("France")
df = pd.read_csv("data/cities.csv")
API_KEY = "95f5ed4b5991c2bd754589456f14cc16"

url = "https://api.openweathermap.org/data/2.5/weather"

rows = []
for _, row in df.iterrows():
    params = {
        "lat": row["lat"],
        "lon": row["lon"],
        "units": "metric",
        "appid": "95f5ed4b5991c2bd754589456f14cc16",
        "lang": "fr"
    }
    response = requests.get(url, params=params)
    # print(row, response.status_code) # check if the call is successful

    payload = response.json()
    # payload["name_city"] = row["name"]

    rows.append(payload)

    time.sleep(1)

df_rows = pd.DataFrame(rows)
print(df_rows)

                               coord  \
0    {'lon': -1.5115, 'lat': 48.636}
1    {'lon': -2.026, 'lat': 48.6495}
2   {'lon': -0.7025, 'lat': 49.2765}
3    {'lon': 0.1079, 'lat': 49.4944}
4     {'lon': 1.089, 'lat': 49.4352}
5      {'lon': 2.32, 'lat': 48.8589}
6    {'lon': 2.2957, 'lat': 49.8942}
7    {'lon': 3.0635, 'lat': 50.6366}
8    {'lon': 7.7505, 'lat': 48.5776}
9      {'lon': 7.38, 'lat': 48.2422}
10   {'lon': 7.3559, 'lat': 48.0812}
11    {'lon': 7.308, 'lat': 48.0448}
12   {'lon': 6.0199, 'lat': 47.2443}
13   {'lon': 5.0407, 'lat': 47.3206}
14   {'lon': 6.1323, 'lat': 45.9008}
15   {'lon': 5.7358, 'lat': 45.1876}
16    {'lon': 4.832, 'lat': 45.7578}
17   {'lon': 6.0057, 'lat': 43.5581}
18   {'lon': 6.5134, 'lat': 43.8465}
19   {'lon': 6.1503, 'lat': 43.5281}
20   {'lon': 6.2215, 'lat': 43.8459}
21   {'lon': 6.1518, 'lat': 43.7589}
22   {'lon': 6.1795, 'lat': 43.5674}
23    {'lon': 5.984, 'lat': 43.8379}
24   {'lon': 6.3419, 'lat': 43.1507}
25    {'lon': 5.5396, 'lat': 43.214}
26   {'lon': 5.3778, 'lat': 43.2964}
27   {'lon': 5.4475, 'lat': 43.5298}
28   {'lon': 4.8059, 'lat': 43.9492}
29   {'lon': 4.4197, 'lat': 44.0121}
30   {'lon': 4.3616, 'lat': 43.8387}
31   {'lon': 4.1915, 'lat': 43.5662}
32   {'lon': 4.4277, 'lat': 43.4516}
33   {'lon': 3.0832, 'lat': 42.5251}
34    {'lon': 2.3491, 'lat': 43.213}
35   {'lon': 1.5675, 'lat': 42.8816}
36   {'lon': 2.3447, 'lat': 49.8874}
37     {'lon': 1.3936, 'lat': 43.15}
38   {'lon': 1.6054, 'lat': 42.9639}
39   {'lon': 1.3613, 'lat': 43.0795}
40   {'lon': 0.6719, 'lat': 43.7458}
41   {'lon': 1.8337, 'lat': 42.8708}
42   {'lon': 1.5911, 'lat': 42.8093}
43   {'lon': 1.1355, 'lat': 43.0025}
44   {'lon': 1.4955, 'lat': 43.1697}
45   {'lon': 1.6043, 'lat': 42.8492}
46   {'lon': 1.4442, 'lat': 43.6045}
47    {'lon': 1.355, 'lat': 44.0176}
48  {'lon': -1.5527, 'lat': 43.4711}
49  {'lon': -1.4737, 'lat': 43.4945}
50  {'lon': -1.1497, 'lat': 46.1616}

                                              weather      base  \
0   [{'id': 804, 'main': 'Clouds', 'description': ...  stations
1   [{'id': 804, 'main': 'Clouds', 'description': ...  stations
2   [{'id': 804, 'main': 'Clouds', 'description': ...  stations
3   [{'id': 804, 'main': 'Clouds', 'description': ...  stations
4   [{'id': 804, 'main': 'Clouds', 'description': ...  stations
5   [{'id': 804, 'main': 'Clouds', 'description': ...  stations
6   [{'id': 804, 'main': 'Clouds', 'description': ...  stations
7   [{'id': 500, 'main': 'Rain', 'description': 'l...  stations
8   [{'id': 500, 'main': 'Rain', 'description': 'l...  stations
9   [{'id': 804, 'main': 'Clouds', 'description': ...  stations
10  [{'id': 804, 'main': 'Clouds', 'description': ...  stations
11  [{'id': 804, 'main': 'Clouds', 'description': ...  stations
12  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
13  [{'id': 802, 'main': 'Clouds', 'description': ...  stations
14  [{'id': 804, 'main': 'Clouds', 'description': ...  stations
15  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
16  [{'id': 802, 'main': 'Clouds', 'description': ...  stations
17  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
18  [{'id': 802, 'main': 'Clouds', 'description': ...  stations
19  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
20  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
21  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
22  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
23  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
24  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
25  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
26  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
27  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
28  [{'id': 804, 'main': 'Clouds', 'description': ...  stations
29  [{'id': 804, 'main': 'Clouds', 'description': ...  stations
30  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
31  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
32  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
33  [{'id': 804, 'main': 'Clouds', 'description': ...  stations
34  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
35  [{'id': 501, 'main': 'Rain', 'description': 'p...  stations
36  [{'id': 804, 'main': 'Clouds', 'description': ...  stations
37  [{'id': 503, 'main': 'Rain', 'description': 't...  stations
38  [{'id': 501, 'main': 'Rain', 'description': 'p...  stations
39  [{'id': 502, 'main': 'Rain', 'description': 'f...  stations
40  [{'id': 500, 'main': 'Rain', 'description': 'l...  stations
41  [{'id': 802, 'main': 'Clouds', 'description': ...  stations
42  [{'id': 500, 'main': 'Rain', 'description': 'l...  stations
43  [{'id': 502, 'main': 'Rain', 'description': 'f...  stations
44  [{'id': 503, 'main': 'Rain', 'description': 't...  stations
45  [{'id': 500, 'main': 'Rain', 'description': 'l...  stations
46  [{'id': 501, 'main': 'Rain', 'description': 'p...  stations
47  [{'id': 801, 'main': 'Clouds', 'description': ...  stations
48  [{'id': 803, 'main': 'Clouds', 'description': ...  stations
49  [{'id': 804, 'main': 'Clouds', 'description': ...  stations
50  [{'id': 804, 'main': 'Clouds', 'description': ...  stations

                                                 main  visibility  \
0   {'temp': 25.41, 'feels_like': 24.95, 'temp_min...     10000.0
1   {'temp': 27.29, 'feels_like': 27.03, 'temp_min...     10000.0
2   {'temp': 26.14, 'feels_like': 26.14, 'temp_min...     10000.0
3   {'temp': 24.59, 'feels_like': 24.07, 'temp_min...     10000.0
4   {'temp': 25.9, 'feels_like': 25.54, 'temp_min'...     10000.0
5   {'temp': 25.61, 'feels_like': 25.22, 'temp_min...     10000.0
6   {'temp': 24.13, 'feels_like': 23.7, 'temp_min'...     10000.0
7   {'temp': 22.42, 'feels_like': 22.02, 'temp_min...     10000.0
8   {'temp': 20.03, 'feels_like': 19.86, 'temp_min...     10000.0
9   {'temp': 21.54, 'feels_like': 21.03, 'temp_min...     10000.0
10  {'temp': 22.05, 'feels_like': 21.69, 'temp_min...     10000.0
11  {'temp': 22.14, 'feels_like': 21.79, 'temp_min...     10000.0
12  {'temp': 28.12, 'feels_like': 28.15, 'temp_min...     10000.0
13  {'temp': 26.8, 'feels_like': 26.67, 'temp_min'...     10000.0
14  {'temp': 29.08, 'feels_like': 28.88, 'temp_min...     10000.0
15  {'temp': 31.54, 'feels_like': 31.63, 'temp_min...     10000.0
16  {'temp': 32.26, 'feels_like': 31, 'temp_min': ...     10000.0
17  {'temp': 29.53, 'feels_like': 29.6, 'temp_min'...     10000.0
18  {'temp': 25.02, 'feels_like': 24.94, 'temp_min...     10000.0
19  {'temp': 29.78, 'feels_like': 30.16, 'temp_min...     10000.0
20  {'temp': 25.49, 'feels_like': 25.37, 'temp_min...     10000.0
21  {'temp': 27.94, 'feels_like': 28.21, 'temp_min...     10000.0
22  {'temp': 29.01, 'feels_like': 29.21, 'temp_min...     10000.0
23  {'temp': 27.82, 'feels_like': 27.93, 'temp_min...     10000.0
24  {'temp': 28.82, 'feels_like': 30.59, 'temp_min...     10000.0
25  {'temp': 29.29, 'feels_like': 30.31, 'temp_min...     10000.0
26  {'temp': 30.74, 'feels_like': 30.32, 'temp_min...     10000.0
27  {'temp': 32.34, 'feels_like': 31.33, 'temp_min...     10000.0
28  {'temp': 34.03, 'feels_like': 33.5, 'temp_min'...     10000.0
29  {'temp': 31.78, 'feels_like': 31.48, 'temp_min...     10000.0
30  {'temp': 31.25, 'feels_like': 30.31, 'temp_min...     10000.0
31  {'temp': 26.98, 'feels_like': 29.51, 'temp_min...     10000.0
32  {'temp': 24.88, 'feels_like': 25.56, 'temp_min...     10000.0
33  {'temp': 28.52, 'feels_like': 30.8, 'temp_min'...     10000.0
34  {'temp': 29.06, 'feels_like': 31.29, 'temp_min...     10000.0
35  {'temp': 30.09, 'feels_like': 31.02, 'temp_min...     10000.0
36  {'temp': 22.51, 'feels_like': 21.91, 'temp_min...     10000.0
37  {'temp': 28.37, 'feels_like': 29.89, 'temp_min...     10000.0
38  {'temp': 33.02, 'feels_like': 36.05, 'temp_min...     10000.0
39  {'temp': 33.77, 'feels_like': 40.77, 'temp_min...     10000.0
40  {'temp': 28.34, 'feels_like': 27.4, 'temp_min'...         NaN
41  {'temp': 30.37, 'feels_like': 30.39, 'temp_min...     10000.0
42  {'temp': 31.89, 'feels_like': 33.93, 'temp_min...     10000.0
43  {'temp': 27.72, 'feels_like': 29.15, 'temp_min...     10000.0
44  {'temp': 33.85, 'feels_like': 40.85, 'temp_min...     10000.0
45  {'temp': 32.56, 'feels_like': 35.16, 'temp_min...     10000.0
46  {'temp': 28.97, 'feels_like': 30.69, 'temp_min...     10000.0
47  {'temp': 29.74, 'feels_like': 30.97, 'temp_min...     10000.0
48  {'temp': 28, 'feels_like': 28.54, 'temp_min': ...     10000.0
49  {'temp': 28.42, 'feels_like': 29.04, 'temp_min...     10000.0
50  {'temp': 25.06, 'feels_like': 25.42, 'temp_min...     10000.0

                                           wind        clouds          dt  \
0       {'speed': 6.25, 'deg': 95, 'gust': 7.4}   {'all': 97}  1787581529
1                    {'speed': 6.69, 'deg': 70}   {'all': 91}  1787581530
2      {'speed': 8.4, 'deg': 53, 'gust': 10.21}  {'all': 100}  1787581531
3                    {'speed': 8.75, 'deg': 70}   {'all': 97}  1787580985
4                     {'speed': 7.2, 'deg': 70}  {'all': 100}  1787581254
5                    {'speed': 5.66, 'deg': 80}   {'all': 98}  1787581534
6      {'speed': 6.71, 'deg': 85, 'gust': 7.86}  {'all': 100}  1787581535
7                    {'speed': 6.17, 'deg': 70}  {'all': 100}  1787581536
8                   {'speed': 5.14, 'deg': 350}   {'all': 97}  1787581208
9                    {'speed': 4.12, 'deg': 30}  {'all': 100}  1787581539
10      {'speed': 7.4, 'deg': 39, 'gust': 12.5}  {'all': 100}  1787581527
11      {'speed': 7.4, 'deg': 39, 'gust': 12.5}  {'all': 100}  1787581541
12      {'speed': 1.1, 'deg': 328, 'gust': 3.1}   {'all': 71}  1787581523
13                   {'speed': 3.09, 'deg': 70}   {'all': 39}  1787581514
14                  {'speed': 2.06, 'deg': 340}   {'all': 85}  1787581134
15    {'speed': 4.47, 'deg': 211, 'gust': 8.49}   {'all': 55}  1787581302
16                  {'speed': 8.75, 'deg': 170}   {'all': 48}  1787581379
17      {'speed': 4.7, 'deg': 292, 'gust': 7.4}   {'all': 80}  1787581547
18     {'speed': 4.2, 'deg': 153, 'gust': 4.48}   {'all': 28}  1787581548
19    {'speed': 6.13, 'deg': 135, 'gust': 7.03}   {'all': 65}  1787581549
20    {'speed': 5.95, 'deg': 164, 'gust': 6.33}   {'all': 54}  1787581100
21    {'speed': 6.48, 'deg': 158, 'gust': 7.29}   {'all': 54}  1787581552
22    {'speed': 6.05, 'deg': 138, 'gust': 7.01}   {'all': 61}  1787581553
23    {'speed': 7.51, 'deg': 162, 'gust': 7.88}   {'all': 55}  1787581554
24    {'speed': 3.58, 'deg': 103, 'gust': 8.49}   {'all': 56}  1787581555
25    {'speed': 0.89, 'deg': 136, 'gust': 3.58}   {'all': 71}  1787581556
26     {'speed': 3.58, 'deg': 164, 'gust': 7.6}   {'all': 60}  1787581557
27    {'speed': 3.13, 'deg': 182, 'gust': 5.81}   {'all': 52}  1787581558
28                  {'speed': 8.75, 'deg': 170}   {'all': 86}  1787581559
29  {'speed': 10.31, 'deg': 178, 'gust': 12.07}   {'all': 94}  1787581560
30                  {'speed': 10.8, 'deg': 160}   {'all': 80}  1787581514
31                   {'speed': 7.2, 'deg': 130}   {'all': 81}  1787581562
32    {'speed': 9.16, 'deg': 153, 'gust': 13.3}   {'all': 82}  1787581563
33      {'speed': 7.77, 'deg': 182, 'gust': 13}   {'all': 99}  1787581565
34   {'speed': 11.83, 'deg': 70, 'gust': 18.01}   {'all': 51}  1787581566
35    {'speed': 5.18, 'deg': 226, 'gust': 7.66}    {'all': 2}  1787581567
36     {'speed': 6.68, 'deg': 85, 'gust': 7.85}  {'all': 100}  1787581568
37    {'speed': 1.12, 'deg': 189, 'gust': 4.56}   {'all': 45}  1787581569
38    {'speed': 5.48, 'deg': 235, 'gust': 7.02}   {'all': 18}  1787581570
39     {'speed': 2.17, 'deg': 209, 'gust': 4.3}   {'all': 39}  1787581571
40    {'speed': 2.26, 'deg': 115, 'gust': 4.06}   {'all': 12}  1787581572
41    {'speed': 4.64, 'deg': 245, 'gust': 6.08}   {'all': 25}  1787581573
42    {'speed': 4.65, 'deg': 221, 'gust': 7.83}    {'all': 0}  1787581574
43    {'speed': 3.39, 'deg': 199, 'gust': 5.09}   {'all': 33}  1787581575
44    {'speed': 0.93, 'deg': 183, 'gust': 4.81}   {'all': 49}  1787581577
45    {'speed': 4.94, 'deg': 225, 'gust': 7.72}    {'all': 0}  1787581578
46                  {'speed': 5.14, 'deg': 150}   {'all': 30}  1787580962
47    {'speed': 8.61, 'deg': 148, 'gust': 8.92}   {'all': 12}  1787581466
48                  {'speed': 5.66, 'deg': 330}   {'all': 82}  1787581581
49                  {'speed': 5.66, 'deg': 330}   {'all': 99}  1787581496
50                   {'speed': 8.23, 'deg': 50}   {'all': 85}  1787581208

                                                  sys  timezone       id  \
0   {'country': 'FR', 'sunrise': 1787548306, 'suns...      7200  6435453
1   {'type': 1, 'id': 6557, 'country': 'FR', 'sunr...      7200  2978640
2   {'type': 1, 'id': 6569, 'country': 'FR', 'sunr...      7200  3034483
3   {'type': 1, 'id': 6533, 'country': 'FR', 'sunr...      7200  3003796
4   {'type': 2, 'id': 2003589, 'country': 'FR', 's...      7200  2982652
5   {'type': 2, 'id': 2012208, 'country': 'FR', 's...      7200  6545270
6   {'country': 'FR', 'sunrise': 1787547239, 'suns...      7200  3037854
7   {'type': 2, 'id': 2011132, 'country': 'FR', 's...      7200  6454414
8   {'type': 1, 'id': 6595, 'country': 'FR', 'sunr...      7200  2973781
9   {'type': 1, 'id': 6482, 'country': 'FR', 'sunr...      7200  6441605
10  {'type': 1, 'id': 6482, 'country': 'FR', 'sunr...      7200  3024297
11  {'type': 5, 'id': 50014460, 'country': 'FR', '...      7200  3020324
12  {'type': 5, 'id': 50014141, 'country': 'FR', '...      7200  3033123
13  {'type': 1, 'id': 6586, 'country': 'FR', 'sunr...      7200  3006622
14  {'type': 1, 'id': 6500, 'country': 'FR', 'sunr...      7200  3037543
15  {'type': 2, 'id': 2004515, 'country': 'FR', 's...      7200  6454071
16  {'type': 2, 'id': 2108477, 'country': 'FR', 's...      7200  8015556
17  {'type': 5, 'id': 50014318, 'country': 'FR', '...      7200  3034918
18  {'country': 'FR', 'sunrise': 1787546892, 'suns...      7200  3028382
19  {'type': 2, 'id': 2006427, 'country': 'FR', 's...      7200  3023410
20  {'country': 'FR', 'sunrise': 1787546962, 'suns...      7200  2996533
21  {'type': 5, 'id': 50014318, 'country': 'FR', '...      7200  3034556
22  {'type': 2, 'id': 2006427, 'country': 'FR', 's...      7200  2976472
23  {'country': 'FR', 'sunrise': 1787547020, 'suns...      7200  2971033
24  {'type': 2, 'id': 2006377, 'country': 'FR', 's...      7200  3031532
25  {'type': 2, 'id': 2012554, 'country': 'FR', 's...      7200  3028431
26  {'type': 2, 'id': 80238, 'country': 'FR', 'sun...      7200  2995469
27  {'type': 2, 'id': 2006832, 'country': 'FR', 's...      7200  3038354
28  {'type': 1, 'id': 6520, 'country': 'FR', 'sunr...      7200  3035681
29  {'type': 2, 'id': 2024181, 'country': 'FR', 's...      7200  2971258
30  {'type': 1, 'id': 6599, 'country': 'FR', 'sunr...      7200  2990363
31  {'type': 1, 'id': 6518, 'country': 'FR', 'sunr...      7200  3038493
32  {'country': 'FR', 'sunrise': 1787547431, 'suns...      7200  2980325
33  {'type': 2, 'id': 2020519, 'country': 'FR', 's...      7200  3024314
34  {'type': 1, 'id': 6513, 'country': 'FR', 'sunr...      7200  3028641
35  {'type': 2, 'id': 2092354, 'country': 'FR', 's...      7200  6426331
36  {'type': 1, 'id': 6446, 'country': 'FR', 'sunr...      7200  3029003
37  {'country': 'FR', 'sunrise': 1787548189, 'suns...      7200  6446851
38  {'type': 2, 'id': 2092354, 'country': 'FR', 's...      7200  3018174
39  {'type': 2, 'id': 2092354, 'country': 'FR', 's...      7200  6446851
40  {'type': 2, 'id': 2031069, 'country': 'FR', 's...      7200  6432068
41  {'type': 2, 'id': 2001435, 'country': 'FR', 's...      7200  3005712
42  {'type': 2, 'id': 2092354, 'country': 'FR', 's...      7200  3018172
43  {'country': 'FR', 'sunrise': 1787548265, 'suns...      7200  2978760
44  {'type': 2, 'id': 2092354, 'country': 'FR', 's...      7200  3036674
45  {'type': 2, 'id': 2092354, 'country': 'FR', 's...      7200  6426331
46  {'type': 1, 'id': 6467, 'country': 'FR', 'sunr...      7200  2972315
47  {'country': 'FR', 'sunrise': 1787548114, 'suns...      7200  2993002
48  {'type': 1, 'id': 6478, 'country': 'FR', 'sunr...      7200  3007799
49  {'type': 1, 'id': 6478, 'country': 'FR', 'sunr...      7200  3034475
50  {'type': 1, 'id': 6458, 'country': 'FR', 'sunr...      7200  3006787

                        name  cod           rain
0            Huisnes-sur-Mer  200            NaN
1                 Saint-Malo  200            NaN
2                     Bayeux  200            NaN
3             Havre-de-Grâce  200            NaN
4                      Rouen  200            NaN
5   Quartier du Palais-Royal  200            NaN
6                     Amiens  200            NaN
7                      Lille  200   {'1h': 0.38}
8                 Strasbourg  200   {'1h': 0.42}
9            Saint-Hippolyte  200            NaN
10                    Colmar  200            NaN
11                 Eguisheim  200            NaN
12                  Besançon  200            NaN
13                    Larrey  200            NaN
14                    Annecy  200            NaN
15                  Grenoble  200            NaN
16                Vieux Lyon  200            NaN
17                   Barjols  200            NaN
18                Castellane  200            NaN
19                  Cotignac  200            NaN
20                 Majastres  200            NaN
21                   Bauduen  200            NaN
22                  Salernes  200            NaN
23                 Valensole  200            NaN
24        Bormes-les-Mimosas  200            NaN
25                    Cassis  200            NaN
26                 Marseille  200            NaN
27           Aix-en-Provence  200            NaN
28                   Avignon  200            NaN
29                      Uzès  200            NaN
30                     Nîmes  200            NaN
31             Aigues-Mortes  200            NaN
32  Saintes-Maries-de-la-Mer  200            NaN
33                 Collioure  200            NaN
34               Carcassonne  200            NaN
35       Tarascon-sur-Ariège  200    {'1h': 1.7}
36                     Camon  200            NaN
37                   Artigat  200   {'1h': 16.2}
38                      Foix  200   {'1h': 1.54}
39                   Artigat  200   {'1h': 12.3}
40                  Preignan  200   {'1h': 0.66}
41                 Lavelanet  200            NaN
42                      Foix  200      {'1h': 1}
43              Saint-Lizier  200   {'1h': 5.62}
44                   Artigat  200  {'1h': 22.49}
45       Tarascon-sur-Ariège  200   {'1h': 0.96}
46                  Toulouse  200   {'1h': 3.26}
47                 Montauban  200            NaN
48               La Négresse  200            NaN
49                   Bayonne  200            NaN
50               La Rochelle  200            NaN

In [3]:
display(df_rows.head())

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod,name_city,rain
0,"{'lon': -1.5115, 'lat': 48.636}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 25.72, 'feels_like': 25.21, 'temp_min...",10000.0,"{'speed': 6.25, 'deg': 95, 'gust': 7.4}",{'all': 97},1787579129,"{'country': 'FR', 'sunrise': 1787548306, 'suns...",7200,6435453,Huisnes-sur-Mer,200,Mont Saint Michel,NaN
1,"{'lon': -2.026, 'lat': 48.6495}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.29, 'feels_like': 26.87, 'temp_min...",10000.0,"{'speed': 5.66, 'deg': 60}",{'all': 91},1787579130,"{'type': 1, 'id': 6557, 'country': 'FR', 'sunr...",7200,2978640,Saint-Malo,200,Saint Malo,NaN
2,"{'lon': -0.7025, 'lat': 49.2765}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 25.14, 'feels_like': 24.75, 'temp_min...",10000.0,"{'speed': 8.4, 'deg': 53, 'gust': 10.21}",{'all': 100},1787579131,"{'type': 1, 'id': 6569, 'country': 'FR', 'sunr...",7200,3034483,Bayeux,200,Bayeux,NaN
3,"{'lon': 0.108, 'lat': 49.4939}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 24.56, 'feels_like': 24.04, 'temp_min...",10000.0,"{'speed': 8.75, 'deg': 80}",{'all': 97},1787579120,"{'type': 1, 'id': 6533, 'country': 'FR', 'sunr...",7200,3003796,Havre-de-Grâce,200,Le Havre,NaN
4,"{'lon': 1.094, 'lat': 49.4405}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 25.08, 'feels_like': 24.64, 'temp_min...",10000.0,"{'speed': 7.72, 'deg': 80}",{'all': 100},1787579134,"{'type': 2, 'id': 2003589, 'country': 'FR', 's...",7200,6454707,Rouen,200,Rouen,NaN

In [17]:
# Applatissement général du JSON pour obtenir un DataFrame plus lisible
df_weather = pd.json_normalize(rows)

In [18]:
display(df_weather.head())

,weather,base,visibility,dt,timezone,id,name,cod,name_city,coord.lon,...,wind.speed,wind.deg,wind.gust,clouds.all,sys.country,sys.sunrise,sys.sunset,sys.type,sys.id,rain.1h
0,"[{'id': 804, 'main': 'Clouds', 'description': ...",stations,10000.0,1787579129,7200,6435453,Huisnes-sur-Mer,200,Mont Saint Michel,-1.5115,...,6.25,95,7.40,97,FR,1787548306,1787598335,NaN,NaN,NaN
1,"[{'id': 804, 'main': 'Clouds', 'description': ...",stations,10000.0,1787579130,7200,2978640,Saint-Malo,200,Saint Malo,-2.0260,...,5.66,60,NaN,91,FR,1787548428,1787598459,1.0,6557.0,NaN
2,"[{'id': 804, 'main': 'Clouds', 'description': ...",stations,10000.0,1787579131,7200,3034483,Bayeux,200,Bayeux,-0.7025,...,8.40,53,10.21,100,FR,1787548035,1787598217,1.0,6569.0,NaN
3,"[{'id': 804, 'main': 'Clouds', 'description': ...",stations,10000.0,1787579120,7200,3003796,Havre-de-Grâce,200,Le Havre,0.1080,...,8.75,80,NaN,97,FR,1787547814,1787598049,1.0,6533.0,NaN
4,"[{'id': 804, 'main': 'Clouds', 'description': ...",stations,10000.0,1787579134,7200,6454707,Rouen,200,Rouen,1.0940,...,7.72,80,NaN,100,FR,1787547584,1787597807,2.0,2003589.0,NaN

In [19]:
weather = pd.json_normalize(df_rows["weather"])
final_weather = pd.json_normalize(weather.to_dict(orient="records"))

In [20]:
final_weather = final_weather.add_prefix("weather.")

In [21]:
display(final_weather.head())

   weather.0.id weather.0.main weather.0.description weather.0.icon
0           804         Clouds               couvert            04d
1           804         Clouds               couvert            04d
2           804         Clouds               couvert            04d
3           804         Clouds               couvert            04d
4           804         Clouds               couvert            04d

In [22]:
df_weather = pd.concat(
    [
        df_weather.drop(columns="weather"),
        final_weather
    ],
    axis=1
)
display(df_weather)

,base,visibility,dt,timezone,id,name,cod,name_city,coord.lon,coord.lat,...,sys.country,sys.sunrise,sys.sunset,sys.type,sys.id,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon
0,stations,10000.0,1787579129,7200,6435453,Huisnes-sur-Mer,200,Mont Saint Michel,-1.5115,48.6360,...,FR,1787548306,1787598335,NaN,NaN,NaN,804,Clouds,couvert,04d
1,stations,10000.0,1787579130,7200,2978640,Saint-Malo,200,Saint Malo,-2.0260,48.6495,...,FR,1787548428,1787598459,1.0,6557.0,NaN,804,Clouds,couvert,04d
2,stations,10000.0,1787579131,7200,3034483,Bayeux,200,Bayeux,-0.7025,49.2765,...,FR,1787548035,1787598217,1.0,6569.0,NaN,804,Clouds,couvert,04d
3,stations,10000.0,1787579120,7200,3003796,Havre-de-Grâce,200,Le Havre,0.1080,49.4939,...,FR,1787547814,1787598049,1.0,6533.0,NaN,804,Clouds,couvert,04d
4,stations,10000.0,1787579134,7200,6454707,Rouen,200,Rouen,1.0940,49.4405,...,FR,1787547584,1787597807,2.0,2003589.0,NaN,804,Clouds,couvert,04d
5,stations,10000.0,1787579041,7200,6545270,Quartier du Palais-Royal,200,Paris,2.3200,48.8589,...,FR,1787547359,1787597443,5.0,50014441.0,NaN,804,Clouds,couvert,04d
6,stations,10000.0,1787578991,7200,3037854,Amiens,200,Amiens,2.2957,49.8942,...,FR,1787547239,1787597574,NaN,NaN,NaN,804,Clouds,couvert,04d
7,stations,10000.0,1787579043,7200,6454414,Lille,200,Lille,3.0635,50.6366,...,FR,1787546961,1787597484,2.0,2011132.0,0.14,500,Rain,légère pluie,10d
8,stations,10000.0,1787579138,7200,2973781,Strasbourg,200,Strasbourg,7.7507,48.5846,...,FR,1787546087,1787596109,1.0,6595.0,2.61,501,Rain,pluie modérée,10d
9,stations,10000.0,1787579139,7200,6441605,Saint-Hippolyte,200,Orschwiller,7.3800,48.2422,...,FR,1787546216,1787596157,1.0,6482.0,NaN,804,Clouds,couvert,04d
10,stations,10000.0,1787579140,7200,3024297,Colmar,200,Colmar,7.3580,48.0778,...,FR,1787546241,1787596144,1.0,6482.0,NaN,804,Clouds,couvert,04d
11,stations,10000.0,1787579141,7200,3020324,Eguisheim,200,Eguisheim,7.3080,48.0448,...,FR,1787546256,1787596152,5.0,50014460.0,NaN,804,Clouds,couvert,04d
12,stations,10000.0,1787578993,7200,3033123,Besançon,200,Besancon,6.0244,47.2380,...,FR,1787546656,1787596368,5.0,50014141.0,NaN,803,Clouds,nuageux,04d
13,stations,10000.0,1787579044,7200,3006622,Larrey,200,Dijon,5.0415,47.3216,...,FR,1787546883,1787596613,1.0,6586.0,NaN,802,Clouds,partiellement nuageux,03d
14,stations,10000.0,1787579486,7200,3037543,Annecy,200,Annecy,6.1323,45.9008,...,FR,1787546775,1787596198,1.0,6500.0,NaN,804,Clouds,couvert,04d
15,stations,10000.0,1787579146,7200,6454071,Grenoble,200,Grenoble,5.7358,45.1876,...,FR,1787546944,1787596218,2.0,2004515.0,NaN,803,Clouds,nuageux,04d
16,stations,10000.0,1787579504,7200,8015556,Vieux Lyon,200,Lyon,4.8320,45.7578,...,FR,1787547102,1787596494,2.0,2101774.0,NaN,802,Clouds,partiellement nuageux,03d
17,stations,10000.0,1787579008,7200,3034918,Barjols,200,Barjols,6.0057,43.5581,...,FR,1787547042,1787595991,5.0,50014318.0,NaN,803,Clouds,nuageux,04d
18,stations,10000.0,1787579149,7200,3028382,Castellane,200,Castellane,6.5134,43.8465,...,FR,1787546892,1787595898,NaN,NaN,NaN,802,Clouds,partiellement nuageux,03d
19,stations,10000.0,1787579150,7200,3023410,Cotignac,200,Cotignac,6.1503,43.5281,...,FR,1787547010,1787595954,2.0,2006427.0,NaN,803,Clouds,nuageux,04d
20,stations,10000.0,1787579583,7200,2996533,Majastres,200,Moustiers Sainte Marie,6.2218,43.8460,...,FR,1787546962,1787595968,NaN,NaN,NaN,803,Clouds,nuageux,04d
21,stations,10000.0,1787579153,7200,3034556,Bauduen,200,Sainte Croix du Verdon,6.1518,43.7589,...,FR,1787546987,1787595976,5.0,50014318.0,NaN,803,Clouds,nuageux,04d
22,stations,10000.0,1787579154,7200,2976472,Salernes,200,Sillans la Cascade,6.1795,43.5674,...,FR,1787546999,1787595951,2.0,2006427.0,NaN,803,Clouds,nuageux,04d
23,stations,10000.0,1787579155,7200,2971033,Valensole,200,Valensole,5.9840,43.8379,...,FR,1787547020,1787596024,NaN,NaN,NaN,803,Clouds,nuageux,04d
24,stations,10000.0,1787579156,7200,3031532,Bormes-les-Mimosas,200,Bormes les Mimosas,6.3419,43.1507,...,FR,1787547000,1787595872,2.0,2006377.0,NaN,803,Clouds,nuageux,04d
25,stations,10000.0,1787579157,7200,3028431,Cassis,200,Cassis,5.5396,43.2140,...,FR,1787547187,1787596070,2.0,2012554.0,NaN,803,Clouds,nuageux,04d
26,stations,10000.0,1787579158,7200,2995469,Marseille,200,Marseille,5.3778,43.2964,...,FR,1787547218,1787596117,2.0,80238.0,NaN,803,Clouds,nuageux,04d
27,stations,10000.0,1787579159,7200,3038354,Aix-en-Provence,200,Aix en Provence,5.4475,43.5298,...,FR,1787547179,1787596122,2.0,2006832.0,NaN,803,Clouds,nuageux,04d
28,stations,10000.0,1787579160,7200,3035681,Avignon,200,Avignon,4.8059,43.9492,...,FR,1787547292,1787596317,2.0,2024181.0,NaN,804,Clouds,couvert,04d
29,stations,10000.0,1787579161,7200,2971258,Uzès,200,Uzes,4.4197,44.0121,...,FR,1787547379,1787596416,2.0,2024181.0,NaN,804,Clouds,couvert,04d
30,stations,10000.0,1787579163,7200,2990363,Nîmes,200,Nimes,4.3601,43.8374,...,FR,1787547410,1787596413,1.0,6599.0,NaN,803,Clouds,nuageux,04d
31,stations,10000.0,1787579164,7200,3038493,Aigues-Mortes,200,Aigues Mortes,4.1915,43.5662,...,FR,1787547477,1787596427,1.0,6518.0,NaN,803,Clouds,nuageux,04d
32,stations,10000.0,1787579165,7200,2980325,Saintes-Maries-de-la-Mer,200,Saintes Maries de la Mer,4.4277,43.4516,...,FR,1787547431,1787596359,NaN,NaN,NaN,803,Clouds,nuageux,04d
33,stations,10000.0,1787579166,7200,3024314,Collioure,200,Collioure,3.0832,42.5251,...,FR,1787547842,1787596594,2.0,2020519.0,NaN,804,Clouds,couvert,04d
34,stations,10000.0,1787579167,7200,3028641,Carcassonne,200,Carcassonne,2.3491,43.2130,...,FR,1787547953,1787596835,1.0,6513.0,NaN,803,Clouds,nuageux,04d
35,stations,10000.0,1787579168,7200,6426331,Tarascon-sur-Ariège,200,Bedeilhac et Aynat,1.5675,42.8816,...,FR,1787548172,1787596991,2.0,2092354.0,8.65,502,Rain,forte pluie,10d
36,stations,10000.0,1787579169,7200,3029003,Camon,200,Camon,2.3447,49.8874,...,FR,1787547228,1787597562,1.0,6446.0,NaN,804,Clouds,couvert,04d
37,stations,10000.0,1787579170,7200,6446851,Artigat,200,Le Carla Bayle,1.3936,43.1500,...,FR,1787548189,1787597058,NaN,NaN,2.92,501,Rain,pluie modérée,10d
38,stations,10000.0,1787579171,7200,3018174,Foix,200,Foix,1.6054,42.9639,...,FR,1787548156,1787596989,2.0,2092354.0,25.26,503,Rain,très forte pluie,10d
39,stations,10000.0,1787579173,7200,6446851,Artigat,200,Le Mas d'Azil,1.3613,43.0795,...,FR,1787548203,1787597059,2.0,2092354.0,13.32,502,Rain,forte pluie,10d
40,stations,NaN,1787579174,7200,6432068,Preignan,200,Mirepoix,0.6719,43.7458,...,FR,1787548305,1787597288,2.0,2031069.0,1.19,501,Rain,pluie modérée,10d
41,stations,10000.0,1787579175,7200,3005712,Lavelanet,200,Montsegur,1.8337,42.8708,...,FR,1787548110,1787596926,2.0,2001435.0,NaN,802,Clouds,partiellement nuageux,03d
42,stations,10000.0,1787579176,7200,3018172,Foix,200,Niaux,1.5911,42.8093,...,FR,1787548174,1787596978,2.0,2092354.0,NaN,800,Clear,ciel dégagé,01d
43,stations,10000.0,1787579177,7200,2978760,Saint-Lizier,200,Saint Lizier,1.1355,43.0025,...,FR,1787548265,1787597106,NaN,NaN,4.65,502,Rain,forte pluie,10d
44,stations,10000.0,1787579178,7200,3036674,Artigat,200,Saint Martin d'Oydes,1.4955,43.1697,...,FR,1787548162,1787597035,2.0,2092354.0,6.31,502,Rain,forte pluie,10d
45,stations,10000.0,1787579179,7200,6426331,Tarascon-sur-Ariège,200,Tarascon sur Ariege,1.6043,42.8492,...,FR,1787548167,1787596979,2.0,2092354.0,0.12,500,Rain,légère pluie,10d
46,stations,10000.0,1787578962,7200,2972315,Toulouse,200,Toulouse,1.4442,43.6045,...,FR,1787548133,1787597089,1.0,6467.0,NaN,802,Clouds,partiellement nuageux,03d
47,stations,10000.0,1787579181,7200,2993002,Montauban,200,Montauban,1.3550,44.0176,...,FR,1787548114,1787597151,NaN,NaN,NaN,801,Clouds,peu nuageux,02d
48,stations,10000.0,1787579183,7200,3032797,Biarritz,200,Biarritz,-1.5527,43.4711,...,FR,1787548866,1787597795,1.0,6478.0,NaN,803,Clouds,nuageux,04d
49,stations,10000.0,1787579184,7200,3232791,Le Limpou,200,Bayonne,-1.4737,43.4945,...,FR,1787548844,1787597778,1.0,6478.0,NaN,804,Clouds,couvert,04d
50,stations,10000.0,1787579185,7200,3006787,La Rochelle,200,La Rochelle,-1.1516,46.1597,...,FR,1787548497,1787597971,1.0,6458.0,NaN,804,Clouds,couvert,04d

In [23]:
df_weather.to_csv("data/cities_weather.csv", index=False) # avoid a second index creation

In [34]:
hotels = pd.read_csv("data/hotels_scrap.csv")

In [36]:
weather = pd.read_csv("data/cities_weather.csv")

In [37]:
cities_weather_hotels = pd.merge(weather, hotels, left_on="name", right_on="city", how="left")

In [39]:
cities_weather_hotels.to_csv("data/cities_weather_hotels.csv", index=False)

In [38]:
display(cities_weather_hotels.head())

,base,visibility,dt,timezone,id,name_x,cod,name_city,coord.lon,coord.lat,...,sys.id,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,city,name_y,price,score
0,stations,10000.0,1787579129,7200,6435453,Huisnes-sur-Mer,200,Mont Saint Michel,-1.5115,48.6360,...,NaN,NaN,804,Clouds,couvert,04d,NaN,NaN,NaN,NaN
1,stations,10000.0,1787579130,7200,2978640,Saint-Malo,200,Saint Malo,-2.0260,48.6495,...,6557.0,NaN,804,Clouds,couvert,04d,Saint-Malo,Kyriad Prestige Saint-Malo,€ 188,"Avec une note de 8,9\n8,9\nSuperbe\n6 971 expé..."
2,stations,10000.0,1787579130,7200,2978640,Saint-Malo,200,Saint Malo,-2.0260,48.6495,...,6557.0,NaN,804,Clouds,couvert,04d,Saint-Malo,ibis Saint Malo Plage,€ 174,"Avec une note de 8,6\n8,6\nSuperbe\n2 480 expé..."
3,stations,10000.0,1787579130,7200,2978640,Saint-Malo,200,Saint Malo,-2.0260,48.6495,...,6557.0,NaN,804,Clouds,couvert,04d,Saint-Malo,Hotel Kyriad Saint Malo Centre Plage,€ 183,"Avec une note de 8,4\n8,4\nTrès bien\n1 873 ex..."
4,stations,10000.0,1787579130,7200,2978640,Saint-Malo,200,Saint Malo,-2.0260,48.6495,...,6557.0,NaN,804,Clouds,couvert,04d,Saint-Malo,Hôtel Cartier,€ 305,"Avec une note de 8,5\n8,5\nTrès bien\n2 334 ex..."